### ISSUE TITLE
Implement containsAny and containsNone on primitive iterables.

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1007]

**Comment by rinatigati** [comment]
Hey @donraab, I would like to work on this!

**Comment by donraab** [comment]
Hi @rinatigati, I assigned the issue to you. Thanks for volunteering!

**Comment by nikhilnanivadekar** [comment]
Before we do primitive we should finish up for object side. So that this one will be easier to implement

**Comment by donraab** [comment]
I disagree. The primitive one is actually easier and more straightforward.
