### ISSUE TITLE
Provide ability to create Hashing Strategy Sets, Maps and Bags using Function

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#1008]
Current: 
`HashingStrategySets.mutable.with(HashingStrategies.fromFunction(Person::getName));`

The below should work once this issue is fixed:
`HashingStrategySets.mutable.with(Person::getName);`

**Comment by donraab** [comment]
@nikhilnanivadekar I think we should use a different name than `with`. I realize from looking at the above that we have a method `with` which takes a `HashingStrategy`. I think the factory method which takes a function could just be called `fromFunction`.

**Comment by goldbal330** [comment]
I could work on it. Thanks.
