### ISSUE TITLE
Implement selectWithIndex, rejectWithIndex on OrderedIterable

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#1033]

**Comment by hvydya** [comment]
Hi! I'd like to work on this. Can you assign it to me?

**Comment by nikhilnanivadekar** [comment]
Hi @hvydya I started implementing this and have been thinking about the usefulness of the API. I don’t want anyone to spend time on this if we won’t take the API in the library. Is there some other issue that interests you?

**Comment by hvydya** [comment]
Ah that's fine. I'll comment under the respective issue if I find something I like.

Thanks 👍 .

**Comment by prathasirisha** [comment]
Closing this issue - these two APIs were released in the 11.0 release 😄 PR - https://github.com/eclipse/eclipse-collections/pull/1116
