### ISSUE TITLE
Optimize ImmutableListFactoryImpl.withAll(Iterable)

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1038]
The final return should call `ImmutableArrayList.newList(items)` to reduce an extra array creation.

**Comment by richardduffett** [comment]
Hi @donraab, I'd like to work on this issues if it's still available.

**Comment by donraab** [comment]
Assigned. Thanks for volunteering @richardduffett. There may be additional optimizations in this particular method call, but this was the first one that jumped out at me. There are some challenges here though. If you remove the one call path, you get rid of the extra array copy for lists > size 20, but lose the optimization for small lists.

**Comment by donraab** [comment]
Hi @richardduffett, I took a look at this today. I believe we can solve the problem by moving the creation code into a new static constructor method on ImmutableArrayList which takes `Iterable`. This new method can call `Iterate.toArray(Iterable)`, and determine whether to create one of the 10 small (ImmutableSingleton, ImmutableDoubleton, etc.) lists or create an `ImmutableArrayList` using the array that was just created.

**Comment by mohrezaei** [comment]
Alternatively, you can change the private constructor of `ImmutableArrayList(T[] newElements)` to package and call it from the factory.

**Comment by nikhilnanivadekar** [comment]
That is what is done for other collections so, we should definitely make the constructor package private.

**Comment by donraab** [comment]
@mohrezaei @nikhilnanivadekar @motlin The issue with making the constructor package private is that someone could create a class in the same package (outside of the library) and construct an `ImmutableArrayList` with an array that could be modified outside of the class.

We have a potential problem I think we need to fix in `Iterate.toArray` as well. There is no guarantee that a call to `Collection.toArray()` or `RichIterable.toArray()` returns a new array. A `Collection` implementer could decide to return a cached array. I think we should force creation of a new array in `Iterate.toArray()` by calling `Collection.toArray(Object[])` instead and verifying the return result is the same array instance that is passed in. Otherwise, we would have to copy the array created from `toArray()` to be safe.

Thoughts?

**Comment by mohrezaei** [comment]
One could also use reflection to make the method public and call it. We have tons of immutable classes with package private constructors. It's the main pattern used to construct these.

as for `toArray`, it's properly documented: "The returned array will be "safe" in that no references to it are
maintained by this collection."

**Comment by donraab** [comment]
The difference with the other package private constructors is that they take references to objects, not an array, and store them in private final fields. The reference once stored in the immutable collection cannot be changed (except via reflection).

I think we can possibly achieve a safer result by using `toArray(Object[])` instead of  relying on `toArray()` being "safe" or always creating a copy which is what I think Guava does.

**Comment by mohrezaei** [comment]
I strongly disagree. Creating large amounts of garbage because some code out in the wild is violating the written contract of a method should be left to the likes of Guava.

**Comment by nikhilnanivadekar** [comment]
There is only so much we can do to protect users from doing something which they shouldn’t do. By making things package private I believe we solve majority ( all of reasonable) use cases. For users trying to do something unconventional there will always be ways and I don’t think we should change our library to support these edge cases.

**Comment by donraab** [comment]
To be clear, I'm arguing against any excess copying. My suggestion of using `toArray(Object[])` would not be fool proof anyway. Someone could decide the cache the array in the method call. 

If we agree that bad actors always have reflection to do bad things, then I think I can see clear to going the package private route you're both advocating for to simplify things and solve for the majority.

**Comment by motlin** [comment]
Reflection can be prevented using a SecurityManager. Immutable should mean that you really can't change anything if you prevent refletion. Guava correctly protects against the vector @donraab mentions by first calling toArray() and then calling Arrays.copyOf() on that array.

**Comment by mohrezaei** [comment]
@motlin I disagree. We're talking about a piece of code that is either in violation of a written contract or in the hands of someone hell bent on doing whatever they way. In the latter case, SecurityManager is irrelevant. In the former case, it's a bug outside our library and should be fixed. It's trivial to write buggy code outside our library that destroys all of our contracts, let alone immutable stuff. Want a hash structure that makes no sense? just write a bad hashcode/equals. Want an immutable structure that's totally useless? fill it with mutable objects, mutate them and watch sparks fly. Want a list that reports the wrong size? add to it in multiple threads. Etc, etc.

**Comment by donraab** [comment]
@motlin Our Immutable types are interfaces so they can just be implemented today with mutable implementations by someone who wants to do that. The only way this could be locked down is with Sealed Types, which we will probably not have available for use in EC in a very long time.

**Comment by richardduffett** [comment]
It looks like the consensus is to go down the package private constructor route.  I'll proceed on that basis unless there are objections.

**Comment by prathasirisha** [comment]
Closing this issue, as this was addressed in this PR - https://github.com/eclipse/eclipse-collections/pull/1050
