### ISSUE TITLE
Allow primitive map put method to return the previous value

### ISSUE THREAD

**Issue by victornoel** [eclipse/eclipse-collections#1042]
It would be very useful for the put method on primitive maps to return the previous value. I suppose it's not obvious how to identify the non-present value, maybe with Optional{Int, Long, Double, ...}?

For now, I had to write this:
```java
int newValue = 5;
int[] prev = { -1 };
objectToIntMap.updateValue(key, -1, previous -> {
  prev[0] = previous;
  return newValue;
 });
if (prev[0] == -1 || prev[0] != newValue) {
  changed = true;
}
```

This is a bit sad ^^

**Comment by mohrezaei** [comment]
We purposely avoid garbage and wrapping in the common methods. To avoid breaking that, we'd have to introduce a new method.

**Comment by goldbal330** [comment]
I could work on it if help is needed.

**Comment by victornoel** [comment]
@goldbal330 we can also introduce the required Optional classes in EC I guess

**Comment by donraab** [comment]
@victornoel @goldbal330 I'd prefer not to add the missing primitive Optional classes in EC. I would recommend maybe having a signature that can handle an "if absent" case by providing a default value. The naming might be a bit awkward.

options:

`getOrDefaultAndPut(K key, int defaultValue, int putValue)`

or

`getAndPut(K key, int defaultValue, int putValue)`

**Comment by victornoel** [comment]
@donraab my initial issue is that I didn't want to associate an existing `int` value to the concept of absent value. If I have a map that does not contain a value, I don't want `-1` or `NaN` to mean this, I want the concept to be explicit.

Still, `getOrDefaultAndPut`/`getAndPut` is better than nothing and could be more useful than the current API in case I am able to use a special value to represent absence :)

**Comment by donraab** [comment]
@goldbal330 I assigned this to you as requested... @victornoel we can can see how the API looks in PR and suggest any changes as necessary.
