### ISSUE TITLE
Add toSortedMap and toSortedMapBy to Collectors2

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1046]
The methods `toSortedMap` and `toSortedMapBy` exist on `RichIterable` but there is no equivalent methods on the `Collectors2` utility class.

**Comment by rajivsethumadhavan** [comment]
@donraab  - I'd like to work on this. Can you please assign it to me?

**Comment by nikhilnanivadekar** [comment]
Done @rajivsethumadhavan
