### ISSUE TITLE
ImmutableStack should return Pair for pop and pop(int)

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1048]
The primary purpose of `pop` is to remove and return the thing(s) you want from the top of a stack.

Today the signature of `pop` and `pop(int)` on ImmutableStack are as follows:

```
ImmutableStack<T> pop();

ImmutableStack<T> pop(int count);
```
A new ImmutableStack instance is returned with the element(s) removed, but they element(s) are not returned. .

I believe the signatures should be:
```
Pair<T, ImmutableStack<T>> pop();

Pair<ListIterable<T>, ImmutableStack<T>> pop(int count);
```
Today, these APIs are inconsistent with `peek` and `peek(int)`.

**Comment by mohrezaei** [comment]
A stack is the most mutable of data structures. An immutable one is already so far beyond the pale that its API are likely completely irrelevant to any real use case. Can anybody conjure a usecase for an immutable stack?

**Comment by donraab** [comment]
I tend to agree. I think @motlin has or knows of a use case. The issue I have is if we are going to keep the interfaces and implementation, the pop methods should be consistent with the mutable side and work for the immutable side.
