### ISSUE TITLE
Useless type parameter in DoubleComparator and equivalents

### ISSUE THREAD

**Issue by victornoel** [eclipse/eclipse-collections#1074]
The interface `DoubleComparator` is defined as:
```java
public interface DoubleComparator<T>
        extends Serializable
{
    int compare(double value1, double value2);
}
```

The type parameter `T` is clearly useless :)

**Comment by donraab** [comment]
Thanks for raising this issue @victornoel. The generic parameter clearly can and should be removed here.

**Comment by vmzakharov** [comment]
I believe this was fixed in this PR: https://github.com/eclipse/eclipse-collections/pull/1052
