### ISSUE TITLE
FastList broken after upgrade to java 16 from 15 due to module error

### ISSUE THREAD

**Issue by MPdaedalus** [eclipse/eclipse-collections#1075]
Hi I just upgraded to java 16 in eclipse and now fastutil is throwing an error 

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.eclipse.collections.impl.list.mutable.FastList.addAllArrayList(FastList.java:311)
	at org.eclipse.collections.impl.list.mutable.FastList.addAll(FastList.java:283)
	at main.Start.main(Start.java:20)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.lang.Object[] java.util.ArrayList.elementData accessible: module java.base does not "opens java.util" to unnamed module @66ff6b1
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at org.eclipse.collections.impl.utility.ArrayListIterate.<clinit>(ArrayListIterate.java:108)
	... 4 more

worked fine in java 15, all I am doing is creating a new fastlist<String> and populating it using a List<String> to addAll()

I can get round the problem using the VM flag
--add-opens java.base/java.util=ALL-UNNAMED
but this is only a workaround not a bugfix.

**Comment by nikhilnanivadekar** [comment]
Instead of addAll() does it work when you use add() and iterate over one element at a time and add? I am asking to understand the impact.
As far as the issue goes this is due to Array copy methods and if you are using the module system you will need to include the Java.util module.

**Comment by nikhilnanivadekar** [comment]
In your specific use case, it is happening because the `addAll(Iterable)`, the Iterable is an ArrayList. And we have a small optimization to support fast copies. You can get around the problem as follows (without adding the new module). 

```
MutableList previousList = Lists.mutable.empty();
MutableList intermediate = Lists.mutable.withAll(yourArrayList);

previousList.addAll(intermediate);
```

Thanks for reporting this. We will come up with a way to remove that optimization and fix it for 11.0.0 version.

**Comment by MPdaedalus** [comment]
Just tested it now, does not throw error if you manually iterate using add() only the addAll() does it, thanks for quick response

**Comment by mohrezaei** [comment]
The solution is trivial: catch `Throwable`, not `Exception` in `ArrayListIterate`

**Comment by mohrezaei** [comment]
JDK 16 also comes with a new flag: [--illegal-access](https://openjdk.java.net/jeps/261#Relaxed-strong-encapsulation). Using `--illegal-access=permit` or `--illegal-access=warn` should resolve the runtime issue.

**Comment by MPdaedalus** [comment]
@mohrezaei yes but its a bit of a blunt instrument if you ask me

**Comment by MPdaedalus** [comment]
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.

just came up for me

**Comment by mohrezaei** [comment]
The flag is a temporary workaround, and meant to be used for this, probably a bit less blunt than `--add-open`. The actual fix (catching Throwable) is trivial and can be rolled out quickly, even for old versions.

**Comment by nikhilnanivadekar** [comment]
Moh would prefer not to do backports. We can do it as a part of 11.0.0 fix. As it stands it’s not something for which there is no workaround. The user has 4 ways of dealing with the issue:
1) Iterate and add
2) Create an intermediate FastList and allAll()
3) Add jvm args to open the module 
4) Add jvm args to warn for illegal access

**Comment by mohrezaei** [comment]
The error happens when ArrayListIterate class is loaded, not necessarily when addAll is called, so it has much wider impact. Even if it was just addAll, (1) and (2) don't make sense. I think you meant:

Find and replace all existing code that uses addAll, including in all libraries with:
1. Iterate and add
2. Create an intermediate FastList and allAll()

which to put it simply is not feasible. (Also, addAll is part of the core List api, so you never know if it's being called on a FastList. It may even be called from within JDK itself if a FastList is passed in to some JDK method).

**Comment by nikhilnanivadekar** [comment]
Fair enough, in that case, we need backport it only to 10.4.0 because this issue happens only in JDK-16+. If you raise a PR with the fix, happy to do a 10.5.0 release with this one change.
Would it make sense to just remove the optimization as it relies on reflection?

**Comment by mohrezaei** [comment]
A separate PR from #1076 ? 
Removing the optimization is something we can consider for later. The optimization works fine for JDK < 16.

**Comment by nikhilnanivadekar** [comment]
you are faster than ether 😄

**Comment by mohrezaei** [comment]
Looks like I misread the stack trace. This was fixed in 2017. @MPdaedalus you must be running an ancient version of the library. Please upgrade to anything released in the last 3 years.

**Comment by nikhilnanivadekar** [comment]
We have a compatibility matrix : https://github.com/eclipse/eclipse-collections#eclipse-collections-and-jdk-compatibility-matrix

**Comment by MPdaedalus** [comment]
my current pom.xml

		<dependency>
			<groupId>org.eclipse.collections</groupId>
			<artifactId>eclipse-collections-api</artifactId>
			<version>10.4.0</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.collections</groupId>
			<artifactId>eclipse-collections</artifactId>
			<version>10.4.0</version>
		</dependency>

**Comment by MPdaedalus** [comment]
is there a way to double check with an api call?

**Comment by mohrezaei** [comment]
There is no api call to return a version or something. Check your classpath.

**Comment by MPdaedalus** [comment]
your right! my class path says 7.1.2, how an earth this happened I don't know. Thanks for the info
Sorry to lead you down a rabbit hole!

**Comment by MPdaedalus** [comment]
I think I found the problem, I am using https://oss.sonatype.org/content/repositories/snapshots repository in maven because some eclipse projects I am using require the latest snapshot but eclipse collections on sonatype have not been updated in ages.
