### ISSUE TITLE
Add fused method for collect and makeString

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1087]
What do folks think about adding a fused method for `collect` + `makeString` to `RichIterable`? I marked this issue as committer discussion as the pattern shows up in the Pet Kata, but I'm not sure if it would pull its weight in production use cases. 

The method `collectString` would basically replace this pattern, and the other variants of `makeString`.

Before:
```
String names = person.getPets()
        .asLazy()
        .collect(Pet::getName)
        .makeString(" & ");
```
After:
```
String names = person.getPets().makeString(Pet::getName, "", " & ", "");
```

I would we start by adding a single default method to `RichIterable` as an overload the three parameter version of `makeString`.

This is the current makeString method.

`default String makeString(String start, String separator, String end)`

The overload should look like this, combining `collect` and `makeString`.

`default String makeString(Function<? super T, String>, String start, String separator, String end)`

**Comment by nikhilnanivadekar** [comment]
Instead of collectString, I would say add an override to makeString. Makes
it easier to discover

**Comment by donraab** [comment]
Makes sense to me.

**Comment by gaurangkudale** [comment]
Hi @donraab and @nikhilnanivadekar  Can I work on this issue?

**Comment by donraab** [comment]
Hi @gaurangkudale, please feel free to work on this. I agree with @nikhilnanivadekar that defining overloads of `makeString` which take a `Function` would make the most sense for discoverability. I'll edit the issue title and example above.

**Comment by gaurangkudale** [comment]
Hi @donraab,
Can you please direct me to the code where it has to change and also what exactly I've to do that will help to get started

**Comment by donraab** [comment]
Hi @gaurangkudale, the first thing you will need to do is understand what the `collect` and `makeString` methods do in Eclipse Collections. If you haven't already, I recommend completing the [Eclipse Collections Katas](https://github.com/eclipse/eclipse-collections-kata) to familiarize yourself with the `collect` and `makeString` methods and the rest of the Eclipse Collections API to see where methods are defined and how. The Pet Kata has several examples using both `collect` and `makeString` in the tests. I would start there. 

The following is a great blog from a first time contributor to Eclipse Collections where he details his journey. I now recommend this blog to help all first time contributors through their first contribution.

https://mydeveloperplanet.com/2021/01/20/how-to-start-contributing-to-open-source/ 

After taking the katas and learning the current API, the following blogs should help you learn about fused methods that already exist in EC. These blogs should give you a very clear idea of how to add a new fused method to the `RichIterable` interface. This is the top level interface where the method will need to be defined, and it should be added as a default method.

1.  [Fusing Methods for Productivity](https://medium.com/javarevisited/fusing-methods-for-productivity-c15c9eb2d666?source=friends_link&sk=ddde162c6aab068bda4619266d3b3bfb)
2. [From Eager to Fused to Lazy](https://medium.com/javarevisited/from-eager-to-fused-to-lazy-66450e290002?source=friends_link&sk=1c61f413a8148ece8e60e0a2a87137b3)

Thank you for your interest in learning and contributing to Eclipse Collections!

**Comment by gaurangkudale** [comment]
Hi @donraab Thank you so much to guide me I'll take time to read the blogs and learn these methods and I'm really excited to contribute

**Comment by Desislav-Petrov** [comment]
@gaurangkudale are u still working on that or are u happy for me to take over?

**Comment by gaurangkudale** [comment]
> @gaurangkudale are u still working on that or are u happy for me to take over?

Sure Go on we will collaborate

**Comment by Desislav-Petrov** [comment]
Thx - I've raised the PR

**Comment by Desislav-Petrov** [comment]
@donraab given we've merged the PR do we still need this issue as open?
