### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by anuva04** [eclipse/eclipse-collections#1105]
It can return different **datatype** depending on the different iteration method used in

> https://github.com/eclipse/eclipse-collections/blob/master/docs/EclipseCollectionDiagram.png

**Comment by Anjali2312-Thombare** [comment]
I am interested in solving this issue 
please assign me this issue

**Comment by donraab** [comment]
Thanks for the interest in contributing @Anjali2312-Thombare. This issue also appears to have been fixed so I will close it. Thank you for finding these issues though so that I can close them.

**Comment by Anjali2312-Thombare** [comment]
Thank you for informing me
Please assign me any beginner friendly issues
