### ISSUE TITLE
Add toImmutableSortedListBy to Collectors2 

### ISSUE THREAD

**Issue by prathasirisha** [eclipse/eclipse-collections#1136]
Add `toImmutableSortedListBy` to `Collectors2` utility class. 

See `toSortedListBy` for reference (mutable side equivalent)

**Comment by Utkarshn10** [comment]
Hi @prathasirisha I would like to work on this!

**Comment by donraab** [comment]
Hi @Utkarshn10, thanks for volunteering, I assigned the issue to you.

**Comment by Utkarshn10** [comment]
> Hi @Utkarshn10, thanks for volunteering, I assigned the issue to you.
Hi @donraab it is my pleasure contributing to collections which I have been using for about 2 yrs now.

**Comment by Utkarshn10** [comment]
Hi @donraab @prathasirisha I have created a PR.
