### ISSUE TITLE
Add toImmutableSortedSetBy to Collectors2

### ISSUE THREAD

**Issue by prathasirisha** [eclipse/eclipse-collections#1137]
Add `toImmutableSortedSetBy` to `Collectors2` utility class. 

See `toSortedSetBy` for reference (mutable side equivalent)

**Comment by HarrietLyBui** [comment]
I am new to open source contribution. May I work on this issue?

**Comment by donraab** [comment]
Hi @HarrietLyBui, I assigned the issue to you. Thank you and welcome to open source!

**Comment by HarrietLyBui** [comment]
Thank you!

**Comment by HarrietLyBui** [comment]
I am having issues running ` $ mvn install -DskipTests=true` to create primitive collections after installing Maven:

**Comment by Utkarshn10** [comment]
Hi @HarrietLyBui, you can use Gitpod and directly add java extensions to it and you are good to  go. I also faced some issues(not the one above mentioned) in the beginning and then I worked on Gitpod and everything  worked smoothly afterwards. 
But if  you want to continue working on  your system then I  would recommend you to reinstall maven and add env variables  correctly. Hope this  helps!!

**Comment by HarrietLyBui** [comment]
@Utkarshn10 Thank you so much for the suggestion! I'll try Gitpod!

**Comment by HarrietLyBui** [comment]
Gitpod works for me!

**Comment by HarrietLyBui** [comment]
When I tried to run on GitPod
` mvn clean install checkstyle:check findbugs:check --projects "!scala-unit-tests,!jmh-scala-tests,!jmh-tests" -DskipTests=true
`
I got an error saying: `bash: !scala: event not found` 
Has anyone run into this issue? @Utkarshn10 @prathasirisha
