### ISSUE TITLE
Add toImmutableSortedBagBy to Collectors2 

### ISSUE THREAD

**Issue by prathasirisha** [eclipse/eclipse-collections#1138]
Add `toImmutableSortedBagBy` to Collectors2 utility class.

See `toSortedBagBy` for reference (mutable side equivalent)

**Comment by Utkarshn10** [comment]
@prathasirisha I tried working on the Issue. Could you please guide me how to run the tests before I create a PR. I am attaching ss of the work.
![Screenshot (23)](https://user-images.githubusercontent.com/58587256/132497773-63f56530-9a32-438c-ad90-358604418a37.png)

**Comment by prathasirisha** [comment]
Hi @Utkarshn10 - the tests for this class will be here Collectors2Test.java
See tests `toSortedBagBy()` and `toSortedBagByParallel()` for reference, you will be adding equivalent immutable methods as part of this PR. Hope this helps!

**Comment by Utkarshn10** [comment]
Hi @prathasirisha thanks for helping. I have added the tests related to toImmutableSortedBagBy and toImmutableSortedBagByParallel in the  Collectors2Test.java as well as have added toImmutableSortedBagBy to Collectors.java. Are there any  tests that I should run before creating  a PR or should I create a PR directly ? I referred https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md but couldnt find anything related to tests. Thanks in Advance!!

**Comment by prathasirisha** [comment]
Related merged PR #1139. 

@Utkarshn10 For your next commit, you can link the issue and PR using your commit message. Second point [here.](https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md#commit-messages) Thank you once again for your contribution!
