### ISSUE TITLE
Unable to see the progress dialog when the welcome screen came

### ISSUE THREAD

**Issue by sanoj-s** [eclipse/eclipse-collections#1141]
Unable to see the progress dialog when the welcome screen came. Here installed a new eclipse and directly opened Eclipse Marketplace and installing one plugin - Kotlin. After that, I saw the progress at the bottom. When I click on that the progress dialog not coming in front. Usually, it will come in the normal cases when we are in the Eclipse Editor. 

![Unable to see the progress dialog when the welcome screen came](https://user-images.githubusercontent.com/53048769/133283335-31d673e2-ce2c-448d-a58a-51b4325c0932.JPG)

**Comment by donraab** [comment]
Hi @sanoj-s, the Eclipse Collections project is not related to to the Eclipse IDE. They are both projects at the Eclipse Foundation, but that is the extent of their association. I would recommend looking at the Eclipse JDT project to find the appropriate support group.

https://projects.eclipse.org/projects/eclipse.jdt
