### ISSUE TITLE
Maven dependencies not able to download in Eclipse

### ISSUE THREAD

**Issue by vishnuprakash9845** [eclipse/eclipse-collections#1170]
So in the pom.xml tried to download the Java Client dependency, but getting the below error

Eclipse Version: 2020-09 (4.17.0)
Build Id: 20200910-1200

Can anyone help me on this issue please

Description Resource Path Location Type
Error while downloading 'https://maven.apache.org/xsd/maven-4.0.0.xsd' to /Users/muniswamyv/.lemminx/cache/https/maven.apache.org/xsd/maven-4.0.0.xsd. pom.xml /appiumFramwork line 1 Language Servers
Description Resource Path Location Type
Error while downloading 'https://maven.apache.org/xsd/maven-4.0.0.xsd' to /Users/vishnu/.lemminx/cache/https/maven.apache.org/xsd/maven-4.0.0.xsd. pom.xml /appiumFramwork line 1 Language Servers
Description Resource Path Location Type
Missing artifact io.appium:java-client:jar:7.6.0 pom.xml /appiumFramwork line 1 Maven Dependency Problem
Description Resource Path Location Type
Missing artifact io.appium:java-client:jar:7.6.0 pom.xml /appiumFramwork line 1 Maven Dependency Problem
![image](https://user-images.githubusercontent.com/24207575/146875787-80af8d7e-16f5-4278-8ec3-e4eccf68e868.png)

**Comment by prathasirisha** [comment]
Hi @vishnuprakash9845, the Eclipse Collections project is not related to the Eclipse IDE. Closing the issue.
