### ISSUE TITLE
Update JavaDoc website generation to use Java 17.

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1173]
There is some new support for `@since` tags in the JavaDoc compiler for Java 17 that would be good to leverage.

https://www.oracle.com/java/technologies/javase/17all-relnotes.html#JDK-8263468

**Comment by nikhilnanivadekar** [comment]
It can’t be used because we have to build Javadoc binaries and push them to
maven central. This is required so that IDEs can show inline help.

**Comment by donraab** [comment]
IIRC we were already building with Java 9 so we had search enabled in JavaDoc.

**Comment by nikhilnanivadekar** [comment]
Those Javadocs are published only to the website. The maven central jar
needs to have Javadoc artifacts as well which need to be Java 8 compatible.
Take a look at the artifacts published on maven central.

**Comment by donraab** [comment]
I'm talking only about the ones published to the website then :).

**Comment by nikhilnanivadekar** [comment]
The Javadocs need to be compatible with Java 8, so, as long as it’s not
breaking, it should be fine. I think we have a GitHub build to verify that
as well.
