### ISSUE TITLE
Add multiReader to Lists factory in API module

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1202]
The Lists factory in the impl module has a multiReader version, that should be added to the API module version of Lists.

API module version:
https://github.com/eclipse/eclipse-collections/blob/master/eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/Lists.java

Impl module version:
https://github.com/eclipse/eclipse-collections/blob/master/eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Lists.java

**Comment by aqsa505** [comment]
Hey Don, I would like to work on this issue.

**Comment by donraab** [comment]
Hi @aqsa505, thank you for volunteering. I have assigned the issue to you.
