### ISSUE TITLE
Generate primitive->object Map factories in API using ServiceLoader.

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1214]
This should follow the same pattern as the primitive List factories that are now generated in the API module.

**Comment by Desislav-Petrov** [comment]
Happy to have a go - mind assigning this to me please?

**Comment by donraab** [comment]
Hi @Desislav-Petrov, this is what the **impl** version of `IntObjectMaps` currently looks like after code gen. This is staying exactly the same as it is today.

```
public final class IntObjectMaps
{
    public static final ImmutableIntObjectMapFactory immutable = ImmutableIntObjectMapFactoryImpl.INSTANCE;
    public static final MutableIntObjectMapFactory mutable = MutableIntObjectMapFactoryImpl.INSTANCE;

    private IntObjectMaps()
    {
        throw new AssertionError("Suppress default constructor for noninstantiability");
    }
}
```

This is what the **api** version of `IntObjectMaps` should look like after code gen after you finish the appropriate templates.

```
public final class IntObjectMaps
{
    public static final ImmutableIntObjectMapFactory immutable = 
            ServiceLoaderUtils.loadServiceClass(ImmutableIntObjectMapFactory.class);
    public static final MutableIntObjectMapFactory mutable =
            ServiceLoaderUtils.loadServiceClass(MutableIntObjectMapFactory.class);

    private IntObjectMaps()
    {
        throw new AssertionError("Suppress default constructor for noninstantiability");
    }
}
```

The difference between these two is the use of `ServiceLoader` to dynamically instantiate the appropriate factory at runtime so that the API module does not depend on the impl module. Take a look at the PR for the api version of `IntSets` for more guidance. 

https://github.com/eclipse/eclipse-collections/pull/1212

**Comment by Desislav-Petrov** [comment]
All clear now - thanks for the explanation. Doing the test template and will submit a PR shortly.

**Comment by Desislav-Petrov** [comment]
PR merged so guess we can close @donraab ? Thanks for the help & guidance on this one!
