### ISSUE TITLE
Add injectIntoKeyValue to primitive Maps

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1217]
Today we can iterate over the key / value combinations in primitive maps using `forEachkeyValue`. It would be nice to have a method which injects some mutable result into the iteration and returns it. The following is possible today for instance for transferring a primitive map's data to an object map.

```
IntObjectMap source;
MutableMap<?, ?> target = Maps.mutable.empty();
source.forEachKeyValue(target::put);
```

If we add `injectIntoKeyValue` to primitive maps, we can write the following:

`MutableMap<?, ?> target = source.injectIntoKeyValue(Maps.mutable.empty(), target::withKeyValue);
`

Today, we don't have any easier way to copy or transform data from a primitive map to an object map.

This issue came up in a question on SO today. The OP was looking for a Map view of the primitive maps so they could pass it to another API. 

https://stackoverflow.com/questions/71349112/how-convert-adapt-byteobjecthashmap-to-a-jdk-map

**Comment by victornoel** [comment]
See also https://github.com/eclipse/eclipse-collections/issues/746, related to the SO question :)

**Comment by donraab** [comment]
Ha, thanks for linking @victornoel! Upvoted again. 😄  The `injectIntoKeyValue` solution is more general and could be used to implement `toMap`. I think both methods are reasonable adds.

**Comment by emilie-robichaud** [comment]
Can I work on this issue?

**Comment by donraab** [comment]
Thanks for volunteering @emilie-robichaud. I assigned the issue to you.
