### ISSUE TITLE
Add of and with factory methods to object -> primitive map factories.

### ISSUE THREAD

**Issue by johnjstuart** [eclipse/eclipse-collections#1236]
Currently the API factories for object -> primitive maps are lacking the equivalent `of()` and `with()` methods that appear on the impl factories as well as on the API factory for object -> object maps.

Immutable object -> primitive map factories have the empty `of()` and  `with()` methods as well the single key value pair versions: `of(K key, <primitive> value)` and `with(K key, <primitive> value)`

On the mutable side, only the empty `of()` and  `with()` methods exist on the current object -> primitive factories.

The impl factories include up to 4 key value pairs for the `newWithKeysValues()` method. The API factories should match the impl side up to 4 key value pairs.

Consistency would dictate that a user should be able to do the following for immutable and mutable object primitive map factories for all primitive types:
```java
ObjectIntMaps.immutable.of("1", 1, "2", 2, "3", 3, "4", 4);
ObjectIntMaps.mutable.of("1", 1, "2", 2, "3", 3, "4", 4);
...
```

**Comment by donraab** [comment]
Thanks for creating the issue @johnjstuart. I assigned it to you in case you were already working on it.

**Comment by johnjstuart** [comment]
I unassigned it from me for now. I may come back to it in the future if it's still open, but I'll leave it for anyone else right now.

**Comment by goldbal330** [comment]
I could work on it.

**Comment by pochopsp** [comment]
Hello, I'm using Eclipse Collections 13.0.0, and I noticed that the Immutable counterpart of the primitive map factories doesn't include the of(...) with multiple key-value pairs. For now, just the mutable has it.
Furthermore, I was wondering why limit this factory method up to 4 key-value pairs, is there a reason behind this?
For instance, the factory method from the java standard library has 10 mappings: https://docs.oracle.com/javase/9/docs/api/java/util/Map.html#of-K-V-K-V-K-V-K-V-K-V-K-V-K-V-K-V-K-V-K-V- (which I find to be a lot more convenient)

**Comment by donraab** [comment]
> Hello, I'm using Eclipse Collections 13.0.0, and I noticed that the Immutable counterpart of the primitive map factories doesn't include the of(...) with multiple key-value pairs. For now, just the mutable has it. Furthermore, I was wondering why limit this factory method up to 4 key-value pairs, is there a reason behind this? For instance, the factory method from the java standard library has 10 mappings: https://docs.oracle.com/javase/9/docs/api/java/util/Map.html#of-K-V-K-V-K-V-K-V-K-V-K-V-K-V-K-V-K-V-K-V- (which I find to be a lot more convenient)

@pochopsp You can use a mutable primitive map as a builder for an immutable primitive map.

Examples can be found in this [blog](https://medium.com/oracledevs/as-a-matter-of-factory-part-3-method-chaining-224217074d31?source=friends_link&sk=ca02518f05ffeae69ce742fb3d68353d). Hope that helps.

**Comment by pochopsp** [comment]
Hi @donraab thanks for your kind reply. The article is great, thanks. So for having more than 4 mappings we can just use the `.withKeyValue` in chaining as suggested.
As regards the fact that the immutable factory only allows one key-value mapping, I guess the API was designed in such a way that to get a immutable map instance you would use toImmutable() on a mutable map most of times.

**Comment by pochopsp** [comment]
Hi @donraab I know it is not 100% related, but it still regards factory methods ofXX in factories.
I was wondering why having both `MutableList<T> ofInitialCapacity(int capacity)` and `MutableList<T> withInitialCapacity(int capacity)` inside `org.eclipse.collections.api.factory.list.MutableListFactory` if they basically do the same thing. I noticed they were both introduced with commit d61e62a88ce15f080

**Comment by donraab** [comment]
@pochopsp This might be a good question for StackOverflow. If you have questions like this, you can ask there and tag them as `eclipse-collections`. I still check SO on occasion and will answer if I see any. Eclipse Collections supports both `of` and `with` prefixes, so the two methods here would be following the same pattern. I explained the reason for both `of` and `with` on the factories in [this blog](https://medium.com/javarevisited/preposition-preference-1f1c709b098b?source=friends_link&sk=c6086d0f5d5da60e8f18ebbfa7c911f7).
