### ISSUE TITLE
Add multiReader to Bags factory in API module

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1237]
The `Bags` factory in the impl module has a multiReader version, that should be added to the API module version of Bags.

API module version:
https://github.com/eclipse/eclipse-collections/blob/master/eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/Bags.java

Impl module version:
https://github.com/eclipse/eclipse-collections/blob/master/eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Bags.java

**Comment by aqsa505** [comment]
Hey @donraab, I'd like to work on this.

**Comment by donraab** [comment]
Thanks @aqsa505, assigned it to you.
