### ISSUE TITLE
Add multiReader to Sets factory in API module

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1238]
The Sets factory in the impl module has a multiReader version, that should be added to the API module version of Sets.

API module version:
https://github.com/eclipse/eclipse-collections/blob/master/eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/Sets.java

Impl module version:
https://github.com/eclipse/eclipse-collections/blob/master/eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Sets.java

**Comment by emilie-robichaud** [comment]
I'll take this one!

**Comment by donraab** [comment]
Thanks @emilie-robichaud, assigned it to you.
