### ISSUE TITLE
Implement RichIterable.getOnlyOptional().

### ISSUE THREAD

**Issue by itohro** [eclipse/eclipse-collections#124]
Implement getOnly method that returns Optional on RichIterable. The method signature would look like below.

`Optional<T> getOnlyOptional()`

**Comment by PascalSchumacher** [comment]
Is this already assigned or can I try to implement this?

By the way: Thanks for providing eclipse-collections. :+1:

**Comment by nikhilnanivadekar** [comment]
This is not assigned to anyone.
Thanks @PascalSchumacher for volunteering to contribute.

**Comment by sendilkumarn** [comment]
@donraab can assign this to me? I will work on this :)

**Comment by donraab** [comment]
Hi @sendilkumarn , assigned the issue to you. Thanks for volunteering!

**Comment by donraab** [comment]
@motlin @nikhilnanivadekar @prathasirisha Does this API seem useful to you all? I am discussing this with @sendilkumarn currently. Returning an `Optional` here removes the need to deal with an exception, but am curious for your thoughts.

**Comment by nikhilnanivadekar** [comment]
I personally can’t think of a place I’ll use this. getOnly () is a specific API and it throws for a valid reason.

**Comment by donraab** [comment]
After digging in and thinking about this a bit, `getOnly` throws the same exception in the case of empty and > 1. It felt kind of odd to me at first with `Optional`, as the `optional.isPresent()` translates to "my size is exactly 1". I thought at first empty and > 1 would be interesting to differentiate, and thus returning `Optional.empty()` in the case of a size > 1 is weird.

**Comment by nikhilnanivadekar** [comment]
If I ever came across getOnlyOptional() how confusing will it be to debug the code. 
The optional is empty because the RichIterable was empty or of size > 1. I would probably replace that part of code with a simple size check. Again the entire idea of using getOnly() is specific and the correct usage is simple. 
What will advantage will we get by adding getOnlyOptional()?

**Comment by donraab** [comment]
After thinking on this API some more, and discussing with @sendilkumarn @prathasirisha @nikhilnanivadekar I'm of the opinion that this API would not be worthwhile to add. Its usage would be unclear and I can't see an advantage to adding the API. I'd want to see a compelling use case where getOnly is already used where this API would make the usage clearer, safer and simpler.

It was very helpful @sendilkumarn to see your draft PR and revisit this now four year old issue. Thank you for taking the time and effort to explore implementing the API.  Unless there are any compelling objections, I would recommend that we close the issue and the PR.

**Comment by sendilkumarn** [comment]
I do agree! It definitely adds an option but the value of this API is subtle. 

I closed the PR. Let us close the issue too!
