### ISSUE TITLE
Add injectIntoKeyValue to MapIterable

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1244]
`MapIterable` currently has `injectInto` which takes the values of the map. There is no equivalent that takes both key and value. This will provide better symmetry with `forEachKeyValue` which does exist.

The signature for this method should be as follows:

`<IV> IV injectIntoKeyValue(IV injectedValue, Function3<? super IV, ? super K, ? super V, ? extends IV> function);
`

It will need to be implemented as a default method on `MapIterable`, and overridden as necessary.

**Comment by emilie-robichaud** [comment]
Hi, can I work on this issue?

**Comment by donraab** [comment]
Hi @emilie-robichaud, I assigned the issue to you.
