### ISSUE TITLE
Add withKeyMultiValues to MutableMultimap and subtypes

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1307]
In addition to `withKeyValue`, which I describe here (https://github.com/eclipse/eclipse-collections/issues/1303), it would be useful to have a specialized `withKeyMultiValues` method which will take a single key and multiple values to add to the `Multimap`.

```
MutableListMultimap<String, String> multimap = Multimaps.mutable.list.empty()
        .withKeyMultiValues("A", Lists.mutable.with("Apple", "Apricot"))
        .withKeyMultiValues("B", Lists.mutable.with("Banana", "Blueberry"))
        .withKeyMultiValues("C", Lists.mutable.with("Cantaloupe", "Clementine"));
```

This could also be implemented via varargs.

```
MutableListMultimap<String, String> multimap = Multimaps.mutable.list.empty()
        .withKeyMultiValues("A", "Apple", "Apricot")
        .withKeyMultiValues("B", "Banana", "Blueberry")
        .withKeyMultiValues("C", "Cantaloupe", "Clementine");
```

**Comment by motlin** [comment]
I agree. I just wanted to point out that the method could be varargs (K, V...)

**Comment by goldbal330** [comment]
I could work on it if help is needed.

**Comment by donraab** [comment]
Thanks for volunteering, @goldbal330. Assigned!
