### ISSUE TITLE
Implement RichIterable.reduceBy().

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#134]
The existing method `RichIterable.aggregateBy(Function, Function0, Function2)` is conceptually a `groupBy()` followed by `injectInto()` on each group of values. This method would be a `groupBy` followed by `reduce()` on each group of values. Multiple variants are possible, but the first signature ought to be:

``` java
<K, T> MapIterable<K, T> reduceBy(
    Function<? super T, ? extends K> groupBy,
    Function2<? super T, ? super T, ? extends T> reduceFunction);
```

**Comment by donraab** [comment]
@motlin any progress on this?

**Comment by motlin** [comment]
It's still just an idea - I never worked on it.
