### ISSUE TITLE
Move collectPrimitive code to InternalArrayIterate from FastList and ArrayIterate

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1350]
`FastList` and `ArrayIterate` should have their implementations replaced with delegation to `InternalArrayIterate` for the following primitive `collect` methods.

```
collectBoolean
collectByte
collectChar
collectDouble
collectInt
collectFloat
collectLong
collectShort
```

**Comment by Desislav-Petrov** [comment]
I can look at that

**Comment by donraab** [comment]
Hi @Desislav-Petrov, thanks for volunteering. I have assigned this issue to you.
