### ISSUE TITLE
eclipse collection status

### ISSUE THREAD

**Issue by jbakoc1** [eclipse/eclipse-collections#1360]
The Roadmap at https://github.com/eclipse/eclipse-collections/wiki/Roadmap is still from 2021. Is the project active? Should we invest in learning?
thanks

**Comment by donraab** [comment]
Yes, the project is still active. We're aiming for an 11.1 release soon. After 11.1 we will be baselining EC on Java 11 for the 12.0 release. We will update the roadmap to indicate this. Most new features are contributions are contributions from the open source community, so hard to plan for those on a roadmap, as it is volunteer time.

You can keep up to date on some new features added by community members when they blog about them on Medium with an Eclipse Collections tag: https://medium.com/tag/eclipse-collections

Cc'ing our committers @prathasirisha @nikhilnanivadekar @motlin @mohrezaei
