### ISSUE TITLE
Add examples of iteration patterns for primitive Interval to reference guide

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1384]
The new reference guide is now in Asciidoc. The relevant section is now here:
https://github.com/eclipse/eclipse-collections/blob/master/docs/2-Collection_Containers.adoc#intinterval

Use the Lost and Found Kata as a guide for the iteration patterns that can be included for various primitive types.

https://github.com/eclipse/eclipse-collections-kata/tree/master/lost-and-found-kata

**Comment by sandip1805** [comment]
Hi @donraab , I would like to work on this, can you please assign this to me?

**Comment by donraab** [comment]
Hi @sandip1805 , thanks for volunteering! I've assigned it to you.
