### ISSUE TITLE
Add examples of iteration patterns for primitive Set to reference guide

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1385]
The new reference guide is now in Asciidoc. The relevant section is now here:
https://github.com/eclipse/eclipse-collections/blob/master/docs/2-Collection_Containers.adoc#primitive-sets

Use the Lost and Found Kata as a guide for the iteration patterns that can be included for various primitive types.

https://github.com/eclipse/eclipse-collections-kata/tree/master/lost-and-found-kata

**Comment by sandip1805** [comment]
Hi @donraab , can you assign this issue to me, I would like to work on this.

**Comment by donraab** [comment]
HI @sandip1805, thank you for volunteering! I have assigned this issue to you.

**Comment by sandip1805** [comment]
Hi @donraab , I have raised Pull Request. Can you please have a look?
