### ISSUE TITLE
UnmodifiablePrimitiveCollection implements MutablePrimitiveCollection

### ISSUE THREAD

**Issue by minQZ** [eclipse/eclipse-collections#1391]
```java
public abstract class AbstractUnmodifiableLongCollection
        implements MutableLongCollection, Serializable
```

As I know, mutable means modifiable, and unmodifiable means immutable. So how do these two coexist?

This leads to the following problem:

PrimitiveObjectMap.keySet() returns MutablePrimitiveSet.
```java
    /**
     * Returns a set containing all the keys in this map. The set is backed by the
     * map, so any modifications to the returned set will affect this map.
     * @return a mutable set containing the keys in this map
     */
    MutableLongSet keySet();
```

But ImmutablePrimitiveObjectHashMap.keySet() returns UnmodifiablePrimitiveSet.
```java
    @Override
    public MutableLongSet keySet()
    {
        return UnmodifiableLongSet.of(this.delegate.keySet());
    }
``` 

AbstractUnmodifiableLongCollection implements addAll() as follows:
```java
    @Override
    public boolean addAll(long... source)
    {
        throw new UnsupportedOperationException("Cannot call addAll() on " + this.getClass().getSimpleName());
    }
```

So I can't modify the result from PrimitiveObjectMap.keySet() though it says it returns a mutable set.
Is this your intention?

**Comment by motlin** [comment]
This is intentional, and consistent with built in JDK methods like java.util.Collections#unmodifiableList. Unmodifiable classes are decorators that prevent modification through the wrapper. They are not immutable, and the wrapped collection can still be mutated if you have a direct reference to it. So it's even possible to see an unmodifiable collection appear to mutate over time.

**Comment by minQZ** [comment]
@motlin 

I understand that's what you mean. But then why is PrimitiveObjectMap.keySet() returning UnmodifiablePrimitiveSet?

Comments on PrimitiveObjectMap.keySet() describe me as being able to mutate the return value of it, but it's not possible because it is unmodifiable and all mutating functions are disabled.

I think PrimitiveObjectMap.keySet() should return modifiable and mutable collection as comment says. Am I wrong?
