### ISSUE TITLE
Expose compact/trimToSize in HashBag implementations

### ISSUE THREAD

**Issue by victornoel** [eclipse/eclipse-collections#1393]
Hi,

`HashBag` implementations seems to rely on a `MutableObjectIntMap` internally, to optimize for memory it would be useful to be able to call compact on the bag so that the internal map is compacted.

My use case is that I have bugs that get filled with data over some time then at one point I convert them to unmodifiable and never modifiy them again but they get moved around and read by different parts of the application. Just before converting them to unmodifiable, it would be good to ensure they use as less space as possible because I have potentially thousands of such bags at every time.

**Comment by mohrezaei** [comment]
Shouldn't the conversion to unmodifiable do the compacting?

**Comment by victornoel** [comment]
@mohrezaei since unmodifiable returns a wrapper, the original object of still modifiable, so I'm not sure it's really relevant. Also I can see other cases where you just want to trim without creating an unmodifiable view on the collection.

Ideally toImmutableXXX could do something like this in the created immutable though! Well all the immutable connections constructor could do this actually, should I open another ticket for this?

**Comment by mohrezaei** [comment]
Sorry, I mixed up the two for a second there. Yes, immutable should compact automatically. The unmodifiable wrapper (not conversion), shouldn't.  I don't see a problem with adding the trim call to bag; just wanted to make sure it happened automatically when it should.

**Comment by victornoel** [comment]
Closing as this should be available in 12.0.0.M1
