### ISSUE TITLE
Update websites to link to new AsciiDoc version of Reference Guide

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1410]
The Eclipse Collections websites currently link to the old version of the Reference Guide.

https://www.eclipse.org/collections/#refGuide

All of the references across the different language translations of the website should link to the new AsciiDoc version of the Reference Guide which is here:

https://github.com/eclipse/eclipse-collections/blob/master/docs/0-RefGuide.adoc

**Comment by nikhilnanivadekar** [comment]
The website change needs to happen on the website project repo.

**Comment by aniket691** [comment]
Please assign this issue to me

**Comment by TheJavaGuy** [comment]
@donraab @nikhilnanivadekar I am willing to do this as soon as the https://github.com/eclipse/collections-website/pull/1 is merged :)

**Comment by nikhilnanivadekar** [comment]
@TheJavaGuy I responded on the website repo 
https://github.com/eclipse/collections-website/pull/1#issuecomment-1528110955

**Comment by TheJavaGuy** [comment]
@nikhilnanivadekar @donraab Just a gentle reminder that I implemented this in https://github.com/eclipse/collections-website/pull/2 and it's ready for review.

**Comment by nikhilnanivadekar** [comment]
Ack. Will check later today. Thanks!
