### ISSUE TITLE
Refactor map tests to be consistent with other tests

### ISSUE THREAD

**Issue by rzrobin213** [eclipse/eclipse-collections#1427]
As referenced in the PR below, the map test suite does not have a MapTestCase class like the other collection test suites. It would be better practice to extract the tests meant to target the Map implementation to another class. 

https://github.com/eclipse/eclipse-collections/pull/1425#discussion_r1065213307_

**Comment by ashutosh-roy** [comment]
Hi rzrobin213, i can take a stab at solving this issue.

**Comment by rzrobin213** [comment]
Go for it! Good luck!
