### ISSUE TITLE
[doc] an extra white space needs to be removed.

### ISSUE THREAD

**Issue by Akash3121** [eclipse/eclipse-collections#1443]
There is an extra white space, need to be removed in the documentation.
https://github.com/eclipse/eclipse-collections/blob/master/docs/2-Collection_Containers.adoc#primitive-maps
<img width="909" alt="image" src="https://user-images.githubusercontent.com/87650180/223153673-ad7a1f0a-f4e2-452d-9365-49385cc48b9f.png">

please assign this to me!
Thank you!

**Comment by Akash3121** [comment]
This issue solved in https://github.com/eclipse/eclipse-collections/pull/1444.
Thank you!

**Comment by donraab** [comment]
Hi @Anjali2312-Thombare , thank you for the interest in contributing! This issue has already been addressed so I am closing the issue.
