### ISSUE TITLE
Sign Releases

### ISSUE THREAD

**Issue by wahlbrink** [eclipse/eclipse-collections#152]
Please sign your release jar files.

See: https://wiki.eclipse.org/JAR_Signing

**Comment by itohro** [comment]
Thanks for pointing this out! 

We've been doing the GPG signing which is a prerequisite for the Maven Central upload, but it seems we missed this jarsign requirement..

As we cannot sign the jars that were already released, we would probably do new service release for each version 7.0.3, 7.1.1 and 8.0.1 with signed jars. 

Would that work?

**Comment by wahlbrink** [comment]
Yes.
But don't forget to fix also #49 , otherwise it is useless for Eclipse/Osgi projects.

**Comment by itohro** [comment]
Thanks. 

We've been seeking for someone who could help contributing to #49 . Would you happen to be interested in contributing to it, or know someone who might be interested? 

No worries if not, just asking.

**Comment by nikhilnanivadekar** [comment]
@itohro I have fixed #49 and #168. Can you please pick up this issue when you get a chance?

**Comment by itohro** [comment]
Thanks @nikhilnanivadekar, yes i'll look into this.

**Comment by itohro** [comment]
[Update]
I'm experimenting sign jar build using [a branch](https://github.com/eclipse/eclipse-collections/commit/2585c08dd1ca4a9830f4e85549d646dec1a6b11c), but [it failed with some permission issue](https://hudson.eclipse.org/collections/job/deploy/26/consoleFull).

I've raised a [bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=510109) for it.
