### ISSUE TITLE
Update the copyrights

### ISSUE THREAD

**Issue by Akash3121** [eclipse/eclipse-collections#1522]
https://github.com/eclipse/eclipse-collections/blob/master/docs/2-Collection_Containers.adoc?plain=1

Line 2 shows as 2022, needs to update to 2023.
![image](https://github.com/eclipse/eclipse-collections/assets/87650180/26328e81-2981-4ebf-beb6-e5c9930cd57f)

please assign this ticket to me @donraab !

**Comment by divyanshv21** [comment]
why is this issue still open?
