### ISSUE TITLE
eclipse-collections v12 JDK compatibility support

### ISSUE THREAD

**Issue by mszurap** [eclipse/eclipse-collections#1525]
We see that the version 12 is in works and in the maven repos the eclipse-collections-12.0.0.M3.jar is already available, however it is built with JDK 11 target compatibility - hence it is breaking with existing applications running with earlier JDK versions (JDK8).

java.lang.UnsupportedClassVersionError: org/eclipse/collections/impl/list/mutable/primitive/LongArrayList has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Is the version 12 not going to support JDK 8? Can that be documented?

**Comment by mszurap** [comment]
eclipse-collections-12.0.0.M1.jar and eclipse-collections-12.0.0.M2.jar seems to be JDK8 compatible, the problem is only with the M3.
Please note that this is causing issues in other applications having dependency on this library, for example mapdb:
https://mvnrepository.com/artifact/org.mapdb/mapdb/3.0.8

**Comment by prathasirisha** [comment]
Hi @mszurap, please use Eclipse Collections 11.1.0 for Java 8 applications and [Eclipse Collections 12.0.0](https://github.com/eclipse/eclipse-collections/issues/1132) (_not yet released_) for Java 11 applications. We will update the compatibility matrix and README with the same information upon 12.0.0 release.

**Comment by mszurap** [comment]
Thank you @prathasirisha for confirming.

**Comment by mohrezaei** [comment]
Documented in README. closing.
