### ISSUE TITLE
The immutablePrimitiveList.stg could benefit from a collect overload

### ISSUE THREAD

**Issue by kuporific** [eclipse/eclipse-collections#154]
The use case I am missing is being able to `collect` from an `ImmutableDoubleList` to the same type. Unfortunately, the API is currently limited to `collect`-ing to an `ImmutableList<V>`.

For example, what I would like to do is:

```
void method(ImmutableDoubleList data)
{
    // Do some manipulation to each double in the list, returning a double.
    ImmutableDoubleList modified = data.collect(d -> d * d / 2 + 4);
    // ...
}
```

But the type of `modified` is forced to:

```
ImmutableList<Double> modified = data.collect(d -> d * d / 2 + 4);
```

One workaround is to add a call to `.collectDouble(d -> d)`, like so:

```
ImmutableDoubleList modified = data.collect(d -> d * d / 2 + 4).collectDouble(d -> d);
```

However, I think this could be more eloquently handled with an overloaded method added to `immutablePrimitiveList.stg` as:

```
Immutable<name>List collect(<name>To<name>Function function);
```

This overload could also be applied to other primitive collection types as well.

**Comment by donraab** [comment]
You can accomplish this today with the following call to asLazy():

```
void method(ImmutableDoubleList data)
{
    // Do some manipulation to each double in the list, returning a double.
    LazyDoubleIterable modified = data.asLazy().collectDouble(d -> d * d / 2 + 4);
    ImmutableDoubleList result = modified.toList().toImmutable();
    // ...
}
``` 
There is a pull request to begin adding the collectPrimitive methods directly to the primitive containers that we need to revisit here: https://github.com/eclipse/eclipse-collections/pull/95

**Comment by donraab** [comment]
There are now methods directly available on each primitive iterable for collecting into a target primitive collection.  Methods are available for converting between all primitive types.  The availability of these methods should lessen the need to have overloaded methods which were originally planned to be added in a major release.  The above example can now also be written as follows:

```
void method(ImmutableDoubleList data)
{
    // Do some manipulation to each double in the list, returning a double.
    ImmutableDoubleList result = data.collectDouble(d -> d * d / 2 + 4, DoubleLists.mutable.empty()).toImmutable();
    // ...
}  
```
