### ISSUE TITLE
can not found the GMF 

### ISSUE THREAD

**Issue by zhang8330** [eclipse/eclipse-collections#1574]
No repository found athttps://download.eclipse.org/modeling/gmp/gmf-tooling/updates/releases-3.0.1/.
See 'Details' for more information.

What can I do 😭

**Comment by donraab** [comment]
Hi @zhang8330, this issue looks like it is not related to the Eclipse Collections project. Based on the URL you posted above, I would suggest creating an issue at the [Eclipse Modeling Framework](https://github.com/eclipse-emf) Project.
