### ISSUE TITLE
Fix performance problem in MutableList.subList() / implement similar optimization as ArrayList.subList()

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#1603]
When implementing head/tail list algorithms in Java, it's common to use subList() to get the tail. When calling subList() on a subList, we must get a chain of wrappers. However, we must also maintain constant times for lookups or the list algorithms become quadratic.

There's a kind of obvious optimization here, and java.util.ArrayList.SubList implements it but none of the SubLists in Eclipse Collections do. SubLists maintain a pointer to their parent sublist as well as the root list in the chain. Mutation operations go through the parent chain, but lookups go straight to the root.

**Comment by yoa1226** [comment]
@motlin hi motlin,  I can understand what you said. I can Mimick the Implementation of Java Standard Library. you can assign this issue to me.

**Comment by yoa1226** [comment]
@motlin  Okay, I will complete the task perfectly, and I'll communicate with you promptly as soon as I have any questions.

**Comment by yoa1226** [comment]
@motlin  hi, motlin . I have completed this task, and the pull request at [1620](https://github.com/eclipse/eclipse-collections/pull/1620).  Some unit tests was added to [MutableListTestCase](unit-tests-java8/src/test/java/org/eclipse/collections/test/list/mutable/MutableListTestCase.java) and all unit tests at package `org.eclipse.collections.test.list.mutable` have passed. You can check my code whenever it's convenient for you.

**Comment by yoa1226** [comment]
@motlin hi  motlin, please close this issue.
