### ISSUE TITLE
Optimize ImmutableArrayList.takeWhile() and dropWhile() for small lists.

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#1640]
ImmutableArrayList.takeWhile() and dropWhile() always return ImmutableArrayList. Since these methods don't delegate to a factory, they can't return ImmutableEmptyList for example.

**Comment by prithviraj2609** [comment]
Hello @motlin,

I have tried resolving this issue and created a PR for the same.
Would you review and merge my PR if this issue is still open
Here is my PR: https://github.com/eclipse/eclipse-collections/pull/1644
