### ISSUE TITLE
Set that return the existing value?

### ISSUE THREAD

**Issue by javafanboy** [eclipse/eclipse-collections#1671]
In order to create "internalization" for your own types etc. it would be great to have support for inserting an entry into a Set and as return value either get the new value (if it was inserted) or the existing value (if one already existed preventing the new value from being inserted). 

I have not seen support for this in the sets today and it would be nice if this was added in the future.

**Comment by motlin** [comment]
This exists, though it's a bit hidden. Check if the Set is an instance of Pool, and then use it using the Pool interface.

https://github.com/eclipse/eclipse-collections/blob/master/eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/Pool.java

**Comment by mohrezaei** [comment]
Additionally, `java.util.Set.put` already does what you're asking for.

**Comment by mohrezaei** [comment]
Sorry, I meant `UnifiedSet.put`

**Comment by javafanboy** [comment]
Thanks guys - good news - will try it out!

There is almost too much features in EC making it hard to sometimes figure out what is there :-)
