### ISSUE TITLE
Implement a Tally function

### ISSUE THREAD

**Issue by nathanmerrill** [eclipse/eclipse-collections#169]
It would be great if there was a Tally function (on RichIterable).

In essense, Tally() would turn your RichIterable<T> into a ObjectIntMap<T>, where the integer is the number of times each T appears in the iterable.

In addition, a TallyBy() that would allow you to tally by the results of a function.

**Comment by nikhilnanivadekar** [comment]
A [Bag](https://github.com/eclipse/eclipse-collections/blob/b40e3bbb0add5f1dfde257d06546be3c9c6ca4fd/docs/guide.md#-bag) will solve this use case. A Bag keeps track of the number of occurrences of each element.

`RichIterable` has a `toBag()` method available on it. 

If you need to create a Bag using results of a function you can do this:
`RichIterable.collect(Function, Bags.mutable.empty());`

Refer to [JavaDoc of collect with target](https://www.eclipse.org/collections/javadoc/8.0.0/org/eclipse/collections/api/RichIterable.html#collect-org.eclipse.collections.api.block.function.Function-R-).

**Comment by nathanmerrill** [comment]
Ah, thank you!  I was surprised that such a function didn't exist.
