### ISSUE TITLE
No way to collect into an ImmutableMultimap

### ISSUE THREAD

**Issue by nathanmerrill** [eclipse/eclipse-collections#171]
As it stands, I only see two ways to construct an ImmutableMultimap:

1. `Multimaps.immutable.of`, which allows you to insert at maximum 3 items.

2. `MutableMultimap.toImmutable()`, which means you have to iterate through a collection, add it to a temporary mutable, then call `toImmutable()` on it.

While option 2 works, I'd love it if there was someway to create a multimap from existing immutable collections.   Signatures would likely be similar to `.flatCollect()`.

EDIT:  I realized that option 1 also allows an iterative-based solution by calling `.newWith()`, but that's effectively the same as option 2.

**Comment by motlin** [comment]
Several methods do this. A good example is ImmutableList.groupBy which
returns ImmutableListMultimap.
