### ISSUE TITLE
eclipse-collections and related projects don't export all packages in their manifest.mf

### ISSUE THREAD

**Issue by almibe** [eclipse/eclipse-collections#172]
Currently eclipse-collections, eclipse-collections-api, etc only export their base package and not all of them like it should to work in an OSGi environment.

I believe this is a problem on all recent versions.

Edited out potential solution that wouldn't work.

**Comment by nikhilnanivadekar** [comment]
Referring to Issue #49 (fixed with PR #168) it doesn't look like eclipse-collections-api needs any changes. The required changes for eclipse-collections module have been merged.
If you think anything else needs an update, please let us know.

**Comment by almibe** [comment]
I just checked out master and built it and it looks like only eclipse-collections is exporting the correct packages.  The api jar is still only exporting it's base package
```
Export-Package: org.eclipse.collections.api;version="8.1.0.SNAPSHOT"
```
It just needs the same wildcard added to it's build file and it'll work
```
<Export-Package>org.eclipse.collections.api</Export-Package>
```
```
<Export-Package>org.eclipse.collections.api.*</Export-Package>
```

**Comment by nikhilnanivadekar** [comment]
@almibe Thanks for the analysis, would you like to raise a PR with this fix?
Our contribution guide can be found here: [How to Contribute](https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md)
If you cannot it is ok.
