### ISSUE TITLE
Make constructors on Unmodifiable and Synchronized collections public

### ISSUE THREAD

**Issue by jankotek** [eclipse/eclipse-collections#193]
I have my own implementations of `LongLongMap` and `LongObjectMap` collections. Constructors on `UnmodifiableLongLongMap` and `SynchronizedLongLongMap` are package protected. My implementations can not instantiate those wrappers.

Is it possible to make constructor on `Unmodifiable*` amd `Synchronized*` classes public?

**Comment by donraab** [comment]
I am fine with this in principle.  I looked at what is currently done in the Unmodifiable and Synchronized Object collections, and there is a pattern of having a public static `of` method which constructs an instance.  Sometimes a constructor is inconsistently public (e.g. SynchronizedBag, SynchronizedXyzMultimap).  I'm not convinced that the benefit of having a static `of` method is worth the extra cost in this case.  There are also instances already in the synchronized wrappers, where there is no public constructor for the scenario where a lock is supposed to be explicitly provided.  I've found tests for these methods, but I believe they should be public or they useless.  If you'd like to submit a pull request, we can get some feedback from others and hopefully merge it in time for the next release.

**Comment by jankotek** [comment]
ok, I will write a patch

**Comment by jankotek** [comment]
pull request is out, but it fails on IP stuff. I have old mail from Craig, will look howto sign the paperwork

**Comment by donraab** [comment]
Info on the Eclipse Contributor Agreement is linked in [here](https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md).

**Comment by jankotek** [comment]
Old PR did not had Signed-off tag. I created new one with checks for null arguments.
