### ISSUE TITLE
Implement LazyIterable.takeWhile(Predicate) and LazyIterable.dropWhile(Predicate).

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#20]
A `LazyIterable` may not have a meaningful order, if it was created from `MutableSet.asLazy()` for example, so it doesn't implement`OrderedIterable`. But it may have a meaningful order too.

`LazyIterable` already implements some equivalent methods from `OrderedIterable` that short circuit, like `take()` and `drop()`. It should also implement `takeWhile()` and `dropWhile()` with the following signatures.

```java
LazyIterable<T> takeWhile(Predicate<? super T> predicate);
LazyIterable<T> dropWhile(Predicate<? super T> predicate);
```

**Comment by nikhilnanivadekar** [comment]
I am working on this.

**Comment by motlin** [comment]
FYI I think that dropWhile can be implemented without delegating to an iterator. I can't think of how to do the same for takeWhile.
