### ISSUE TITLE
OrderedIterable::max/min/first to return Optional instead of throwing exception

### ISSUE THREAD

**Issue by Ziemien** [eclipse/eclipse-collections#213]
Would be possible for:
OrderedIterable::max, min, getFirst, getLast etc. to return Optional<T> instead of throwing runtime exception? That would provide more concise programming experience.

**Comment by motlin** [comment]
We wouldn't break the backwards compatibility of min(), max(), getFirst(), getLast(), but we'd add alternatives that return Optional. The idea is covered (partially) by #122.

**Comment by Ziemien** [comment]
perfect.

**Comment by nikhilnanivadekar** [comment]
This is covered by #122 and #123 . You can follow those issues.
Closing this as redundant.
