### ISSUE TITLE
Implement synchronized Multimaps.

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#22]
Implement synchronized Multimap wrappers like `SynchronizedMutableListMultimap`, `SynchronizedMutableSetMultimap`, etc.

Implement `MutableMultimap<K, V> asSynchronized();` in `MutableMultimap<K, V>` and covariant overrides like `MutableListMultimap<K, V> asSynchronized();` in `MutableListMultimap`.

All interfaces that extend `MutableMultimap` should have an override, including
- `MutableBagIterableMultimap`
- `MutableBagMultimap`
- `MutableListMultimap`
- `MutableSetIterableMultimap`
- `MutableSetMultimap`
- `MutableSortedBagMultimap`
- `MutableSortedSetMultimap`

The overall design and inheritance hierarchy of synchronized `MutableMultimaps` should be similar to the synchronized `MutableCollection` hierarchy.

**Comment by itohro** [comment]
@g-votte is working on this issue.
