### ISSUE TITLE
Implement unmodifiable BiMaps.

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#24]
The API `MutableBiMap<K, V>.asUnmodifiable()` already exists, but [the implementation](https://github.com/eclipse/eclipse-collections/blob/7.0.0/eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/mutable/AbstractMutableBiMap.java#L390) in `AbstractMutableBiMap` is unsupported.

**Comment by nikhilnanivadekar** [comment]
I am working on this.
