### ISSUE TITLE
Deprecate or hide collection factory constructors.

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#26]
Clarify that classes like collection factory classes are not meant to be instantiated more than once. The current API allows you to get an empty immutable list like this.

``` java
ImmutableList<Object> list1 = new ImmutableListFactoryImpl().empty();
```

The better way to get an empty immutable list is like this.

``` java
ImmutableList<Object> list2 = Lists.immutable.empty();
```

Both examples return the singleton instance of the empty immutable list. In other words, `list1` and `list2` are the same instance. The second example creates no garbage, making the first example seem especially wasteful. `Lists.immutable` is intended to hold the only instance of `ImmutableListFactoryImpl` in the JVM.

For all collection factory classes, change them to implement the singleton pattern, or clarify that they aren't meant to be instantiated by deprecating their constructors and adding Javadoc links to the classes like `Lists` that should be used instead.

If this is handled through deprecation, it can be done in a minor release. Changing the collection factories to implement the singleton pattern would be a [compatibility breaking change](https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md#semantic-versioning).

**Comment by bhav0904** [comment]
I am working on this.
