### ISSUE TITLE
Implement UnifiedMap.trimToSize or (UnifiedMap.compact).

### ISSUE THREAD

**Issue by cinquin** [eclipse/eclipse-collections#265]
Hi,
Is there a way of compacting a UnifiedMap? Some primitive maps and sets do have a `compact` method, but I can't find such a method (or equivalent) for UnifiedMap. Is the only way to free up memory used by the `table` field and the chained key arrays (e.g. after many elements have been inserted and then removed from the map) to create a new map from the remaining objects and discard the old one?

Would there be interest in having a `compact` method, or is it a design decision not to have one?

Incidentally, Trove also has useful autocompaction behavior, and a `retainEntries` method that helps perform automatic compaction at reasonable times.

**Comment by motlin** [comment]
Trove's hash tables use open addressing with sentinels to mark removal, so they can be compacted by rehashing every element and getting rid of the sentinels. The hash tables in Eclipse Collections use chaining, and get rid of the chains as elements are removed, so compaction is usually unnecessary. However, after doubling the size of the array, I'm not sure we ever go back and halve it. Is that what you're referring to?

**Comment by cinquin** [comment]
But the array that backs a chain is never resized downwards, and only becomes eligible for garbage collection once that chain becomes empty, right? (The reference to the array is nulled at the end of `UnifiedMap::overwriteWithLastElementFromChain` and in `PositionalIterator:: removeLastFromChain `).
So if lots of mappings are inserted into a map, and then lots — but not all — mappings are removed, the map may still have a large number of big chain-backing arrays that are mostly empty but still take the same amount of space, right?

Also, I cannot see a way of efficiently removing multiple mappings in one go. For example, `removeAll ` makes repeated calls to `remove`. If multiple mappings need to be removed from the same chain, it seems that would lead to a lot of redundant iteration of the backing array (and depending on the use case it may be much more efficient to just iterate all entries of the map and check if they should be removed, as with `retainEntries`, rather than looking up and removing each entry individually). There is also `PositionalIterator::remove`, but it probably ends up iterating over the backing arrays more times than strictly necessary, in `PositionalIterator::removeFromChain`.

Overall I guess the typical use case for which `UnifedMap` is designed is one in which there aren't substantial fluctuations in the number of mappings in the map over its lifetime?

**Comment by motlin** [comment]
Good points. You've convinced me that a compact/trim method makes sense as public api on UnifiedMap (and UnifiedSet). What do you think @gs-rezaem?

I'm not sure I understand the point about removeAll. Are there other map implementations with the behavior you're describing?

**Comment by cinquin** [comment]
> Good points. You've convinced me that a compact/trim method makes sense as public api on UnifiedMap (and UnifiedSet). What do you think @gs-rezaem?

Great. I think that'd be useful.


> I'm not sure I understand the point about removeAll. Are there other map implementations with the behavior you're describing?

My point is that neither `removeAll` nor any other UnifiedMap method allows for optimal performance of entry removal, when one has a predicate to apply to all map entries to decide which ones should be kept. As far as I can tell one of the purposes of the [`retainEntries` method in Trove's THashMap](https://github.com/cinquin/GNU_Trove/blob/70f5917f8a3bbb640c83278f383f62efe61806f4/core/src/main/java/gnu/trove/map/hash/THashMap.java#L378) is to perform efficient removal in that situation. If there are a lot of entries to be removed in one go, I think using a `retainEntries` method with the appropriate predicate should be more efficient than calling `remove` on each individual entry to be removed, or than using an entry set iterator (at least with the current implementation of the iterator in UnifiedMap).

In terms of the API, the missing method I'm looking for would be exactly the same as Trove's `retainEntries` — which, other than the Collection/Map difference, is the same as Java 8's `removeIf` default interface method that was added to Collection.

**Comment by gs-rezaem** [comment]
Agree that `compact` (or maybe to keep it similar to Fast/ArrayList `trimToSize`) is a good idea.

`removeAll` is more interesting. `removeAll(predicate)` is certainly worth considering. `removeAll(collection)` can only really be better optimized if the collection has a fast lookup, so essentially an O(1) `contains()`. Even then, that makes the implementation very "instance-checky", which is not productive, as there are so many implementations of collection out there.

BTW, if you have long chains in UnifiedMap, you should re-evaluate your hashcode -- the rule of thumb is that the population of chain lengths should exponentially decrease with chain size. One of the design decisions in UnifiedMap/Set is that we expect the user to have decent hashcodes.

**Comment by nikhilnanivadekar** [comment]
@cinquin can you please try this one out when we release 9.0.0.M3 and give us feedback?

**Comment by cinquin** [comment]
@nikhilnanivadekar  Thanks for having implemented this! Yes I'll have a look.

**Comment by nikhilnanivadekar** [comment]
@cinquin M3 was pushed to Maven Central. You can test it out in a couple of hours. Thanks!
