### ISSUE TITLE
Web page shows wrong date for 8.1 release

### ISSUE THREAD

**Issue by pburka** [eclipse/eclipse-collections#269]
The main web page (https://www.eclipse.org/collections/), in the latest news section, says:

- Eclipse Collections 8.1.0 released (Mar 16th 2016)

I believe that this should be "2017".

**Comment by nikhilnanivadekar** [comment]
Thanks for pointing this out, and apologies for the mistake. We will fix it.

**Comment by itohro** [comment]
Fixed this.
