### ISSUE TITLE
Remove usage of JCIP annotations and the dependency on net.jcip:jcip-annotations.

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#270]
We've been using these annotations for a long time without applying them consistently to all immutable and thread-safe classes. They don't catch a lot of problems in my experience so far. Another direction we could go is to consistently use these annotations everywhere. Open to debate.

**Comment by nikhilnanivadekar** [comment]
If they don't catch problems, I would prefer to remove them. This removes the only external dependency we have in our impl module: https://github.com/eclipse/eclipse-collections/blob/master/eclipse-collections/pom.xml#L47

**Comment by motlin** [comment]
Just to clarify [they can report bugs](https://stackoverflow.com/questions/8479599/what-concurrency-warnings-should-i-expect-from-findbugs) but in my experience if you go through all the effort to set up the annotations correctly, you already kind of know what you're doing, so I haven't seen them prevent problems.
