### ISSUE TITLE
Stream shortcut in immutable collections

### ISSUE THREAD

**Issue by Addvilz** [eclipse/eclipse-collections#274]
Currently the only way to create a stream of ImmutableSortedSet or ImmutableList, for example, is to do something like this

```java
final ImmutableSortedSet<Object> values = // ...
StreamSupport
    .stream(values.spliterator(), false)
    .// ...
```

Could we get an api extension for the immutable collections to support `.stream` as with other collections? Would it make sense?

**Comment by donraab** [comment]
Yes, this makes perfect sense and was actually being worked on.  But IIRC we needed to wait for the 9.0 release because the work could not be done in a backwards compatible manner.

@itohro Is this correct?

**Comment by nikhilnanivadekar** [comment]
@Addvilz while we add the api extension, you can achieve inter-op like this:

```
ImmutableList<String> immutableList = Lists.immutable.empty();
immutableList.castToList().stream()
.//...;
```
