### ISSUE TITLE
Two things about Bag.size() etc.

### ISSUE THREAD

**Issue by qblyy** [eclipse/eclipse-collections#291]
It implements: int org.eclipse.collections.api.RichIterable.size().
Returns the number of items in this iterable.

It should returns long. See this: long org.eclipse.collections.api.IntIterable.sum().
Because the sum of occurrences may overflow when the Bag has some items with large occurrences.

And the method name "size()" is ambiguous. It should have a better name likes this:
int org.eclipse.collections.api.bag.Bag.sizeDistinct()
The size of the Bag when counting only distinct elements.

The int size() should be refactor to long totalOccurrences() or long sizeTotalOccurrences() etc.

All primitive and other bags should be refactored too.

**Comment by motlin** [comment]
For mutable bags, it also implements `Collections.size()`.

**Comment by qblyy** [comment]
1. In ec, Bag, ImmutableBag and primitive bags are neither MutableBag nor Collection.

2. For the mutable bag, size() just returns the number of elements or Integer.MAX_VALUE. Such as Koloboke Collections has size() do the same thing and long sizeAsLong() returns the correct size.

int java.util.Collection.size()
Returns the number of elements in this collection. If this collection contains more than Integer.MAX_VALUE elements, returns Integer.MAX_VALUE.

**Comment by motlin** [comment]
Right, so what is the follow-up? Add sizeAsLong()?

**Comment by qblyy** [comment]
I think a interface is better:

public interface BigCollection

or

public interface BigCollection<T> extends Collection<T>
{
	@Deprecated
	default int size() {
		return (int) Math.min(Integer.MAX_VALUE, sizeAsLong());
	};

	long sizeAsLong();
}

I would like to see EC adds more big collections in the future.

**Comment by nikhilnanivadekar** [comment]
@qblyy do you have a real production use-case for this?
Or this is more of a theoretical exercise. We have not yet received any requests for a `BigCollection`.
Are you dealing with collections which cannot be satisfied with the existing collections we have?
