### ISSUE TITLE
Add covariant override for subList() in ListIterable hierarchy.

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#298]
Refer to thread: https://dev.eclipse.org/mhonarc/lists/collections-dev/msg00030.html

**Comment by nikhilnanivadekar** [comment]
Currently the users will have to add redundant casts to achieve subList() on ListIterable

```
    @Test
    public void subImmutableList()
    {
        ListIterable<String> immutableList = Lists.immutable.with("a", "b", "c", "d", "e");

        if (immutableList instanceof ImmutableList)
        {
            ListIterable<String> subImmutableList = ((ImmutableList) immutableList).subList(1, 3);
            Assert.assertEquals(Lists.immutable.with("b", "c"), subImmutableList);
            Verify.assertInstanceOf(ImmutableList.class, subImmutableList);
        }
    }

    @Test
    public void subMutableList()
    {
        ListIterable<String> mutableList = Lists.mutable.with("a", "b", "c", "d", "e");
        if (mutableList instanceof MutableList)
        {
            ListIterable<String> subMutableList = ((MutableList) mutableList).subList(1, 3);
            Assert.assertEquals(Lists.mutable.with("b", "c"), subMutableList);
            Verify.assertInstanceOf(MutableList.class, subMutableList);
        }
    }

```

**Comment by aewhite** [comment]
After some thinking, I did some up with a reasonable alternative that doesn't involve casting but I suspect it has some (trivial?) overhead.  

```
Interval.fromTo(startIndex, endIndex - 1).asLazy().collect(list::get)
```

But I feel like first class support for sublist would be nice.

**Comment by nikhilnanivadekar** [comment]
If you are using Interval, you can drop the asLazy() call, since the collect() will in essence be lazy. Interval is an interesting implementation where it is lazy at the same time not lazy. Regarding the overhead it really depends on your from and to indexes and type of list. YMMV, best to benchmark and check.

You will get the subsist API in 9.0.0 by end of September. I'll be doing a milestone release soon, if that will work for you.

Also, we accept contributions, so if you are interested I will accept a Pull Request :-)
