### ISSUE TITLE
Implement HashingStrategies.nullSafeFromFunction(Function)

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#301]
Currently, there is HashingStrategies.nullSafe(HashingStrategy) and HashingStrategies.fromFunction(). However there is nothing which is a mix of both. If we chain them:
HashingStrategies.nullSafe(HashingStrategies.fromFunction(Function)) if the Function.valueOf() results in a null, it will throw a NPE.

The implementation will be similar to this:
```
        @Override
        public int computeHashCode(T object)
        {
            return Objects.hashCode(this.function.valueOf(object));
        }

        @Override
        public boolean equals(T object1, T object2)
        {
            return Objects.equals(this.function.valueOf(object1),
                    this.function.valueOf(object2));
        }
```

**Comment by motlin** [comment]
https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#hashCode(java.lang.Object)

https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#equals(java.lang.Object,%20java.lang.Object)
