### ISSUE TITLE
Implement chunk on primitive iterables.

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#307]
There is chunk(int) on `RichIterable`, which returns `RichIterable<RichIterable<T>>`.  There should be chunk on primitive iterables defined as:

`<RichIterable<<type>Iterable>> chunk(int size)`

**Comment by nikhilnanivadekar** [comment]
The output should not be a RichIterable. It should be PrimitiveIterable. We should not box the elements during chunk.

**Comment by donraab** [comment]
I don't think the outer can't be a primitive iterable, unless I am missing something.

**Comment by nikhilnanivadekar** [comment]
you mean can or can't?
But I see your point. I missed the `<type>Iterable` there.

**Comment by nikhilnanivadekar** [comment]
@donraab @motlin question about unmodifiableCollections. Should the return RichIterable be unmodifiable? Should the inner batches be unmodifiable? On the object side we keep it Mutable. But I think the inner batches and the RichIterable should be unmodifiable.

**Comment by donraab** [comment]
Sounds reasonable.  How is it implemented on the object side?

**Comment by nikhilnanivadekar** [comment]
`org.eclipse.collections.impl.collection.mutable.AbstractUnmodifiableMutableCollection#chunk`
it simply calls `chunk()` on the underlying `MutableCollection`.

**Comment by donraab** [comment]
Is is copying the data, or presenting a view?

**Comment by nikhilnanivadekar** [comment]
Copies it

**Comment by donraab** [comment]
So if the data is copied, there's no reason to make it unmodifiable.

**Comment by nikhilnanivadekar** [comment]
Ok makes sense

**Comment by motlin** [comment]
:+1:
