### ISSUE TITLE
Implement collectWithIndex on Ordered primitive Iterables.

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#309]
Signatures should be as follows:

`default <V> OrderedIterable<V> collectWithIndex(<type>IntToObjectFunction<? super T, ? extends V> function)`
`default <V, R extends Collection<V>> R collectWithIndex(<type>IntToObjectFunction<? super T, ? extends V> function, R target)`

**Comment by nolequen** [comment]
It seems collectWithIndex is already implemented in orderedPrimitiveIterable.stg

**Comment by nikhilnanivadekar** [comment]
@nolequen thanks!

**Comment by nikhilnanivadekar** [comment]
Closed via #414
