### ISSUE TITLE
Implement classic set operations on primitive sets.

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#310]
Implement the following set operations on primitive sets, to be symmetric with the same forms on SetIterable:

```
<type>Set union(<type>Set);
<type>Set intersect(<type>Set);
<type>Set difference(<type>Set);
<type>Set symmetricDifference(<type>Set);
boolean isSubSetOf(<type>Set);
boolean isProperSubsetOf(<type>Set);
LazyIterable<<type><type>Pair> cartesianProduct(<type>Set);
```

**Comment by digsb** [comment]
@donraab Can I work on this issue?

**Comment by donraab** [comment]
@digsb No one else is working on it currently that I am aware so please feel free if you'd like to work on it.  Thank you!
