### ISSUE TITLE
Implement reduce and reduceInPlace on primitive iterables.

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#312]
Signatures should be:

```
Optional<type> reduce(<type><type>To<type>Function);
R reduceInPlace(Function0<R>, Object<type>Procedure);
```
This would require supplementing the current OptionalInt/Long/Double with equivalents for all primitives.  There is also no BinaryOperator currently for primitive types other than int/long/double so I suggest using the primitive function equivalent in EC.

**Comment by victornoel** [comment]
@donraab if I make a PR for this, will it go into v10?

And where should the method be declared (interface) and implemented (an abstract class? a default method?).

Thanks :)

**Comment by donraab** [comment]
@victornoel Yes, this can make it into v10.  If it is possible to do as a default method, then I would go with that. Since 10.0 is a major release, if it is easier to implement in the abstract types then this would be fine as well.

**Comment by victornoel** [comment]
@donraab @nikhilnanivadekar @motlin I think this can get closed (cf comment above)
