### ISSUE TITLE
Implement primitive BiMaps

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#313]
Today we have PrimitiveObjectMap, ObjectPrimitiveMap and PrimitivePrimitiveMap combinations.  It may be useful to have the same constructs for BiMaps.  Has anyone encountered this use case?  Comment or vote if you have.

**Comment by nikhilnanivadekar** [comment]
BiMap is a special case of having a self contained map and an inverse map. Adding them on the primitive side might be unnecessary. But happy to see if other users think it is useful.
