### ISSUE TITLE
Implement primitive key multimaps.

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#314]
Today we can only group by object keys, since we only have object multimaps.  It may be useful to create primitive keyed multimaps so we can group by primitive keys (e.g. age, count, id).  Has anyone seen this use case?  Comment or vote if you have.

If we have primitive key multimaps, we will want them in a separate module, to reduce the size of the binaries.  We can also create Collector implementations to provide primitive groupings like:

```
ListIntMultimap<Pet> petsByAge = list.stream().collect(Grouping.byInt(Pet::getAge));
ListLongMultimap<Pet> petsByAge = list.stream().collect(Grouping.byLong(MyObject::getSomeId));
```
Or some other better naming pattern for the utility class to hold the Collectors.

**Comment by nikhilnanivadekar** [comment]
I think the overhead of having primitive multimaps to the jar size is going to be enormous. That said, currently if the users need multimap like behavior they can use a combination of primitive maps and iterables.
