### ISSUE TITLE
Add "multiReader" factories to Lists, Sets and Bags

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#338]
The multiReader factory should allow you to write code similar to the mutable and immutable factories, only returning MultiReaderFastList, MultiReaderUnifiedSet or MultiReaderHashBag.

```
Lists.multiReader.empty();
Lists.multiReader.with(1, 2, 3);

Bags.multiReader.empty();
Bags.multiReader.with(1, 2, 3);

Sets.multiReader.empty();
Sets.multiReader.with(1, 2, 3);

```

**Comment by nikhilnanivadekar** [comment]
Fixed via #367 , #436 , #455
