### ISSUE TITLE
Implement Lists.mutable.withInitialCapacity(int initialCapacity)

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#342]

**Comment by motlin** [comment]
Could the method just be called empty()? Do we have the equivalent for sets
and maps already?

**Comment by nikhilnanivadekar** [comment]
Yes
org.eclipse.collections.impl.set.mutable.MutableSetFactoryImpl#withInitialCapacity

org.eclipse.collections.impl.map.mutable.MutableMapFactoryImpl#withInitialCapacity

**Comment by nikhilnanivadekar** [comment]
Fixed with #364
