### ISSUE TITLE
Yak Shaving: Upgrade maven-enforcer plugin to work with Java 9

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#359]
This needs to wait the release of plugin. Currently it is only in milestone mode.

**Comment by kedar-joshi** [comment]
I wanted to work on this issue but commit 609bcdcd already upgraded maven-enforcer plugin to 3.0.0-M1 and it seems to work well on JDK 11 so far.

**Comment by nikhilnanivadekar** [comment]
Yes Kedar, but feel free to upgrade once the version or above is released. Thanks!
