### ISSUE TITLE
Implement groupByUniqueKey Collector on Collectors2.

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#363]

**Comment by TheLoneKing** [comment]
The implementation that I have written does not seem to work well with parallel stream. Any insight into how parallel streams should be handled would be helpful.

**Comment by donraab** [comment]
What isn't working well?  Is a test you've written failing?

The parallel version of this would have to be able to handle the case where non-unique keys that were unique on different tasks were merged together in the final result.
