### ISSUE TITLE
Add check on FastList for initialCapacity < 0

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#365]

**Comment by loradd** [comment]
Hi! Should we return a 0-sized list when initialCapacity < 0?

    public FastList(int initialCapacity) 
    {
        this.items = initialCapacity <= 0 ? (T[]) ZERO_SIZED_ARRAY 
                                          : (T[]) new Object[initialCapacity];    
    }

**Comment by motlin** [comment]
I think we should throw IllegalArgumentException. Thoughts?

**Comment by nikhilnanivadekar** [comment]
I agree, also this will be consistent with the existing implementations.
Justification for this approach is that, I would expect the users of this constructor, to know the initialCapacity beforehand.

**Comment by loradd** [comment]
Yes, I agree. I can take this issue if it is fine for you.

**Comment by nikhilnanivadekar** [comment]
@loradd we already have a PR for the fix of this #427 .
We have many more issues we could use your help on, for example: #511 , #476 , #457 , #409 and many more!
Also, I would love to add translations of the website in more languages, if you are interested.
