### ISSUE TITLE
Add Assume.assumeTrue(System.getProperty("java.version").startsWith("1.8.")); for reflection tests.

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#366]

**Comment by nikhilnanivadekar** [comment]
If we run all unit tests using Java 9 and check for reflection warnings by passing the VM arg `--illegal-access=warn` we can find all the tests which need the assume condition.

**Comment by jiminhsieh** [comment]
After trying `mvn clean install -DargLine="--illegal-access=warn"`, I didn't see any warning related to reflection. Could anyone give me some hints? Thanks!

**Comment by leomrlima** [comment]
Is this still valid? I also didn't see any warning...

**Comment by m-flak** [comment]
**I get this warning using version 10.1.0 on OpenJDK13.** I did not see anything in the changelog that would indicate I would get different behavior using the latest version.
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.collections.impl.utility.ArrayListIterate (file:/C:/Users/Matthew/myblog/server/target/server-1.0-shaded.jar) to field java.util.ArrayList.elementData
WARNING: Please consider reporting this to the maintainers of org.eclipse.collections.impl.utility.ArrayListIterate
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by nikhilnanivadekar** [comment]
Closing this issue as it is invalid. JDK-9+ made reflective access as a warning. However, there are workarounds added in case there are reflective access cases the non-reflective code path will be used and will not have issues.
