### ISSUE TITLE
Implement MutableMapIterable.putPair(Pair<K, V> keyValue).

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#391]

**Comment by motlin** [comment]
This exists already and is called add() if I recall.

**Comment by nikhilnanivadekar** [comment]
I thought so too, but I only added it in Multimap in 6.0. I guess I missed adding it to MutableMap.

**Comment by nikhilnanivadekar** [comment]
There exists `add()` on MutableMapIterable. It was pointed out offline that `put()` as a method is more widely used, known and is easily discoverable.

**Comment by motlin** [comment]
If you think of a map as a collection of tuples, add makes sense. It’s also
consistent with Scala.

**Comment by nikhilnanivadekar** [comment]
ok I am fine with not deprecating and having add and putPair. add is to make us consistent with Scala, putPair for discoverability.
