### ISSUE TITLE
Implement MutablePrimitiveObjectMap.putPair(PrimitiveObjectPair<V>).

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#394]
Complete method signature:

`public <V> putPair(PrimitiveObjectPair<V> keyValuePair)`

**Comment by leomrlima** [comment]
Why add and not put? This is a Map...

**Comment by nikhilnanivadekar** [comment]
We have a method add() on Multimaps and we like to maintain consistency.

**Comment by leomrlima** [comment]
Maybe we need to change the add to put on Multimaps...

On Fri, Nov 3, 2017 at 2:43 PM, Nikhil Nanivadekar <notifications@github.com

**Comment by nikhilnanivadekar** [comment]
I will like to not break backwards compatibility. I am fine adding `add` as well as `put` and delegate.

**Comment by donraab** [comment]
There is an inconsistency between `add` and `putAllPairs`.

```
    default boolean add(Pair<K, V> keyValuePair)
    {
        return this.put(keyValuePair.getOne(), keyValuePair.getTwo());
    }
```
```
    // Bulk Operations
    default boolean putAllPairs(Pair<K, V>... pairs)
    {
        boolean changed = false;
        for (Pair<K, V> pair : pairs)
        {
            changed |= this.put(pair.getOne(), pair.getTwo());
        }
        return changed;
    }
```

**Comment by donraab** [comment]
There is a difference between `add` and `put` in the case of `Map`.  A method called `add` would return `boolean`, and a method called `put` would return the previous element or `null` if none exists there.

**Comment by nikhilnanivadekar** [comment]
Changed it to put() as it is more intuitive for a Map
