### ISSUE TITLE
Implement Bag.anySatisfyWithOccurrences(), Bag.allSatisfyWithOccurrences(), Bag.noneSatisfyWithOccurrences(), Bag.detectWithOccurrences()

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#406]
Similar to selectByOccurrences

**Comment by donraab** [comment]
The only concern I have with these methods is that we could also add anySatisfyWithOccurrences which would take an ObjectIntPredicate instead of an IntPredicate.  Thoughts?

**Comment by nikhilnanivadekar** [comment]
In that case I would rather have only `anySatisfyWithOccurrences()` as the users can simply ignore the object/key if they need to work with only occurrences. But then we will break symmetry with `selectByOccurrences()`

**Comment by donraab** [comment]
I'll leave it to you.  Add the ones you need.  I need collectWithOccurrences already.  I'm ok leaving selectByOccurrences.  It is a special case that we can also replicate if you really need just the occurrences for these predicate methods.  I think the By methods are useful for the predicate methods.

**Comment by goldbal330** [comment]
I would be interested to work on it.

**Comment by donraab** [comment]
Thanks @goldbal330 ! I've assigned it to you.

**Comment by nikhilnanivadekar** [comment]
@goldbal330 are you working on this?

**Comment by goldbal330** [comment]
Yes. Making a good progress.

________________________________
