### ISSUE TITLE
Implement MapIterable.collectKeysUnique().

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#409]
```java
<R> MapIterable<R, V> collectKeysUnique(Function2<? super K, ? super V, ? extends R> function);
```
or
```java
<R> MapIterable<R, V> collectKeysUnique(Function<? super K, ? extends R> function);
```

Similar to the existing api:
```java
<R> MapIterable<K, R> collectValues(Function2<? super K, ? super V, ? extends R> function);
```

`collectKeys` is trickier than `collectValues` because after transformation, the new keys can be equal to each other and collapse into a smaller map. I'm inclined to say that collectKeys should throw, similar to the behavior of groupByUniqueKey, when the function returns non-unique results. On the other hand, RichIterable.toMap() and MutableMap.collectKeysAndValues() already silently collapse duplicates and no one seems to complain.

**Comment by donraab** [comment]
Perhaps call it collectKeysUnique if it is going to throw?

**Comment by nikhilnanivadekar** [comment]
If someone needs to only collect on keys and not do anything to values and not throw for dups they can always use `collectKeysAndValue()` and bypass the valueFunction.
For handling duplicates on `collectKeys()` we can return a `BagMultimap` or we can just take a target Multimap and not have any covariant overrides.
If we want to throw on duplicates, we can call it collectUniqueKeys or collectKeysUnique

**Comment by motlin** [comment]
collectKeysAndValues() isn’t fluent. You call it on the target map, not the
source. It’s a strange method.

In my use-case, the original Map keys don’t implement equal/hashcode, and I
want to transform them by calling a getter which returns their unique
property, which is just a name. I don’t want to get back a bag because I do
expect the transformation to be unique.

Both collectKeysUnique and collectUniqueKeys sound good to me.

**Comment by nikhilnanivadekar** [comment]
how about we add both collectKeys() which will return a Multimap with a target and collectUniqueKeys which will return a Map?

**Comment by nikhilnanivadekar** [comment]
@motlin is this still valid issue?
