### ISSUE TITLE
Is multiplication by 2 required during initialization of UnifiedSet?

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#411]
In the default constructor of UnifiedSet, an array of length 16 is allocated. Is that necessary? During the constructor of UnifiedMap it is necessary to multiply by 2, due to alternate keys and values. But I do not think we need to do the same for UnifiedSet.
```
protected static final int DEFAULT_INITIAL_CAPACITY = 8;
public UnifiedSet()
{
    this.allocate(DEFAULT_INITIAL_CAPACITY << 1);
}
```

```
protected static final int DEFAULT_INITIAL_CAPACITY = 8;
public UnifiedMap()
{
    this.allocate(DEFAULT_INITIAL_CAPACITY << 1);
}
```
@motlin @gs-rezaem @donraab thoughts?

**Comment by gs-rezaem** [comment]
In a hash structure, capacity is what the users think of capacity: how many can we put in the set before it resizes. UnifiedSet has a default loadFactor of 0.75, which means it keeps the array at most 3/4 full.
So multiply by 2 is not quite right, it should be multiply by 4/3. But we also need to be a power of 2, so ``8*4/3`` rounded up to the next power of 2 which is 16, or ``8 << 1``.
