### ISSUE TITLE
Add a JUC Map view on IntObjectMap (and the likes): IntObjectMap.asMap()

### ISSUE THREAD

**Issue by leomrlima** [eclipse/eclipse-collections#416]
So, use case: I have a class that internally store things in an IntObjectMap. And it implements an interface that has (the same) information exposed in a Map<Integer, Object> getInformation() method.

Currently, I have to iterate over the IntObjectMap and create a new Map to satisfy this. 

BUT I think that's cumbersome and wasteful, and EC is "more with less", so I'd like a way to have a IntObjectMap exposed as Map<Integer, Object>.

When I discussed this idea with @donraab, he said that a view would be best and to "create an issue asking for asMap on our primitive maps"; so here it is.

Now, for consistency, there's already a toMap() method from RichIterable<V>, but that doesn't seem to do what I want here (or I couldn't make it happen).

**Comment by leomrlima** [comment]
My specific case in point is with ImmutableIntObjectMap. So a view would make even more sense.

**Comment by leomrlima** [comment]
Adding a JUC Map view kind of requires a JUC Set view to PrimitiveSet. So... ONWaRDS~!

**Comment by nezda** [comment]
Was this implemented? I haven't found it: would ease migration to Eclipse Collections.
