### ISSUE TITLE
entrySet() and values() removeIf() methods in both CHM are not thread-safe

### ISSUE THREAD

**Issue by isopov** [eclipse/eclipse-collections#424]
Basically issue is the same as https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8078645 (there are two samples there counting duplicate issue) that is still present in java8 and fixed in java9.
For eclipse-collections this issue is present in ConcurrentHashMap and ConcurrentHashMapUnsafe running on both java8 and java9.

Here is my sample revealing it - https://github.com/isopov/chm-jcstress
You can build it with
`./mvnw clean package`
And if have docker reproduce it easily on different java versions:
```docker run -v `pwd`/target:/mnt/target openjdk:8u151-jre java -jar /mnt/target/chm-jcstress.jar```
issues reproduced in both j.u.c.CHM and eclipse CHMs
``` docker run -v `pwd`/target:/mnt/target openjdk:9.0.1-11-jre java -jar /mnt/target/chm-jcstress.jar```
issues reproduced in eclipse CHMs only

**Comment by isopov** [comment]
Moreover there is separate from j.u.c.CHM bug in the same reproduction that can be linearized the following way:
- put one value with put
- successful replace it with other value
- try to remove second values with values().removeIf() or entrySet().removeIf() and fail (bug!)
- check if key is present and it is not (same or another bug)

**Comment by gs-rezaem** [comment]
I have a possible fix in https://github.com/gs-rezaem/eclipse-collections/tree/chmfix.
Do you mind running the stress tests?
Also, if there is a linear bug here, do you mind supplying a junit test?

**Comment by isopov** [comment]
>Do you mind running the stress tests?
I've built version from your fork and this issue is fixed, I think
>Also, if there is a linear bug here, do you mind supplying a junit test?
Sorry - I referred to https://en.wikipedia.org/wiki/Linearizability and other issues are still present. 

Shorter algo:
- thread 1 puts pair 1,1 into map
- thread 2 puts pair 1,0 into map replaces previous pair (receiving 1 as output from put)
- thread 2 tries to removeIf by values 0 but this method returns false as there is no such value

For reproduction you can use either my jcstress based tests, or here is modification of original testcase that illustrates the problem:

```
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.CyclicBarrier;

import org.eclipse.collections.impl.map.mutable.ConcurrentHashMap;

public class EclipseConcurrentHashMapTest {

	static final int K = 100;
	static final int SIZE = 10000;

	public static void main(String[] args) throws InterruptedException {
		for (int i = 0; i < K; i++) {
			System.out.println(i + " of " + K);
			test();
		}
	}

	private static void test() throws InterruptedException {
		ConcurrentHashMap<Integer, Integer> map = new ConcurrentHashMap<>();
		// put 0's
		for (int i = 0; i < SIZE; i++) {
			map.put(i, 0);
		}

		CyclicBarrier barrier = new CyclicBarrier(2); // to start working
														// simultaneously
		CountDownLatch latch = new CountDownLatch(2); // to wait until both
														// threads finished

		// this thread put 1's into map
		new Thread(new Changer(map, barrier, latch)).start();

		// this thread remove all 0's from map
		new Thread(new Remover(map, barrier, latch)).start();

		latch.await();
	}

	static class Changer implements Runnable {

		private final ConcurrentHashMap<Integer, Integer> map;
		private final CyclicBarrier barrier;
		private final CountDownLatch latch;

		public Changer(ConcurrentHashMap<Integer, Integer> map, CyclicBarrier barrier, CountDownLatch latch) {
			this.map = map;
			this.barrier = barrier;
			this.latch = latch;
		}

		@Override
		public void run() {
			try {
				barrier.await();
			} catch (Exception e) {
			}

			for (int i = 0; i < SIZE; i++) {
				map.put(i, 1);
			}

			latch.countDown();
		}
	}

	static class Remover implements Runnable {

		private final ConcurrentHashMap<Integer, Integer> map;
		private final CyclicBarrier barrier;
		private final CountDownLatch latch;

		public Remover(ConcurrentHashMap<Integer, Integer> map, CyclicBarrier barrier, CountDownLatch latch) {
			this.map = map;
			this.barrier = barrier;
			this.latch = latch;
		}

		@Override
		public void run() {
			try {
				barrier.await();
			} catch (Exception e) {
			}

			for (int i = 0; i < SIZE; i++) {
				boolean put = null != map.put(i, 0);
				boolean removed = map.entrySet().removeIf(e -> e.getValue() == 0);
				if (put && !removed) {
					System.out.println("Value put, but could not be removed right after it");
				}
			}

			latch.countDown();
		}
	}
}
```

**Comment by gs-rezaem** [comment]
@ isopov Sorry, I'm not sure I understand the behavior you expect from the test above.
The two loops (put(i,1) and put(i,0);removeIf) are running simultaneously. There is no implied guarantee that thread 2 should see a map that only has 0 values between the call to put(i,0) and removeIf. So the following sequence of events can easily lead to the System.out:

Thread 2: put(0,0) (put is true)
Thread 1: put(0,1)
Thread 2: removeIf: false, as there is no 0 value.

**Comment by gs-rezaem** [comment]
@isopov Sorry, my example above is wrong (put would be false in Thread 2). Let me have a closer look.

**Comment by gs-rezaem** [comment]
@isopov I think I know the issue here. There is a bug in the test code. The map is initialized with zeros, so the following is possible:

Thread 2: put(0,0) (put is true because it's prepopulated)
Thread 1: put(0,1)
Thread 2: removeIf: false, as there is no 0 value.

If you add map.clear() before the CyclicBarrier and I can no longer see any System.outs.
