### ISSUE TITLE
Implement asLazy() on Multimap.

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#44]
Currently, iteration patterns on `Multimap` are eager. `Multimap` interface should have `asLazy()` method which will delegate to a `LazyMultimap` similar to how `asLazy()` on `RichIterable` delegates to `LazyIterable`.

**Comment by motlin** [comment]
Before we solve this for Multimaps, I think we should design how we want to handle lazy evaluation over key-value pairs in MapIterables.
