### ISSUE TITLE
Implement MutableMapIterable#newEmpty(initialCapacity)

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#444]

**Comment by nikhilnanivadekar** [comment]
Minor version with default UnsupportedOperationException.

**Comment by nikhilnanivadekar** [comment]
There is org.eclipse.collections.impl.map.mutable.AbstractMutableMap#newEmpty which has the below signature:
`public abstract <K, V> MutableMap<K, V> newEmpty(int capacity);`

It is generic and public, so we cannot pull it up from abstract class to the interface. At the same time, we cannot have a method with same name on MutableMapIterable. This causes issues as the abstract method/implementations cannot override `the newEmpty(int capacity)` from the interface.

I propose we name the new method on interface to be `newWithInitialCapacity(int initialCapacity)`.

@motlin @donraab @itohiro73 thoughts?

**Comment by motlin** [comment]
It's probably used for collect, right? Do the generics make it more useful, or annoying?

It's also an option to go through a deprecation cycle and get rid of the method rather than avoid the name.

**Comment by nikhilnanivadekar** [comment]
It is useful, I have observed code which looks like this: `UnifiedMap.newEmpty(capacity)`  so, deprecating and eventually removing it will break users. Even in the library we have used it:
```
@Override
public <K, V> MutableMap<K, V> withInitialCapacity(int capacity)
{
    return UnifiedMap.newMap(capacity);
}
```
We can replace similar uses by `new UnifiedMap<>(size);` or `Maps.mutable.withInitialCapacity(size)`
But since it is useful and will lead to breaking change which might impact a lot of users, we should not deprecate/remove it, instead add a new method on the interface, which will be used for optimizations.
Or we skip this issue altogether and move down the methods to implementation classes which need `withInitialCapacity()` for optimization.

**Comment by motlin** [comment]
Just want to make sure it's clear that UnifiedMap.newMap() is a different method that happens to have the same name. It's static, so it does not implement or override the method in question.

**Comment by motlin** [comment]
And yes AbstractMutableMap#newEmpty is a public method, but it's not on the interface. In order to access it, you'd have to be storing your UnifiedMap (for example) as a UnifiedMap or AbstractMutableMap, not a MutableMap or Map. Deprecating/deleting/replacing still seems reasonable to me.

Also, "do nothing" is a reasonable option. We don't really need to add a method if we can do the same thing through factories.

**Comment by nikhilnanivadekar** [comment]
This method is currently required only for collect (as you pointed out). We can deprecate it in 9.2 and make it protected in 10.0 or in 11.0. So this will at least not break users who have extended our Map implementations. Also, it will allow us to hint users to use `newMap(capacity)` instead in Javadoc.

That still leaves us with the problem of having the same method name. If we are not too tied up with the newEmpty name, we can add `newWithInitialCapacity(size)` so that it shows right below `newEmpty()` in the IDE during auto-complete prompt.

Also, totally fine to "do nothing". I created this issue for the optimization which would be required for methods like `toMutable()` which is being discussed in #457 , but if these methods are added in the implementation itself, then I think we can close this issue.

From the above points, "do nothing" seems to be best option.
