### ISSUE TITLE
Optimize implementations of groupByUniqueKey() by pre-sizing the target maps.

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#445]
Since groupByUniqueKey makes the assertion that each result of invoking the function is unique from every other invocation, we can assume the size of the result will be the same size as the input and pre-size the map.

I spot checked a few implementations and none were pre-sized.

```java
    public static <K, T> MutableMap<K, T> groupByUniqueKey(
            List<T> list,
            Function<? super T, ? extends K> function)
    {
        return RandomAccessListIterate.groupByUniqueKey(list, function, UnifiedMap.newMap());
    }
```

**Comment by loradd** [comment]
Hi, I would like to work on this issue.
Is anybody working on it? Thanks!

**Comment by nikhilnanivadekar** [comment]
@loradd go for it! Thanks in advance for your contribution!
