### ISSUE TITLE
Optimize implementations of sumByPrimitive methods for Bags to only iterate once per item, not per occurrence.

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#448]
sumBy* methods for Bags should use forEachWithOccurrences.

**Comment by motlin** [comment]
should use forEachWithOccurrences instead of forEach

**Comment by AFederici** [comment]
Planning to fix this issue

**Comment by prathasirisha** [comment]
Hi @donraab, I want to work on this.

**Comment by donraab** [comment]
@AFederici are you working on this currently?

**Comment by donraab** [comment]
Hi @AFederici, I haven't heard back and since @prathasirisha has volunteered I have assigned the issue to her.
