### ISSUE TITLE
Optimize implementations of aggregateByPrimitive methods for Bags to only iterate once per item, not per occurrence.

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#449]
aggregateBy* methods for Bags should use forEachWithOccurrences.

**Comment by motlin** [comment]
should use forEachWithOccurrences instead of forEach

**Comment by AFederici** [comment]
Planning to fix this issue

**Comment by prathasirisha** [comment]
Hi, would like to work on this issue.

**Comment by donraab** [comment]
Thanks @prathasirisha ! I've assigned the issue to you.
