### ISSUE TITLE
Implement keySet() on Multimap.

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#45]
`Multimap` has `keyBag()` however, it is an O(n) operation which loops through the elements and creates a new Bag. Since a `Multimap` is defined as a `Map` of key and value `Collection`, there should be a method `keySet()` similar to what is present on a `Map`.

The `keySet()` implementation will go on [AbstractMutableMultimap](https://github.com/eclipse/eclipse-collections/blob/8d45bc751e796c1e0f8cc21a26d4f96b060392c2/eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/AbstractMutableMultimap.java) and [AbstractImmutableMultimap](https://github.com/eclipse/eclipse-collections/blob/8d45bc751e796c1e0f8cc21a26d4f96b060392c2/eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/AbstractImmutableMultimap.java).

On `AbstractMutableMultimap`, the implementation will be:

```
public Set<K> keySet()
{
  return this.map.keySet();
}
```

On `AbstractImmutableMultimap`, the implementation will be:

```
public Set<K> keySet()
{
  return this.map.castToMap().keySet();
}
```

Note: 
1) This cannot be added on `AbstractMultimap` as the `getMap()` method on it returns a `MapIterable` and does not have a `keySet()` method as yet.
2) Current workaround is `keysView()` which is a lazy view of the unique keys.

**Comment by motlin** [comment]
An implementation like this would violate invariants.

```java
public Set<K> keySet()
{
  return this.map.keySet();
}
```

You could just call `multimap.keySet().clear()` and the `Multimap` would have a non-zero size but be empty.

I agree that set-like views are important to add, but I don't think we should use the `Set` interface. We only use `Set` as the return type for `MutableMap.keySet()` because the type is inherited from `Map`.

**Comment by nikhilnanivadekar** [comment]
Can we return an UnmodifiableSet?

**Comment by motlin** [comment]
Yes, and returning it as a `SetIterable` makes sense in that context. An easy implementation on the immutable side would be to do the same thing, but it would be good to change the return type to `ImmutableSet` when we are ready to support a more full featured immutable view.
