### ISSUE TITLE
Make Primitive Hash Sets non-final

### ISSUE THREAD

**Issue by bergmanngabor** [eclipse/eclipse-collections#453]
Currently primitiveHashSet.stg generates final classes. Note that on the contrary, UnifiedSet as well as primitive maps are non-final classes. 

I recommend to remove the `final` modifier so that the resulting classes can be just as customizable / extensible as the other collections implementation classes.

**Comment by gs-rezaem** [comment]
👍

**Comment by nikhilnanivadekar** [comment]
We can do this, but it will have to wait till major release.

**Comment by bergmanngabor** [comment]
> have to wait till major release

Why is that? I believe no client code can be broken by marking a previously final class as non-final?

**Comment by itohiro73** [comment]
As @bergmanngabor mentioned, this change won't affect client code and can be released in minor-version. 

https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html#jls-13.4.2

I also double confirmed this doesn't break serialization.

**Comment by nikhilnanivadekar** [comment]
thank you @itohiro73

**Comment by bergmanngabor** [comment]
Thanks a lot!

**Comment by bergmanngabor** [comment]
Can I ask whether you are joining the Eclipse Photon release train by Milestone 6? In other words, will builds with the above fix (pre-releases of 9.3.0 if I understand correctly) be available in the [SimRel staging repo](http://download.eclipse.org/staging/photon) sometime soon, so that other Photon participants (Viatra in my case) can start depending on it? 

Sorry to bother you personally with this question, but I tried and failed to piece this info together using [your Roadmap wiki](https://github.com/eclipse/eclipse-collections/wiki/Roadmap) (that does not mention release 9.3) and the [Project database](https://projects.eclipse.org/projects/technology.collections/releases/9.3.0) (that lists no milestones currently).

**Comment by nikhilnanivadekar** [comment]
I will be creating a milestone release next week, and will update the sim-rel contribution. If you need it immediately, I am happy to create a milestone today, but wont have time to upgrade the contribution version.

**Comment by bergmanngabor** [comment]
There is no rush :) Next week is totally fine!
Thanks!

**Comment by nikhilnanivadekar** [comment]
@bergmanngabor 
I have published 9.2.0.M1 to p2 repo. Maven central deploy is having an issue, raised a bug here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=530997

For now can you please verify if the published p2 artifacts work fine for you? I can then upgrade the sim-rel contribution.

**Comment by nikhilnanivadekar** [comment]
path: download.eclipse.org/collections/9.2.0.M2/p2-repository-9.2.0.M2.zip

**Comment by bergmanngabor** [comment]
@nikhilnanivadekar thank you very much!
The update site seems to work, and now I can subclass LongHashSet etc.

Remark (CC @ujhelyiz ): on the P2 update site, the P2 feature "org.eclipse.collections" has an incorrect version tag "9.1.0.v20180210-2306", even though its contained plugins are correctly versioned as 9.2. You probably need to bump the major.minor version in your feature.xml.

**Comment by nikhilnanivadekar** [comment]
@bergmanngabor you mean here?
https://github.com/eclipse/eclipse-collections/blob/master/p2-feature/org.eclipse.collections.feature/feature.xml

Will keep that in mind for the next release's prep work. In the meantime if you want to raise a PR for the necessary version updates for p2, I will be happy to merge it.

**Comment by ujhelyiz** [comment]
It would be better to increase the version number for the whole p2-feature module (https://github.com/eclipse/eclipse-collections/tree/master/p2-feature) using a maven command, something like `mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=9.2.0-SNAPSHOT`

Note that you don't need to create a specific release version here (without the -SNAPSHOT bit); in Eclipse/OSGi the release builds use the same versioning scheme as normal builds.

**Comment by nikhilnanivadekar** [comment]
Does this go as a post step to snapshot build? Or it goes as a separate build?

**Comment by ujhelyiz** [comment]
Neither, this should be a once per release step.

I usually do this manually when I prepare for the next release; e.g. after we had released version 1.7.0 from the master branch, I run a command like that on my computer to increase the version number to either 1.7.1-SNAPSHOT or 1.8.0-SNAPSHOT, then commit the changes to the repository.

**Comment by nikhilnanivadekar** [comment]
ok understood. I will keep that in mind. Thanks!
