### ISSUE TITLE
Implement a Map factory method that takes a Map parameter.

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#457]
Something like this:
```java
Maps.mutable.withMap(map)
```
I'm not sure if `map` should be `java.util.Map` or `MapIterable` though. I suppose we could add MapIterable.toMutable() so that the factory would work best with `java.util.Map`. Thoughts?

**Comment by nikhilnanivadekar** [comment]
I think it should be a `java.util.Map`

For `MapIterable.toMutable()` in case of MutableMapIterable will we return a copy or same instance? From our convention toMutable will have to be a copy. It can return `this` for ImmutableMapIterable.

In the factory, we will iterate over key, value and populate the pre-sized new map.

**Comment by motlin** [comment]
I mostly agree, except it cannot return `this` for ImmutableMapIterable, it has to make a copy in all cases.

We should delegate to forEachKeyValue if available, and entrySet otherwise.

**Comment by nikhilnanivadekar** [comment]
Ok I understand why `this` will not be possible because then it will return an Immutable 😄 
👍
