### ISSUE TITLE
Make primitive classes non-final. 

### ISSUE THREAD

**Issue by itohiro73** [eclipse/eclipse-collections#459]
This is similar to #453. I find number of primitive impl stg templates are defined to generate final classes.

![image](https://user-images.githubusercontent.com/2220637/35791703-c4e7abcc-0a8c-11e8-8287-60dc2cda70db.png)

I'm not sure if there was a particular reason for that. If no valid reason, I'd suggest to remove `final` as similar to issue #453. 

Thoughts @donraab @nikhilnanivadekar @motlin @gs-rezaem ?

**Comment by motlin** [comment]
I put `final` in a number of places. For immutable collections it helps ensure that sublcasses are still immutable. For the other classes, it doesn't buy us much, or anything. Even synchronized and unmodifiable wrappers only make guarantees about mutations that go through the wrappers, so I think they could be non-final without sacrificing anything.

**Comment by itohiro73** [comment]
Thanks @motlin . That's what I thought. 

Let me remove `final` from the classes besides immutable collections.
