### ISSUE TITLE
Remove deprecated Serializable*SummaryStatistics.

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#473]
`SerializableDoubleSummaryStatistics`, `SerializableIntSummaryStatistics`, `SerializableLongSummaryStatistics`, `SummaryStatistics`
Were deprecated in 8.2.0 and marked to be removed.

**Comment by prathasirisha** [comment]
Closing this issue as this was taken care of by https://github.com/eclipse/eclipse-collections/pull/599.
