### ISSUE TITLE
index method is final in both UnifiedMap and UnifiedSet

### ISSUE THREAD

**Issue by gjajoo** [eclipse/eclipse-collections#475]
While the classes UnifiedMap and UnifiedSet aren't final, their index method is final. This issue is that sometimes index is the perfect method to Override in those classes as opposed to all the other methods that call index. Would it be possible to remove final on the index method? If not what are the design considerations for keeping it final, given that put/get can be overridden and can alter the behaviour of these classes as drastically as say index.

**Comment by gs-rezaem** [comment]
Can you describe your use case for overriding index?

**Comment by gjajoo** [comment]
Basically when there's a large number of updates to a Map/Set, the default implementation of index method isn't very cache friendly. With our dataset, we can arrange the updates in a manner, that if we can override the index method, we can reduce the cache misses drastically. Also our index override is less computationally intensive so it's improves the overall throughput. This is when measured with a very particular dataset.

**Comment by gs-rezaem** [comment]
Interesting. Index is well factored and can be marked non-final. It was probably marked final to encourage inlining, which when overriden is less likely to happen due to megamorphism.

**Comment by gs-rezaem** [comment]
To enshrine the non-final contract, the test suite would have to be executed with two versions of the classes (with an without override).

**Comment by gs-rezaem** [comment]
Alternatively, we could explore a better default index, maybe based on the ideas in the much newer primitive classes.

**Comment by gs-rezaem** [comment]
I meant the test suite in eclipse collections. Right now, index is well factored, but ensure future changes to the class don't break (unknown) subclasses, we should run all the tests with an without an override.

> Admittedly that doesn't seem to be the case here. This is for a very peculiar dataset and we don't foresee this applying to datasets at large.

I didn't mean we should transplant **your** index function and expect it to work. Optimistically, there may exist a lower-computational index method that works for the general case and your (let's call it) "unusual" case.

**Comment by gs-rezaem** [comment]
@gjajoo Do you mind trying one of these [32 bit spread functions](https://github.com/eclipse/eclipse-collections/blob/df5b50c7154b09634ad16b78ffeb1c165218600e/eclipse-collections/src/main/java/org/eclipse/collections/impl/SpreadFunctions.java#L19)?

**Comment by gjajoo** [comment]
@gs-rezaem Sorry I couldn't get back sooner on this as I am travelling. 

> With our dataset, we can arrange the updates in a manner, that if we can override the index method, we can reduce the cache misses drastically.

This is the most important thing in our usecase  i.e. it's possible to order data in a way that's causes fewer cache misses, regardless of the length of the table. It's possible for us to do this because the dataset's hashcodes are distributed enough that we can simply do a single >> shift operation to arrive at the desired index (with a table size power of 2). Just the spread function doesn't let us achieve this. What matters is how the index is calculated so that we can predict the order of buckets from "outside" the map. 

From a hashmap/set library author's perspective this is too specific (bizarre?) a case to cater to. There are well known tradeoffs between avoiding collisions and having a cheap hash function. But it's quite unusual to care about the order of the buckets (we're not talking separate linked list either). Which is why having this ability to override index method gives us the ability to use an already great general implementation for our specific case without worrying about affecting this library's generality.

**Comment by gs-rezaem** [comment]
@gjajoo fair enough. Would you like to contribute this change?

**Comment by gjajoo** [comment]
Yes I can contribute the change. I'll read up on the procedure for doing so and will revert if I run into any issues.

**Comment by nikhilnanivadekar** [comment]
@gjajoo contribution guidelines are available here: https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md

**Comment by nikhilnanivadekar** [comment]
Fixed via https://github.com/eclipse/eclipse-collections/commit/a2d12731ef3e161341086f87af0b709ed3a14102
