### ISSUE TITLE
Eclipse issues with MANIFEST.MF

### ISSUE THREAD

**Issue by elius1** [eclipse/eclipse-collections#49]
Eclipse is able to pick up the eclipse-collections-api jar as a plug-in. However, the eclipse-collections jar is not recognized as such.

Also, for both jars, the exported packages list only contains the top level package. This causes Eclipse to recognize the classes in all subpackages as non-api, resulting in warnings when used.

Could this be an issue with the way that the MANIFEST.MF files in the jars are build?

**Comment by motlin** [comment]
The MANIFEST.MF is created by the maven-bundle-plugin. Here are the relevant portions of the pom files.

https://github.com/eclipse/eclipse-collections/blob/master/eclipse-collections-api/pom.xml#L76
https://github.com/eclipse/eclipse-collections/blob/master/eclipse-collections/pom.xml#L82

Is the fix as simple as replacing the import...
```xml
<Export-Package>org.eclipse.collections.impl</Export-Package>
```
...with a star import?
```xml
<Export-Package>org.eclipse.collections.impl.*</Export-Package>
```

**Comment by stfnsche** [comment]
In https://github.com/eclipse/eclipse-collections/blob/master/eclipse-collections-api/pom.xml you need not specify any Export-Package (default behaviour is to export all packages except those containing internal or impl).
In https://github.com/eclipse/eclipse-collections/blob/master/eclipse-collections/pom.xml you need to specify everything you want exported (as the packages contain impl in their name). To export everything you can write as you said
`<Export-Package>org.eclipse.collections.impl.*</Export-Package>`
