### ISSUE TITLE
Nice to have an API which will make conversion from `RichIterable<BoxedPrimitive>` to `PrimitiveIterable` easier.

### ISSUE THREAD

**Issue by fabfas** [eclipse/eclipse-collections#496]
I was converting `MutableMap<String, Double>` to `ObjectDoubleMap<String>`.  I can use something below;

MutableMap<String, Double> stringDoubleMutableMap = Maps.mutable.with("1", 1.0, "2", 2.0);
MutableObjectDoubleMap<String> targetMap = ObjectDoubleMaps.mutable.empty();
stringDoubleMutableMap.forEachKeyValue((key, value) -> targetMap.put(key, value));

But It would be nice to have an API which will make conversion from `RichIterable<BoxedPrimitive>` to `PrimitiveIterable` easier.

**Comment by nikhilnanivadekar** [comment]
@fabfas this is a good proposal. Would you like to contribute this feature?
Contribution guidelines are available here: https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md

**Comment by nikhilnanivadekar** [comment]
Listing down few patterns which we could have:

```
PrimitiveLists.mutable.ofAll(Iterable<BoxedPrimitive>)
PrimitiveLists.mutable.withAll(Iterable<BoxedPrimitive>)

PrimitiveSets.mutable.ofAll(Iterable<BoxedPrimitive>)
PrimitiveSets.mutable.withAll(Iterable<BoxedPrimitive>)

PrimitiveBags.mutable.ofAll(Iterable<BoxedPrimitive>)
PrimitiveBags.mutable.withAll(Iterable<BoxedPrimitive>)

PrimitiveStacks.mutable.ofAll(Iterable<BoxedPrimitive>)
PrimitiveStacks.mutable.withAll(Iterable<BoxedPrimitive>)

Primitive1Primitive2Maps.mutable.ofAll(Map<BoxedPrimitive1, BoxedPrimitive2>)
Primitive1Primitive2Maps.mutable.withAll(Map<BoxedPrimitive1, BoxedPrimitive2>)

PrimitiveObjectMaps.mutable.ofAll(Map<BoxedPrimitive1, V>)
PrimitiveObjectMaps.mutable.withAll(Map<BoxedPrimitive1, V>)

ObjectPrimitiveMaps.mutable.ofAll(Map<K, BoxedPrimitive>)
ObjectPrimitiveMaps.mutable.withAll(Map<K, BoxedPrimitive>)
```
Same pattern for immutable side.

**Comment by nikhilnanivadekar** [comment]
Please let me know if any of these patterns seem superfluous or feel free to add more if missing.
