### ISSUE TITLE
Add method Bag.selectDuplicates().

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#499]
I searched my codebase for all usages of Bag.selectByOccurrences(). There are only a few usages, but all of them are of the form `bag.selectByOccurrences(occurrences -> occurrences > 1)`. I would suggest adding a convenience method `Bag.selectDuplicates()` which just delegates to `this.selectByOccurrences(occurrences -> occurrences > 1)`. Thoughts?

**Comment by nikhilnanivadekar** [comment]
This is one of the methods which I use quite often. Upvoted!

**Comment by nikhilnanivadekar** [comment]
I would consider adding a `Bag.selectUniques()` as well as a corollary to this method.
