### ISSUE TITLE
addToValue on maps return the argument value unchanged

### ISSUE THREAD

**Issue by rbjorklin** [eclipse/eclipse-collections#519]
`addToValue` on maps return the argument `toBeAdded` unchanged which doesn't seem very useful. Wouldn't it make more sense to return either the old or the new value?

Excerpt from `ObjectDoubleHashMap`:

    public double addToValue(K key, double toBeAdded)
        {
            int index = this.probe(key);
            if (isNonSentinel(this.keys[index]) && nullSafeEquals(this.toNonSentinel(this.keys[index]), key))
            {
                this.values[index] += toBeAdded;
                return this.values[index];
            }
            this.addKeyValueAtIndex(key, toBeAdded, index);
            return toBeAdded;
        }

**Comment by nikhilnanivadekar** [comment]
@rbjorklin the `toBeAdded` value is returned only when the Map does not contain the corresponding key.
the `if` block is for when there is a key, value in the Map. the value gets updated and we return the added value.
However, if the key is not present in the map, we add the key and value (`toBeAdded`) in this case and return `toBeAdded`.

**Comment by nikhilnanivadekar** [comment]
Feel free to reopen if you have more questions. Thanks for trying out Eclipse Collections!

**Comment by rbjorklin** [comment]
I need to get my eyes checked... I somehow missed the `return` statement inside the `if` block... Sorry!
