### ISSUE TITLE
zip is deprecated ?

### ISSUE THREAD

**Issue by roger-gl** [eclipse/eclipse-collections#524]
The following code causes a deprecated warning for the zip call in IntelliJ. Is that a problem of IntelliJ or is that code wrong?

```
  ListAdapter.adapt(row)
      .collect(ExcelValue::fromString)
      .zip(columnNames)
      .select(p -> p.getOne().isValid())
      .forEach(p -> applyMapping(unit, p.getOne(), p.getTwo()));
```

**Comment by motlin** [comment]
MutableList.zip() is not deprecated, so IDEs shouldn't show a deprecation warning on this code.

However, RichIterable.zip() is deprecated as a warning that you might be running an operation which cares about ordering on an unordered collection.
