### ISSUE TITLE
Implement stream() on Int/Long/DoubleList

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#526]
This will allow developers to use the three primitive streams with the equivalent primitive Lists.  This can be useful for both mutable and immutable primitive array lists.  Parallel primitive streams can be used with their internal primitive arrays.

**Comment by david-gang** [comment]
As these lists are backed by a primitive array we can just use:
streams from Arrays
https://docs.oracle.com/javase/8/docs/api/java/util/Arrays.html

I see now that we just need to update the string template to achieve this.
Is this correct ?

**Comment by david-gang** [comment]
Hi, I analyzed the issue and thought that for Ints we should have in IntIterable two functions
```
Spliterator.OfInt primitiveSpliterator();

default IntStream primitveStream()
    {
             return StreamSupport.intStream(primitiveSpliterator(), false);
    }
```
The primitiveSpliterator should be implemented in the implementation level. 
The same idea could be applied for all  primitive types types 
This is what i think but as i am just using eclipse collections and never developed in it i would like to hear your view before starting to invest in this time.

**Comment by donraab** [comment]
@david-gang Hi, thank you for expressing interest in this issue.  When I created the issue, I was thinking that starting with primitive Lists supporting streams would be the easiest to implement and provide the most value.  If we have stream and parallelStream on primitive Lists, we can provide an opportunity for parallelism that we do not have today.  We only have parallel APIs available for our object containers.  Since our primitive lists are backed by primitive arrays, it should be trivial to implement both serial and parallel streams.

**Comment by david-gang** [comment]
I started to work on this with pr https://github.com/eclipse/eclipse-collections/pull/672
I would appreciate if someone could just look at this and give comments.
