### ISSUE TITLE
CollectPrimitiveProcedure.stg to populate CollectPrimitiveProcedure.java

### ISSUE THREAD

**Issue by henohenotsuyoshi** [eclipse/eclipse-collections#529]
Hi All, 
Currently all CollectPrimitiveProcedure has actual java files respectively in code base.
CollectBooleanProcedure
CollectByteProcedure
CollectCharProcedure
CollectDoubleProcedure
CollectFloatProcedure
CollectIntProcedure
CollectLongProcedure
CollectShortProcedure

I think better to replace those with CollectPrimitiveProcedure.stg file. What do you think ?

Thanks,
Tsuyoshi.

**Comment by nikhilnanivadekar** [comment]
Sure! Go for it! 
As long as the package names do not change we should be fine from a compatibility perspective.

**Comment by henohenotsuyoshi** [comment]
Thanks, I will work on this.
