### ISSUE TITLE
[Questions] about Im / mutableCollections 

### ISSUE THREAD

**Issue by zluo01** [eclipse/eclipse-collections#543]
Hi, I am new to e.c. I read through the reference guide but still have couple questions that I am not able to find answers online.

1.  I cannot find any clone method or shadow clone options like JDK provides. I wonder how e.c. handled clone issues ?

2. In JDK collections, List have native shuffle functions. In e.c. , I am not able to find any of this. And also in primitive collections.

3. In java 8, I am able to create a new list with stream containing data.  Can e.c. also do the same thing or I have to do .of() and parsed them into a mutable or immutable list in e.c. ??

Thank you

**Comment by donraab** [comment]
Thank you for the questions.  Let me try and answer them.  In the future, it would be great if you could ask questions like these on StackOverflow with a tag of `eclipse-collections`.  Then more people can benefit from the answers, and you may even get an answer faster.

1. There are clone methods on `MutableList`, `MutableSet`, `MutableBag`, etc.  You can also create a copy of the contents of any `RichIterable` by using `toList`(), `toSet`(), `toBag`() depending on the target type you would like.

2. MutableList has two forms of `shuffleThis`().  One takes no parameters and the other takes an instance of `Random`.   The name shuffleThis matches the naming pattern we used for `sort` (sortThis).  The "this" in the method name indicates that after the function is performed, the List you are shuffling will be returned from the method.

3. There are converter methods on all `RichIterable` types for converting to mutable collections.  For instance, `toList`(), `toSet`(), `toBag`(), etc.  The "to" in the method signifies that operation takes linear time as it will create a copy of all the contents.

**Comment by nikhilnanivadekar** [comment]
To add for 3, if you have a stream, you can check the utility class `Collectors2`, There are Eclipse Collections specific Collectors.
Thanks for trying out Eclipse Collections!
I am closing this issue, please reopen if you have more questions. 
Thanks!
