### ISSUE TITLE
Should getFirst() and getLast() be undeprecated and explicitly mention no guarantees of repeatable results in the Javadocs for hashed data structures?

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#544]
getFirst() and getLast() were deprecated mainly because unordered data structures do not give any guarantees of the behavior. That said, I think we should undeprecate this API and explicitly mention that we pick the first or the last element. Due to unordered nature of these data structures, repeatability of the returned elements cannot be guaranteed.

**Comment by donraab** [comment]
I think so.

**Comment by donraab** [comment]
If we leave the API deprecated, then we could add `getAny()` as a replacement.  Then at least developers have an option to use that doesn't leave a call to a deprecated method in their code.

**Comment by nikhilnanivadekar** [comment]
I like `getAny()`

**Comment by mohrezaei** [comment]
No iterator would mean no garbage, and it's quite a bit shorter and more readable.
For unordered collections, it's no better than random.

**Comment by motlin** [comment]
I like getAny()

**Comment by nikhilnanivadekar** [comment]
Issue raised #548
