### ISSUE TITLE
Implement ObjectPrimitiveMap.from(Iterable, KeyFunction, ValueFunction), PrimitiveObjectMap.from(Iterable, KeyFunction, ValueFunction), PrimitivePrimitiveMap.from(Iterable, KeyFunction, ValueFunction).

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#547]
This can be a utility on Iterate to make it easy to create Primitive Maps or even on the Factory classes.
Currently, there is no easy way to create a PrimitiveMap from an Iterable/RichIterable.

**Comment by motlin** [comment]
If we ever want to split primitive maps into their own jar, we’d probably
need these methods to live somewhere other than on RichIterable.

**Comment by nikhilnanivadekar** [comment]
We should do it the other way around then. These methods can be on the primitive factories. Right now we do not have an easy way to create the primitive maps.
