### ISSUE TITLE
Implement RichIterable.getAny().

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#548]
In the Javadoc where `getFirst()` and `getLast()` are deprecated, there should be suggestion to use `getAny()`

**Comment by alimcmaster1** [comment]
Hi, 
I would be interested in getting more detail on what this change would entail, is its a good first issue?

It seems like from the issue referenced, the decision is to add a getAny() to the RichIterable interface.

Im assuming I then go implement this method in all appropriate places, the implementation can get the same as getFirst() or getLast()/ pick any random element..

Any appropriate test cases I should consider adding?

Thanks,

Alistair

**Comment by nikhilnanivadekar** [comment]
Hi @alimcmaster1 thanks for your interest in contributing. This is a good first issue and I have updated the label to suggest the same.
You are correct in the implementation specifics. For ordered collections (List, Stack), you can simply delegate it to getFirst() or getLast() (either is fine as long as you are consistent). For hashed data structures, you can take a look at how getFirst() is implemented, and have a similar implementation. 

You can either add the tests in the unit-test module or in the java-8-test module. Have tests with duplicate and unique elements. 

We can discuss and enhance the implementation (if needed) when you raise a PR, if you are stuck in the midst of making this change, please use this issue for questions. Thanks!

**Comment by motlin** [comment]
The fastest way to add getAny is as a default method on RichIterable that
delegates to getFirst but isn’t deprecated.

**Comment by alimcmaster1** [comment]
Thanks both for the pointers, appreciate the help. @motlin that's what I was thinking initially, but I thought that eventually if we want to get rid of getFirst() and getLast()? Ive begun the task of implementing a getAny() method to all classes that implement the RichIterable Interace. 
Example for FastList.java below. So its a step towards removing getFirst() and getLast() from the interface. What do you think? Is this appropriate for this change?
    
    @Override
    public T getAny()
    {
        return this.isEmpty() ? null : this.items[0];
    }

    @Override
    public T getFirst()
    {
        return this.isEmpty() ? null : this.items[0];
    }

    @Override
    public T getLast()
    {
        return this.isEmpty() ? null : this.items[this.size() - 1];
    }

**Comment by motlin** [comment]
I deprecated getFirst and getLast on RichIterable to indicate that not
every RichIterable has an ordering, so it's not always appropriate to call
getFirst and getLast. But every OrderedIterable obviously has an ordering,
so the same methods live there, with no deprecation. FastList transitively
implements OrderedIterable, and it will always have getFirst and getLast. A
delegating default implementation is definitely fine in OrderedIterable.
And even though the methods are deprecated (in some places) we may never
remove them in any places. So it might be fine in RichIterable too.
