### ISSUE TITLE
Better handle hash collisions

### ISSUE THREAD

**Issue by marschall** [eclipse/eclipse-collections#56]
With large hash collisions hashed eclipse-collections seem to perform a lot worse than the stock Oracle JDK hashed collections. Initial superficial analysis seems to suggest that with large hash collisions eclipse-collections also scale a lot worse than the stock Oracle JDK collections.
Generally large hash collisions are a symptom of bad `#hashCode` implementations is user code. However sometimes an attacker can craft input that results in large hash collisions. An example is when an attacker is able to supply strings that end up as keys in hashed collections and he can chose the input such that all keys have the same hash code. This is generally the case for any key-value based input, examples include XML element or attribute names, XML namespace prefixes, names of JSON object properties, HTTP header names and query parameters of any kind. If an attacker is able to create large enough hash collisions he may be able to degrade application performance enough to create a DoS attack.

`String#hashCode()` is quite susceptible to hash collisions. There are 2048 strings of length 2 that have the same hash code (see below). Strings have the property that if `a.hashCode() == b.hashCode()` then `(a + b).hashCode() == (b + a).hashCode()`. This means out of these 2048 strings one can generate 4194304 strings of length 4 with the same hash code.

To mitigate this changes where introduced to `java.util.HashMap` (the implementation of `String#hashCode()` is specified in the Javadoc and Oracle does not want to change it). As a stop gap measure `java.util.HashMap` used MurmurHash 3 with a random seed to hash strings by calling `sun.misc.Hashing.stringHash32` instead of calling `String#hashCode()` with an `instanceof` check in `HashMap.hash(Object)`. This changce seems to have been rolled back in recent Java 8 versions. The second change was to overflow to a red-black tree instead of a (linked) list when there are too many hash collisions for a slot. This would probably be the most appropriate change for eclipse-collections as well.

This is all based on [Schadcode - Schadenfreude for Hash Functions](https://github.com/emboss/schadcode).

Sample code for producing collisions an be found in [marschall/hashcollisions](https://github.com/marschall/hash-collisions/tree/master/src/main/java/com/github/marschall/hashcollisions).

The following are results for JMH benchmarks with 2048 elements all having the same hash code.
As you can see often eclipse-collections is more than a factor 10 slower than the stock Oracle JDK collections.
However if it's a scalability difference then more elements would produce a larger difference.

Jcf = Java Colllections Framework (stock Oracle JDK collections) JDK 1.8u74

    Benchmark                                          Mode  Cnt       Score     Error   Units
    AddCollisionBenchmark.addAllEclipse               thrpt  100     121.100 ±   0.471   ops/s
    AddCollisionBenchmark.addAllJcf                   thrpt  100    2793.015 ±  14.038   ops/s
    AddCollisionBenchmark.addEclipse                  thrpt  100      74.085 ±   0.320   ops/s
    AddCollisionBenchmark.addJcf                      thrpt  100    2889.612 ±  24.448   ops/s
    ContainsCollisionBenchmark.containsFirstEclipse   thrpt  100  162662.160 ± 620.752  ops/ms
    ContainsCollisionBenchmark.containsFirstJcf       thrpt  100   13453.828 ±  97.863  ops/ms
    ContainsCollisionBenchmark.containsLastEclipse    thrpt  100     134.515 ±   0.611  ops/ms
    ContainsCollisionBenchmark.containsLastJcf        thrpt  100    5684.152 ±  21.751  ops/ms

**Comment by motlin** [comment]
`UnifiedSet`, `UnifiedMap`, and their `*WithHashingStrategy` variants are not resistant to deliberately constructed hash collisions. Neither was `HashMap` until recently. Should we update these classes to be resistant to attack? I'm not aware of any other implementations that made this change. People generally choose to use `UnifiedSet` and `UnifiedMap` because of their speed, low memory usage, and API. If you need a hash table that's resistant to DoS attacks you can always use a `HashMap` wrapped in a `MapAdapter`.

If we do change the hash tables this way, it would be important not to hurt the performance of existing methods, as measured by the JMH tests in [jmh-tests/src/main/java/org/eclipse/collections/impl/jmh/map](https://github.com/eclipse/eclipse-collections/tree/master/jmh-tests/src/main/java/org/eclipse/collections/impl/jmh/map).

**Comment by motlin** [comment]
Closing this ticket for now. Happy to reopen if we discuss next steps to proceed.
