### ISSUE TITLE
Implement MutableMultimap.getIfAbsentPutAll().

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#566]

**Comment by motlin** [comment]
What would the parameters be? `K` and `V`, or `K` and `Iterable<V>`? If the answer is `K` and `V` then my gut reaction is we should not add this api.

**Comment by motlin** [comment]
MutableMapIterable.getIfAbsentPut(K, V) is analogous to Set.add(T). It's a constant time operation that finds a bucket, mutates it, and returns a value.

MutableMultimap.getIfAbsentPut(K, V), especially if done on a ListMultimap, is more analogous to List.containsIfAbsentAdd(T), which we don't have for good reason. It would hide an O(n) operation behind a method that sounds like it's O(1).

**Comment by nikhilnanivadekar** [comment]
<K, Iterable<V>,>
if it is <K, V>, I would also not be comfortable having that API.
The get() for multimap returns an Iterable, so the getIfAbsentPut() should also be for an Iterable. But I am totally fine not having this API.

**Comment by njcohen2** [comment]
Working on this at UIUC HackNight.

**Comment by tylermcdonald** [comment]
I'll help you work on it @njcohen2 .

**Comment by ethan-lord** [comment]
I'll also help work on this @njcohen2 @tylermcdonald

**Comment by nikhilnanivadekar** [comment]
@etsrepo This issue is to implement that method. #622 is a bug you have reported. Please do not cross-reference unrelated issues. Thanks for understanding!

**Comment by etsrepo** [comment]
@nikhilnanivadekar I know this issue is for implementation, still referenced because they will check existing issues in similar implementation. it may help them check upfront
