### ISSUE TITLE
Bug in addToValue for primitive Maps

### ISSUE THREAD

**Issue by dcullender** [eclipse/eclipse-collections#588]
Thanks for all the hard work gone into making and maintaining Eclipse Collections.

With the ObjectPrimitiveHashMaps, there is a piece of generated code : 

```java
    public int addToValue(K key, int toBeAdded)
    {
        int index = this.probe(key);
        if (isNonSentinel(this.keys[index]) && nullSafeEquals(this.toNonSentinel(this.keys[index]), key))
        {
            this.values[index] += toBeAdded;
            return this.values[index];
        }
        this.addKeyValueAtIndex(key, toBeAdded, index);
        return this.values[index];
    }
```

the expectation is that the value returned is the value after the addition. The problem is that for non-sentinel keys, the following code is run

```java
        this.addKeyValueAtIndex(key, toBeAdded, index);
        return this.values[index];
```

`addKeyValueAtIndex` may rehash and grow the map, meaning that the index calculated before is invalid, hence `return this.values[index];`  may return the incorrect value

**Comment by mohrezaei** [comment]
The fix is in the [9.2.0](https://github.com/eclipse/eclipse-collections/releases/tag/9.2.0) release.

**Comment by nikhilnanivadekar** [comment]
This was fixed in 9.2.0: https://github.com/eclipse/eclipse-collections/releases/tag/9.2.0
Also this bug was back ported to service releases.

**Comment by dcullender** [comment]
Thanks for the update, but there is still a bug in 9.2

```java
    @Override
    public int addToValue(K key, int toBeAdded)
    {
        int index = this.probe(key);
        if (isNonSentinel(this.keys[index]) && nullSafeEquals(this.toNonSentinel(this.keys[index]), key))
        {
            this.values[index] += toBeAdded;
            return this.values[index];
        }
        this.addKeyValueAtIndex(key, toBeAdded, index);
        return toBeAdded;
    }
```

This should return the value after the addition has occured, not the value to be added. If the key was a sentinal, the behaviour is correct

`this.values[index];`

but the other case is not consistent

`return toBeAdded;`

**Comment by nikhilnanivadekar** [comment]
Can you please give us a failing test case? We will be happy to fix it. Thanks!

**Comment by dcullender** [comment]
ahh, sorry. Misread the code there. All looks good to me - thanks!
