### ISSUE TITLE
Implement UnifiedSetWithHashingStrategy#addOrReplace(Object)

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#633]
I have encountered few usages where UnifiedSetWithHashingStrategy could have benefited to have replace(Object), this is useful when one of non-key the parameters needs to be overridden.
Thoughts?
Implementation will be an optimized version of this:
```
this.remove(Object);
this.add(Object);
```

**Comment by motlin** [comment]
Why not use a Unified*Map*WithHashingStrategy?

**Comment by nikhilnanivadekar** [comment]
The value will always be an empty object? If this use case makes sense then, I would rather add replace() to UnifiedSetWithHashingStrategy.

**Comment by mohrezaei** [comment]
I think this is a good method to add. Since it adds if it wasn't there, should it be called `addOrReplace`?

**Comment by nikhilnanivadekar** [comment]
I agree with `addOrReplace()` updated the issue.

**Comment by motlin** [comment]
If you use a map, the key is NOT replaceable by calling put(). The value is
replaceable. The key would be whatever is the first item you used to call
put().

So in theory I agree that this method makes sense. But I’d just use
UnifiedMapWithHashingStrategy.put(value, value) instead.

**Comment by nikhilnanivadekar** [comment]
I have raised a PR with the implementation
