### ISSUE TITLE
Add injectInto without initial value, aka RichIterable.reduce for primitive collections

### ISSUE THREAD

**Issue by victornoel** [eclipse/eclipse-collections#638]
The current signature of `injectInto` seems to be similar to `reduce` available in JCL, but one difference is that `injectInto` obligatorily needs an initial value while `reduce` is available also without an initial value.

For non-primitive collections, this is not a problem since there is also a `reduce` method available in `RichIterable`. For primitive collections, there doesn't seem to exist such a functionality.

This is useful for example when applying an arbitrary operator on a `DoubleIterable` that could be either sum or multiply (multiply needs 1 as an initial value while sum needs 0).

For now I am forced to write something like that (where `operator` is a parameter of the class containing this code):
```java
someDoubles.<Double>injectInto(null, (x, y) -> x == null ? y : operator.applyAsDouble(x, y))));
```

I would like to be able to write:
```java
someDoubles.injectInto(operator::applyAsDouble);
```

or:
```java
someDoubles.reduce(operator::applyAsDouble);
```

An open question is: should this version of `injectInto` take an extra argument for when the iterable is empty or should it returns an `Optional` as with JCL? I suppose that the eclipse-collection team has an answer for that :)

Thanks!

**Comment by motlin** [comment]
Well you can use reduce() on RichIterables. Is this request for primitive
collections?

**Comment by victornoel** [comment]
@motlin indeed, I didn't realize but my request only apply to primitive collections then, yes!

In another words, it seems I'm looking for a reduce as with `RichIterable` but for primitive collections.

I don't think this exists yet. I will update the description and title, thank you.

**Comment by victornoel** [comment]
Ok, I see there is already an issue for that: #312
