### ISSUE TITLE
Add an overload for toMap with a target Map as a parameter to RichIterable

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#656]
Currently there is a method `toMap` which returns a `MutableMap`.  The method `toMap` is similar to the `collect` method.  The method collect currently has an overloaded form which takes a target `Collection`.  I recently encountered a use case where it would have been helpful to have a form of `toMap` which takes a target `Map` as a parameter.  The specific use case was collecting from a `List` into a `LinkedHashMap`.  This particular use case could have also been solved if there was a method called `toOrderedMap`, but I think the `toMap` overload would be more generally useful as any `Map` type could be returned.

**Comment by motlin** [comment]
java.util.Map or our MutableMapIterable?

**Comment by donraab** [comment]
I think we should be consistent with collect and other methods with targets.

**Comment by motlin** [comment]
R extends MutableMapIterable<NK, NV>

**Comment by donraab** [comment]
Then we cannot return JDK maps or any other maps, like we can with collect.

**Comment by motlin** [comment]
groupBy, aggregateBy, etc all take MutableMapIterable. I don't remember the
decision at the time but I think we had a choice between interoperating
well with JDK types or sorted maps and we chose sorted maps.

**Comment by donraab** [comment]
Am I missing something?  I don't see target maps in any of those methods on RichIterable.

**Comment by c-guntur** [comment]
R extends MutableMapIterable<NK, NV> is more consistent when adding a target R, given toMap(...) without a target, returns a MutableMap.

**Comment by nikhilnanivadekar** [comment]
Agreed about consistency @c-guntur however for interop Map makes more sense. The below lines of code all compile fine. So, IMO it should be a java.util.Map

```
        Map<Integer, Integer> mutableMapIterable;
        mutableMapIterable = Maps.mutable.empty();
        mutableMapIterable = new HashMap<>();
        mutableMapIterable = new TreeSortedMap<>();
        mutableMapIterable = new TreeMap<>();
```

**Comment by motlin** [comment]
This is the only one I found that's similar, in that it could take Map or
MutableMapIterable.

<V, R extends MutableMapIterable<V, T>> R groupByUniqueKey(

        Function<? super T, ? extends V> function,
        R target);

**Comment by donraab** [comment]
The upside of `MutableMapIterable` is that you are guaranteed to get something back something you asked for with the fluent EC Map API.  The upside of `Map` is that you get back exactly what you ask for without restricting to EC only types.

**Comment by motlin** [comment]
Even though we don't have methods like aggregateBy that take a target, I
was looking at classes like NonMutatingAggregationProcedure, which only
work with MutableMapIterables and delegate to
MutableMapIterable#updateValueWith.

One other design question about toMap()... if the keyFunction returns
multiple equal keys, I think it should throw. There are probably places
where we don't do this.

Longer term, I think this method shouldn't exist. I think it's time we
added proper lazy iterables containing key/value pairs. I'll call this
LazyPairIterable for lack of a better name.

iterable
    .asLazy() // still a LazyIterable
    .groupByUniqueKey(function) // today it's a MapIterable<K, V>, in the
future it would be a LazyPairIterable<K, V>
    .collectValues(valueFunction) // transforms LazyPairIterable<K, V> to
LazyPairIterable<K, VV>
    .toMap();

Not as terse as an overload of toMap(), but (1) I'm not a fan of overloads
anyway and (2) we plan to add many variants of collect() on Maps and
Multimaps.

https://github.com/eclipse/eclipse-collections/issues/409
https://github.com/eclipse/eclipse-collections/issues/467
https://github.com/eclipse/eclipse-collections/issues/546

**Comment by donraab** [comment]
Not sure I agree on the the throwing for duplicate keys.  This doesn't happen on `toMap` today.  It happens only on `groupByUniqueKey`.  Interestingly, `groupByUniqueKey` has a target of `MutableMap` today.  Can you recall why we went with this decision?  This is more restrictive than `Map` and `MutableMapIterable`.  I would propose we lessen the restriction and go with `Map` here in the future so we can be more consistent.

```
<V, R extends MutableMap<V, T>> R groupByUniqueKey(
            Function<? super T, ? extends V> function,
            R target);
```

**Comment by motlin** [comment]
I’m guessing it’s based on age. toMap() and MutableMap are the oldest.
groupByUniqueKey came next. Last came ordered maps and the abstraction
MutableMapIterable.

I consider the behavior of toMap() and collectKeysValues() to be a bug that
we can never fix. So I don’t use those methods. Instead of toMap(), I call
groupByUniqueKey() followed by collectValues(). Despite the verbosity, I
think it’s more clear. And I want the safety of the uniqueness assertion.

I don’t want to add new methods that ignore duplicates. But it would be
reasonable to give it a different name than the method which does ignore
duplicates.

I think it’s reasonable to start loosening the type restriction to Map.
Looking around, it’s not super simple and can only be done in a major
release.

**Comment by cguntur-bnym** [comment]
I am submitting a PR for this.

**Comment by motlin** [comment]
I think we should deprecate all methods that silently collapse duplicate
keys, so toMap() and collectKeysValues(). We could mark them as deprecated
but not-for-deletion. Thoughts? I’d submit the PR but I want to check if
it’s controversial first.

**Comment by donraab** [comment]
I don't think we should deprecate. If throwing exceptions on duplicates is a desired behavior and common use case, we can add toMapUnique() similar to groupByUniqueKey with both key and value functions.

**Comment by nikhilnanivadekar** [comment]
I do not quite understand the rationale behind deprecation. Since the duplicates will be overridden, I understand that the behavior will not be deterministic in all cases. However, that is the behavior that is expected. This same behavior is observed in JDK Collectors and other places. This is the exact same behavior which users will get if they did a forEach(each -> map.put(each.getKey(), each.getValue()).

It might be pedantic to throw on duplicates, but that is supported by groupByUniqueKey(), if we want to give users a more discoverable API, we can add something like toMapThrowsOnDuplicates() or toMapUniqueKey() or something else. But we should not deprecate.

Cc-ing @mohrezaei for his thoughts as well.

**Comment by mohrezaei** [comment]
I've been following this. I usually tend to fall on the "not deprecate" side of the fence and in this case, it seems pretty straight forward, as alternate methods can be provided. 

I actually don't understand the return type issue. If the return type is `R extends Map<K,V>`, doesn't this code work just fine:

```
MutableMap<Integer,String> m = UnifiedMap.newMap();
richIterable.toMap(keyFunc, valueFunc, m).collectKeysAndValues(...);
                                         ^^^^^^^^^^^^^^---- a mutable map only method
```
In general, `R` as a parameter should be restricted to the smallest interface the method needs, which in this case is just something that has `put`.

**Comment by motlin** [comment]
When I see toMap() in code reviews, it raises questions. Do you expect unique entries? No? Then use groupBy. Yes? Then use groupByUniqueKey. Don't know? Why not? Wouldn't you want to know about duplicate keys? Similarly, if I saw `iterable.forEach(each -> map.put(keyFunction(each), valueFunction(each))` I would raise questions about that in a code review.

I personally have never used toMap() in my code. Deprecation-not-for-deletion is just documentation so obviously it's not critical and I don't need to push for it anymore. If I convinced you to think twice about using toMap() in new code then I'm happy.

Also, to deprecate, we probably would need good alternatives to exist. The method toMapUnique() doesn't exist. And groupByUniqueKey().collectValues() has different performance. I've been talking about LazyPairIterable which would also potentially be a good alternative, if it existed.

```java
iterable
    .asLazyPairs()
    .collectTwo(valueFunction)
    .toMap(); // <-- This version of toMap() would throw, or return Either<Map, Error>
```
