### ISSUE TITLE
Documentation: Practical examples

### ISSUE THREAD

**Issue by dirkgr** [eclipse/eclipse-collections#657]
Eclipse Collections is an amazing piece of work. When I need it, I am usually in some sort of performance trouble, and this library is the silver bullet that will save me.

However, that doesn't happen often enough that I remember the API, so every time I have to read through the documentation. And every time I have the same problem:

The examples you have are full of things you can do once you have a collection. There is nothing about ways to create a collection. Very little production code looks like `ImmutableList<String> immutableListOf = Lists.immutable.of("One", "Two");`. Most of the time the input comes from a file, or from a stream, or some other process. To figure out the idiomatic way of creating a collection, I'm off into the source code.

**Comment by nikhilnanivadekar** [comment]
@dirkgr thanks for using Eclipse Collections. Can you give an example of what sort of examples you would like in the Javadoc? We can add it to the readme or to the reference guide as well. You can also raise a PR with your suggestions, we will be happy to review and take a contribution.
Cheers!

**Comment by mohrezaei** [comment]
To reiterate what Nikhil said, if there was a piece of code that you figured out on your own, you could contribute a test case or documentation that showcases that piece.

**Comment by dirkgr** [comment]
I write in Scala, but it might be pretty similar. This is taken directly from some "production" code:
```Scala
    def indexFromLines(lines: Iterator[String]): Index = {
      val token2sentence: MutableSetMultimap[String, String] = Multimaps.mutable.set.empty()
      val token2count: MutableBag[String] = Bags.mutable.empty()
      val sentence2tokenized: MutableSetMultimap[String, String] = Multimaps.mutable.set.empty()

      lines.foreach { sentence =>
        val normalizedSentence = normalize(sentence)
        val tokens = stemmedTokenSet(normalizedSentence)

        sentence2tokenized.putAll(normalizedSentence, tokens.asJava)
        tokens.foreach { token =>
          token2count.add(token)
          token2sentence.put(token, normalizedSentence)
        }
      }

      Index(token2sentence.toImmutable, token2count.toImmutable, sentence2tokenized.toImmutable)
    }
```

The two main points here are
 * Apparently the idiomatic way of creating an immutable collection is to create a mutable one, insert a bunch of stuff, and then call `.toImmutable()`.
 * The other thing is `.add()`, `.put()`, `.putAll()`. I figured those out using code completion. Sure, it's obvious, but it could have been `.insert()` or some other word. I'm also confused why a `MutableSetMultimap` has `.putAll()`, but `MutableBag` does not. That's not a documentation issue, but it does make it more confusing when you use code completion to figure out the API.

**Comment by saurabhmj** [comment]
Hello @donraab @dirkgr ! I'm trying to learn eclipse-collections and I think working on this issue would be a great way for me to get a head start. Mind if I work on this?

I think that adding examples for `.toImmutable()` would come under [creating immutable collections](https://github.com/eclipse/eclipse-collections/blob/master/docs/guide.md#-creating-immutable-collections) section. 

Any idea where I could add the examples for `.newWith()`, `.newWithAll()`?

Appreciate your help!

**Comment by donraab** [comment]
@saurabhmj Thank you for the interest and this is a great contribution!  Adding `.toImmutable()` to this section makes sense to me.

I think adding a new section under "Immutable Collections" titled "Growing and Shrinking Immutable Collections" would make sense for `.newWith()`, `.newWithAll()`, `.newWithout()`, `.newWithoutAll()`.

**Comment by nikhilnanivadekar** [comment]
This is great! Agree with Don.
Please reach out to us if you need help!

**Comment by johnjstuart** [comment]
I see that @donraab merged this change in almost a year ago but the PR didn't have a closes tag so this issue still shows as open. Can this issue be closed manually now?

**Comment by donraab** [comment]
Good catch. Closing.
