### ISSUE TITLE
Implement MutableMapIterable#removeAllKeys(Iterable<K> keys).

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#663]

**Comment by brenopessoa** [comment]
Hello , What do you think about this implementation?

` default Collection<V> removeAllKeys(Iterable<K> keys) {
    	return StreamSupport
    		.stream(keys.spliterator(),false)
    		.map(this::remove)
    		.collect(Collectors.toCollection(ArrayList::new));
    }`

and maybe an overload with target collection for return.

Thank's

**Comment by nikhilnanivadekar** [comment]
@brenopessoa There is already an open PR for this: https://github.com/eclipse/eclipse-collections/pull/666

**Comment by brenopessoa** [comment]
Ok, thank you for the feedback.
