### ISSUE TITLE
eclipse gives error when importing project

### ISSUE THREAD

**Issue by david-gang** [eclipse/eclipse-collections#675]
After downloading the project and running 
mvn install -DskipTests
I import the project and get an error:

Errors occurred during the build.
Errors running builder 'Maven Project Builder' on project 'org.eclipse.collections'.
Missing parameter for pluginExecutionFilter. groupId, artifactId, versionRange and goals must be specificed, but found: groupId = 'org.eclipse.ebr'
artifactId = 'ebr-maven-plugin'
versionRange = '1.0.0-SNAPSHOT'
goals = '[]'

Afterwards i get an error:
Project 'eclipse-collections-testutils' is missing required Java project: 'eclipse-collections-api'
How can this be fixed?

i use eclipse photon

**Comment by nikhilnanivadekar** [comment]
@leomrlima @guw can you please help

**Comment by guw** [comment]
I think this is an M2E issue.

Here is a similar one:
https://github.com/deeplearning4j/deeplearning4j/issues/3625

Here is some documentation around this:
https://wiki.eclipse.org/M2E_compatible_maven_plugins#.3Cignore.2F.3E_mapping

**Comment by david-gang** [comment]
Thanks. Will close issue.
