### ISSUE TITLE
UnifiedSet java.lang.ArrayIndexOutOfBoundsException while iterating

### ISSUE THREAD

**Issue by arebgun** [eclipse/eclipse-collections#701]
I trying out Eclipse Collections for my project, using the latest available version - 9.2.0. Sometimes I am getting exceptions while iterating over a set (both while using UnifiedSet and UnifiedSetWithHashingStrategy):

`Error: java.lang.ArrayIndexOutOfBoundsException: Index 256 out of bounds for length 256
java.lang.ArrayIndexOutOfBoundsException: Index 256 out of bounds for length 256
	at org.eclipse.collections.impl.set.strategy.mutable.UnifiedSetWithHashingStrategy$PositionalIterator.next(UnifiedSetWithHashingStrategy.java:1834)`

the index can be different, I have seen 256, 512, 1024 and some other powers of 2. It doesn't look like I am doing anything special here.

Could be similar or related to #481?

**Comment by nikhilnanivadekar** [comment]
Thanks for trying out Eclipse Collections. Can you please share a test case or code which we can use to analyze?

**Comment by arebgun** [comment]
I don't have a test case that I can share right now. So far I just tried to use UnifiedSet a drop-in replacement for JDK's HashSet in a bigger project. I will try to distill a test case, although I have been unsuccessful so far.

**Comment by victornoel** [comment]
@arebgun are you sure that:
- you aren't using it in a concurrent context?
- you are not modifying it while iterating over it?

**Comment by arebgun** [comment]
@victornoel thanks for the ideas. It does look like the set is being added to while being iterated over.
