### ISSUE TITLE
UnmodifiableMutableList does not implement toArray

### ISSUE THREAD

**Issue by victornoel** [eclipse/eclipse-collections#722]
When using the Eclipse debugger, an instance of `UnmodifiableMutableList` can't be explored via the debugger because it does not implement `toArray`:
![image](https://user-images.githubusercontent.com/160975/57528759-70880700-7333-11e9-9fa5-8cc4446d0b2b.png)

I suppose it would be relevant to implement it, and also maybe for some other collections that are in the same situation?

**Comment by donraab** [comment]
Sounds reasonable to me.

**Comment by victornoel** [comment]
@donraab sorry, actually it seems to be an Eclipse bug related to Java 11: https://bugs.eclipse.org/bugs/show_bug.cgi?id=543604
