### ISSUE TITLE
Implement LongInterval

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#723]
Today we have IntInterval.  It would be useful to have LongInterval as well.  I don't know that we need more than just IntInterval and LongInterval, so I would hold off trying to code generate all of the primitive type versions of interval.

**Comment by prathasirisha** [comment]
Testing to see if commenting on an issue helps with assigning the ticket ourselves.

**Comment by vmzakharov** [comment]
So I took a stab at it (tests ported from `IntIntervalTest` pass) and would like to hear people's thoughts on the following:
1. Overflow. We should ignore overflow on aggregation operations, this is behavior consistent with `IntInterval` today*. If this is not desirable, another issue needs to be created specifically to handle overflows differently. 
2. The size of a long interval may exceed `Integer.MAX_VALUE`. One approach to handle it:
-  Implement all the `PrimitveList` methods, but fail if an index (or size, return result, etc.) would exceed maxint (e.g., for methods like `size()`, `toArray()`, `forEachWithIndex()`, etc.) 
- Also: Implement a parallel set of APIs supporting long sizes/indices (e.g., `longGet(long)`, `longSize()`, `forEachWithLongIndex()`, etc.). `toArray()` still won't won’t be supported for `size > maxint`, naturally.

**Comment by donraab** [comment]
Hi @vmzakharov if the work is ready, please submit a PR so we can visualize the issues and agree on approaches and make comments on the code. On point 2 though, I think a `LongInterval` should be consistent with other primitive lists and be limited to an `int` size. We can design and implement a different type that is not limited by an int size, but this would require some thoughts on new interfaces, etc.

**Comment by vmzakharov** [comment]
Will make the following changes before submitting a PR: 
- remove "long-indexed" versions of the APIs 
- `LongInterval` factory methods will throw when attempting to create an interval with the size exceeding `Integer.MAX_VALUE`.
