### ISSUE TITLE
Distinct element view of Bag 

### ISSUE THREAD

**Issue by victornoel** [eclipse/eclipse-collections#726]
It would be great to have a lazy view on Bags that contains the distinct elements of the Bag. It could be called `distinct` or `distinctView`.

Currently, the only way to work on the distinct elements of a Bag is to use `forEachWithOccurrences`.

An alternative could be a view which would contain `ObjectIntPair` with each distinct element and their number of occurrence.

**Comment by nikhilnanivadekar** [comment]
@victornoel this is a good idea. I think `distinctView()` is a better name. 
Curious about your use case: are you trying to manipulate the elements? If you just need a view, we might want to add asSet() and just return the keySet() of the backing map. thoughts?

**Comment by victornoel** [comment]
@nikhilnanivadekar I just want to iterate over the elements, or maybe collect something else based on them, so maybe I would do: `bag.distinctView().collect(e -> ...).toList()`.

So yes, it is basically a view that I am interested in: `asSet()` would totally correspond to my need.

**Comment by nikhilnanivadekar** [comment]
would you like to contribute? On the interface it can be default implementation which throws but implementation will have the actual `asSet()`

**Comment by victornoel** [comment]
@nikhilnanivadekar yes I can, not sure I will be able to before 2 weeks though, but I guess now that v10 is released, we have some time :)

Questions:
- the default implementation on the interface is needed for backward compat, right?
- I wonder if we should return a `MutableSet`, a `SetIterable` or a `RichIterable`?
  - If it's a `Set`, should it be an `UnmodifiableSet` like what is returned by primitive maps `keySet` method?
  - some of the implementation are not using a set-based collection inside so it's not going to be views in that case… I was thus thinking more of using `RichIterable` or a `LazyIterable` even for this, in the same way that the maps have a `keyView`.
- The actual implementations of `MutableBag` have internally a method `getKeysView` but it's not a `Set`, would it make sense to make this method be the same as the one I would be adding here?

**Comment by motlin** [comment]
SetIterable is ideal. LazyIterable is easier to implement but limiting.

**Comment by victornoel** [comment]
Hi, I started working on this, and I have some questions:

- To implement `asSet` for `ImmutableHashBag`, the best would be to reuse `ImmutableUnifiedSet` to wrap the `delegate.asSet()` of `ImmutableHashBag`. Of course this is not possible because the constructor of `ImmutableUnifiedSet` is private. What's the best course of action in that case?
- To implement it for `TreeBag`, the best would be to rely on `MutableSortedMap.keySet` which is meant to implement the correct interface for this (`SortedMutableSet`) but according to the javadoc, to stay compatible with Java 5, it is returning a `MutableSet`: are we still supporting only Java 5 and if not, is there some plan to change the interface of `MutableSortedMap.keySet`?

Some more questions will follow most certainly :)

**Comment by motlin** [comment]
@victornoel I think you can use the interface `ImmutableSet` but not the implementation `ImmutableUnifiedSet`. That's because `ImmutableUnifiedSet` actually holds a `UnifiedSet` and takes linear time to construct. A method named asSomething should return a view in constant time. This is not easy though. Take a look at the implementations of keySet and keysView for ideas.

**Comment by victornoel** [comment]
@motlin @nikhilnanivadekar thanks for your help, I finally finished the PR: #797.
