### ISSUE TITLE
Variable name in Multimaps class for ImmutableSortedBagFactory is incorrect

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#737]
The name of the variable is currently `multimap` and should instead be `sortedBag` in the `Multimaps` class.

This is what currently exists in the `ImmutableMultimaps` static inner class.
```
public final ImmutableSortedBagMultimapFactory multimap = new ImmutableSortedBagMultimapFactory();

```
This should be changed as follows:

```
public final ImmutableSortedBagMultimapFactory sortedBag = new ImmutableSortedBagMultimapFactory();

```

**Comment by nikhilnanivadekar** [comment]
Why would we name a variable a “Bag” inside a “Multimap” factory? What am I missing ?

**Comment by donraab** [comment]
In the inner class:
```
public static final class ImmutableMultimaps
{
    public final ImmutableListMultimapFactory list = new ImmutableListMultimapFactory();
    public final ImmutableSetMultimapFactory set = new ImmutableSetMultimapFactory();
    public final ImmutableSortedSetMultimapFactory sortedSet = new ImmutableSortedSetMultimapFactory();
    public final ImmutableBagMultimapFactory bag = new ImmutableBagMultimapFactory();
    public final ImmutableSortedBagMultimapFactory multimap = new ImmutableSortedBagMultimapFactory();

```

**Comment by motlin** [comment]
This is labeled minor-version. Is that because it's not a big deal?

**Comment by itohiro73** [comment]
I suppose this is minor-version because it's a naming bug.

**Comment by donraab** [comment]
I labeled it as a minor version because we can add sortedBag as a new variable, and leave multimap as it is with a deprecated warning and remove it in the next major version.  Make sense?

**Comment by nikhilnanivadekar** [comment]
Do we want to create a 10.1, or we should just go to 11. Even if we release it in 6 months, we should just do major version releases and service releases for critical bug fixes. I vote only major version releases, makes it easier to manage.

**Comment by donraab** [comment]
Ok with me.
