### ISSUE TITLE
Bag factories with occurrences

### ISSUE THREAD

**Issue by Isammoc** [eclipse/eclipse-collections#739]
Something like the `Maps.immutable.of` factory, but for bags:

```java
Bags.immutable.ofWithOccurrences(first, 3,
                                 second, 5);
```

**Comment by jiminhsieh** [comment]
I want to work on this one. I need the confirmation of this result is:
```java
Bags.immutable.with("first", "first", "first", "second", "second", "second", "second", "second");
```
Thanks.

**Comment by nikhilnanivadekar** [comment]
You can definitely add that in addition to variants like this:
(first, occurrence)
(first, occurrence, second, occurrence)
(third, occurrence, second, occurrence, third, occurrence)

We generally go till 4.

For Pair, please use an ObjectIntPair

**Comment by Isammoc** [comment]
> I want to work on this one. I need the confirmation of this result is:

Yes, it is close to it (my sample was with variables/constants)

```
Bags.immutable.with(first, first, first, second, second, second, second, second);
```
