### ISSUE TITLE
Equivalent to `java.util.TreeMap#floorEntry` with TreeSortedMap

### ISSUE THREAD

**Issue by lpellegr** [eclipse/eclipse-collections#741]
Your library is really awesome. 

I am trying to use it with a `org.eclipse.collections.impl.map.sorted.mutable.TreeSortedMap` in order to create a RangeMap data structure. 

For this purpose, I am looking for an equivalent to [java.util.TreeMap#floorEntry](https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html#floorEntry-K-) that is provided with the JDK. Unfortunately, it seems there is no similar method available in the eclipse-collections API. Is it right? Is there a way to implement such a method on top of the public API?

**Comment by lpellegr** [comment]
Erf, your implementation of `TreeSortedMap` relies on ` java.util.TreeMap`. So the solution in my case is to directly use the JDK implementation.

**Comment by nikhilnanivadekar** [comment]
Thanks for the compliments nonetheless. Please reach out if you need help in the future
