### ISSUE TITLE
Implement Interval.range() with similar behavior as IntStream.range()

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#744]
This issue can be merged with #743 .

**Comment by govi20** [comment]
@nikhilnanivadekar  @donraab would it be okay if I take this up?

**Comment by govi20** [comment]
@nikhilnanivadekar What should be output if from and to values are same and if to < from. Should exceptional be thrown as done in `Interval.fromToBy()`
I am planning to re-use fromToBy method, `Interval.fromToBy(newFrom, newTo - 1, 1);`

is this approach correct?

**Comment by nikhilnanivadekar** [comment]
I would want to avoid that. The IntStream.range() implementation is a bit more forgiving, especially around ‘from’ and ‘to’ being equal.

**Comment by sendilkumarn** [comment]
Can we close this issue? since #743 is merged :)

**Comment by nikhilnanivadekar** [comment]
This should have been auto-closed.

**Comment by nikhilnanivadekar** [comment]
Raised an issue with GitHub
