### ISSUE TITLE
aggregateBy for MapIterable should have a variant to aggregate on key and value

### ISSUE THREAD

**Issue by mgoldver** [eclipse/eclipse-collections#747]

**Comment by donraab** [comment]
Would this take a `Function` for the groupBy as well as a `Function` to apply to the value?

**Comment by mgoldver** [comment]
Makes sense, thanks Don.

**Comment by goldbal330** [comment]
I would be interested int helping out with implementation of this feature. 
Thanks.

**Comment by donraab** [comment]
Thanks @goldbal330 ! I have assigned it to you.

**Comment by goldbal330** [comment]
Thanks, @donraab. 
I would like to make sure we agree on the method signature.

If I add a new method to 
MapIterable (public interface MapIterable<K, V> extends RichIterable<V>)
does the method signature bellow make sense?

 default <K1, V1> MapIterable<K1, V1> aggregateBy(
            Function2<? super K, ? super V, ? extends K1> groupByKeyValue,
            Function0<? extends V1> zeroValueFactory,
            Function2<? super V1, ? super V, ? extends V1> nonMutatingAggregator)


Thanks.
@goldbal330.

**Comment by donraab** [comment]
I think what @mgoldver was asking for was:

```
 default <K1, V1, V2> MapIterable<K1, V2> aggregateBy(
            Function<? super K, ? extends K1> keyFunction,
            Function<? super V, ? extends V1> valueFunction,
            Function0<? extends V2> zeroValueFactory,
            Function2<? super V2, ? super V1, ? extends V2> nonMutatingAggregator)
```

@mgoldver can you confirm?

**Comment by mgoldver** [comment]
Hi guys, yes, agree with Don.
Thanks a lot
MikeG

**Comment by mgoldver** [comment]
Hi @goldbal330, Thanks a lot. Closing the issue.

**Comment by nikhilnanivadekar** [comment]
It’ll be auto-closed once we merge the PR
