### ISSUE TITLE
Add withMap() to MutableMap and MutableMapFactory

### ISSUE THREAD

**Issue by mkrivoshein** [eclipse/eclipse-collections#761]
Would be nice to have utility methods that can add contents of an another map while allowing use of the API in a builder pattern style.

It will especially be useful if you already have multiple maps and you want to create an union of these maps.

```
ImmutableMap<String, String> map = Maps.mutable
           .withMap(firstMap)
           .withMap(secondMap)
           .withMap(thirdMap)
           .toImmutable();
```

Just as a reference, similar functionality is available with Guava ImmutableMap builder.

**Comment by nikhilnanivadekar** [comment]
this makes sense. We have withKeyValue() but with do not have withMap().
Would you like to contribute this enhancement? This should be relatively straightforward and quick to implement. I will be happy to guide you through.

**Comment by mkrivoshein** [comment]
I'd be interesting experience. Will look into what needs to be done to become a contributor first.

**Comment by nikhilnanivadekar** [comment]
Please read our contribution guide. And feel free to ask questions on this
issue. Please tag me so that they show up in my notifications. Once you
raise a PR we can discuss on the PR itself. Thanks!

**Comment by victornoel** [comment]
it would make sense to have both `withMap(MapIterable)` and `withMap(Map)` methods I think, no?
