### ISSUE TITLE
IntInterval.fromToBy(n, n, -x) doesn't work as expected

### ISSUE THREAD

**Issue by slemouzy** [eclipse/eclipse-collections#762]
Using eclipse collections 10.0.0

`IntInterval.fromToBy(2, 2, -1).toList()` raises an exception whereas we expect `[2]`.

 Here is the exception raised:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.eclipse.collections.impl.list.primitive.IntInterval.lambda$toArray$7243f8d6$1(IntInterval.java:610)
	at org.eclipse.collections.impl.list.primitive.IntInterval.forEachWithIndex(IntInterval.java:324)
	at org.eclipse.collections.impl.list.primitive.IntInterval.toArray(IntInterval.java:610)
	at org.eclipse.collections.impl.list.mutable.primitive.IntArrayList.newList(IntArrayList.java:98)
	at org.eclipse.collections.impl.list.primitive.IntInterval.toList(IntInterval.java:900)
       [...]
```

`IntInterval.fromToBy(2,2,-2).forEach(i -> { System.out.println(i);}); ` prints an infinite sequence of decreasing integers whereas we expect just `2`.

This behaviour is not the same as `Interval.fromToBy(2,2,-2)` wich seems to be ok.

**Comment by nikhilnanivadekar** [comment]
Thanks @slemouzy for reporting this. This is a bug and we will put in a fix with our next release. Currently, we do not have a release planned, however, if this is critical for your application, I will be happy to release a patch version. Once the bug fix is merged. Please let me know.
Cc @donraab @cguntur-bnym

**Comment by slemouzy** [comment]
@nikhilnanivadekar thank you for the proposition of releasing a patch version but it is not necessary since using `Interval` instead of `IntInterval` is an acceptable temporary workaround for our application.

**Comment by nikhilnanivadekar** [comment]
great! thanks!

**Comment by cguntur-bnym** [comment]
I'll start work on the issue for the next planned release.

**Comment by nikhilnanivadekar** [comment]
@slemouzy I will be working on a 10.1.0 milestone release. It should be in maven central by Friday evening US hours. If you get a chance please try to test the fix with the milestone release. I will ping the maven central coordinates here once they are available. Thanks!

**Comment by slemouzy** [comment]
@nikhilnanivadekar thank you for the fix. Sure I will test the fix as soon as you ping me the maven central coordinates.

**Comment by nikhilnanivadekar** [comment]
@slemouzy the milestone coordinates are below. Please note the final 10.1.0 release will be done on December 4th. So, please let us know if things are working fine. Thank you!
```
<dependency>
  <groupId>org.eclipse.collections</groupId>
  <artifactId>eclipse-collections-api</artifactId>
  <version>10.1.0.M2</version>
</dependency>

<dependency>
  <groupId>org.eclipse.collections</groupId>
  <artifactId>eclipse-collections</artifactId>
  <version>10.1.0.M2</version>
</dependency>
```
Maven Central link: https://search.maven.org/search?q=org.eclipse.collections

**Comment by slemouzy** [comment]
@nikhilnanivadekar sorry for the delay, I've tested the fix and everything is working like a charm. Thank you for the work. :+1:

**Comment by nikhilnanivadekar** [comment]
Perfect! Thanks! I’ll release 10.1.0 on December 4th, it’ll be available on maven central on December 5th or 6th. Look out for the release notes
