### ISSUE TITLE
Make org.eclipse.collections.impl.list.Interval#goForward private

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#775]
This should be done during major version.

**Comment by heowc** [comment]
I will work on it!

**Comment by vibhuti019** [comment]
I am a newbie and i would like to work if the issue is not fixed.

**Comment by nikhilnanivadekar** [comment]
This is not being worked on yet. Feel free to contribute. Thanks for your help and contribution!

**Comment by vibhuti019** [comment]
Can you please explain the issue?

**Comment by nikhilnanivadekar** [comment]
In the Interval class there is a method called `goForward` we want to make it `private` There will be a similar method in IntInterval class as well which should become private

**Comment by vibhuti019** [comment]
goForward in IntInterval is already private

**Comment by vibhuti019** [comment]
The Pull Request is Showing this problem: --

Anonymous (vibhutisingh037@****.com) is not covered by the necessary legal agreements in order to proceed

**Comment by vibhuti019** [comment]
Refer #805
