### ISSUE TITLE
Provide a way to track heap allocations

### ISSUE THREAD

**Issue by klaren** [eclipse/eclipse-collections#787]
Hi,

I'm currently facing an issue where we have a lot of collections that eventually throws `OutOfMemoryError`. The workload is user-generated and killing a request is viable. So I'm looking for a way to track the size of the collections, e.g. `LongObjectHashMap`, without resorting to using reflections. Ideally, I would like a callback in `LongObjectHashMap#allocateTable` that will be invoked before allocation and potentially throw an exception, thus preventing the large allocations that will happen there.

Have you tried implementing anything like this in the past?
Or do you have some other ideas about how this can be done?

**Comment by mohrezaei** [comment]
If I understand you correctly, you have some user-defined workload that may generate too many map entries. Are you processing many requests simultaneously or one at a time?

For the hashed structures, their size is proportional to `size()` method of the collection itself. Growth only happens when adding, so it should be possible to implement what you want by simply aborting when `size()` gets to a per-defined value. If you have many users, you can put a cap on the size per user/per thread. Please note that for a XObjectHashMap, the size of the object storage (not the arrays in the map) would be quite significant too (at least 50% of the memory, if not much more).

**Comment by klaren** [comment]
We serve concurrent requests in separate threads so a cap per thread would be our goal. We already track the objects heap usage.

What do you mean by proportional in size? Don't the backing arrays grow in increments in powers of 2?

Another way to make this possible would be to make `allocateTable` protected.

**Comment by mohrezaei** [comment]
Sorry, let me be more clear. Just before a resize, the internal overhead is proportional to size. The size can be computed like this:
```
        int slots = Integer.highestOneBit(map.size()) << 1;
        long overheadPerSlot = KEY_SIZE * 2 + VAL_SIZE * 2;
        long totalBytes = slots * overheadPerSlot;
```
Long KEY_SIZE is 8. Object VAL_SIZE is 4 for 32bit JVM or 64bit with compressed oops. It's 8 for plain 64bit.

**Comment by klaren** [comment]
I understand that it will work, but we will have to do the calculations on all of the maps all the time. Most of the time the calculations will be exactly the same, and in the case of a resize event, we only do the calculations when those occur. 

Making the `allocateTable` method `protected` will solve this. What do you think about that approach?

```java
public class MyLongHashSet extends LongHashSet
{
    @Override
    protected void allocateTable(int sizeToAllocate)
    {
        // recalculate heap usage, throw if exceeding threshold
        super.allocateTable(sizeToAllocate);
    }
}
```

I can make a PR with the change if you think this will be useful.

**Comment by mohrezaei** [comment]
If you want to override methods, why don't you override `put()`?

**Comment by klaren** [comment]
Let's look at this more complete example:

```java
public class HeapTrackingLongHashSet<V> extends LongObjectHashMap<V> implements AutoCloseable
{
    private static final long OVERHEAD_PER_SLOT = Long.BYTES * 2 + NUM_BYTES_OBJECT_REF * 2;
    private final HeapTracker heapTracker = ...;
    private long totalBytesTracked;

    @Override
    public V put( long key, V value )
    {
        recalculateHeapUsage();
        return super.put( key, value );
    }

    @Override
    public V getIfAbsentPut( long key, Function0<? extends V> function )
    {
        recalculateHeapUsage();
        return super.getIfAbsentPut( key, function );
    }

    @Override
    public <P> V getIfAbsentPutWith( long key, Function<? super P,? extends V> function, P parameter )
    {
        recalculateHeapUsage();
        return super.getIfAbsentPutWith( key, function, parameter );
    }

    @Override
    public V getIfAbsentPutWithKey( long key, LongToObjectFunction<? extends V> function )
    {
        recalculateHeapUsage();
        return super.getIfAbsentPutWithKey( key, function );
    }

    private void recalculateHeapUsage()
    {
        long totalBytes = (Integer.highestOneBit( size() + 1 ) << 1) * OVERHEAD_PER_SLOT;
        if ( totalBytes != totalBytesTracked )
        {
            heapTracker.adjustHeapUsage( totalBytes - totalBytesTracked ); // throws when exceeding threshold
            totalBytesTracked = totalBytes;
        }
    }

    @Override
    public void close() throws Exception
    {
        heapTracker.adjustHeapUsage( -totalBytesTracked );
    }
}
```
This will not work in every case either. Since the collections only shrink when you call `.compact()`, adding a lot of elements and then removing them, will claim that the collection is smaller than it actually is. It's also unnecessary cpu time spent on calculating the same values over and over again. Overriding `allocateTable` would avoid both problems.

But I can see why you don't want to expose the `allocateTable` as well, so feel free to close this issue if you think this is too large of a change.

**Comment by mohrezaei** [comment]
It might be helpful to understand the code around this. In my experience, map growth is not something that happens in many places in a pseudo-random fashion. Maps are typically grown in a single place, usually a loop. If that's the case, it's not hard to add a simple check to the loop. How is your map growing?

You also mentioned "We already track the objects heap usage". Can you put a limit on the object count (per user/thread) instead of weaving all this tracking code?

**Comment by klaren** [comment]
This is a couple of places where we need to track the sizes:
* https://github.com/neo4j/neo4j/blob/4.0/community/kernel/src/main/java/org/neo4j/kernel/impl/api/state/TxState.java
 * https://github.com/neo4j/neo4j/blob/4.0/community/kernel/src/main/java/org/neo4j/kernel/impl/api/state/RelationshipChangesForNode.java
* https://github.com/neo4j/neo4j/blob/4.0/community/kernel/src/main/java/org/neo4j/kernel/impl/api/state/EntityStateImpl.java
* https://github.com/neo4j/neo4j/blob/4.0/community/kernel/src/main/java/org/neo4j/kernel/impl/util/diffsets/MutableLongDiffSetsImpl.java

The collections travel through the whole stack and accumulate changes based on currently stored data and provided user queries, so from our point of view it might as well be pseudo-random. Many of the collections are pure primitive as well, with no other heap allocation than the backing arrays, so setting a cap only on the objects themself would not solve the problem.

I already did the tracking for `UnifiedMap` which has a protected `allocateTable` method. What are the objections to making the same method protected in the primitive maps/sets as well?

**Comment by mohrezaei** [comment]
Thanks for sharing the code. I think I see the real issue here: you have lots of collections and a size restriction on a single one doesn't make sense. You have to track the sum.

I don't have any objections to marking `allocateTable` `protected`.
