### ISSUE TITLE
flatCollect missing for primitive collections

### ISSUE THREAD

**Issue by fipro78** [eclipse/eclipse-collections#794]
I have a map that looks like this:

```
MutableMap<String, MutableIntSet> hidden = Maps.mutable.empty();
this.hidden.put("Test1", IntSets.mutable.ofAll(IntStream.range(0, 100_000))); 
this.hidden.put("Test2", IntSets.mutable.ofAll(IntStream.range(100_001, 200_000))); 
this.hidden.put("Test3", IntSets.mutable.ofAll(IntStream.range(200_000, 300_000))); 
this.hidden.put("Test4", IntSets.mutable.ofAll(IntStream.range(300_000, 400_000))); 
this.hidden.put("Test5", IntSets.mutable.ofAll(IntStream.range(400_000, 500_000))); 
```

In a later stage I want to get all int values in a flattened map. But the flatCollect() methods do not support primitive values. At least I do not find a way to get a flattened primitive MutableIntSet.

Maybe I am missing something as I just started with Eclipse Collections, but IMHO the API is missing. Im am currently creating a flattened collection like this:

```
MutableIntSet hiddenColumnIndexes = IntSets.mutable.empty();
for (MutableIntSet indexes : hidden.values()) {
    hiddenColumnIndexes.addAll(indexes);
}
return hiddenColumnIndexes.toSortedArray();
```
In 100 executions this takes about 50ms. Changing this to use a MutableIntList and do a distinct at the end results in about 40ms.

```
MutableIntList hiddenColumnIndexes = IntLists.mutable.empty();
for (MutableIntSet indexes : hidden.values()) {
    hiddenColumnIndexes.addAll(indexes);
}
return hiddenColumnIndexes.distinct().toSortedArray();
```

Not sure if this of interest for you. Just wanted to point out my observations and the missing flatten API on primitive types. If I missed some API, please let me know.

**Comment by donraab** [comment]
This is interesting, but could also result in a method explosion if we're not careful. We could add default methods to RichIterable for each of the primitives. Maybe something like:

```
default <R extends MutableIntCollection> R flatCollectInt(Function<? super T, ? extends IntIterable> function, R target)
{
    this.forEach(each -> target.addAll(function.valueOf(each)));
    return target;
}
```
This would provide good symmetry with the equivalent collect-Primitive methods.

@motlin @nikhilnanivadekar Thoughts?

**Comment by goldbal330** [comment]
I would like to work on this if help is needed.

**Comment by donraab** [comment]
Hi @fipro78, just wanted to confirm this is the API that you were looking for on `RichIterable`. Did you want to implement this or are you ok if I assign it to @goldbal330 who has expressed interest above? 

```
default <R extends MutableIntCollection> R flatCollectInt(Function<? super T, ? extends IntIterable> function, R target)
{
    this.forEach(each -> target.addAll(function.valueOf(each)));
    return target;
}
```

**Comment by goldbal330** [comment]
Do we want to implement this for all primitive types currently supported by EC (boolean, double, float, short, int, long, byte, char) or restrict to the most popular types (int, double) to keep the number of methods in RichIterable from growing much?

Thanks.

**Comment by donraab** [comment]
To be consistent with collect, we should implement them all.

**Comment by fipro78** [comment]
Hi @donraab, sorry for the late reply. Well I think this is the API I was looking for. But also without providing the target collection. Not sure if this is possible.
Actu I did not plan to work on this myself. I am still trying to understand and use everything correctly (blog post in work). So if anyone wants to take it, I'll be glad. If not I could try. Not sure when I will be able to make it.

**Comment by donraab** [comment]
Hi @fipro78, I would suggest we don't add the version without the target collection for a simple reason. It is a tremendous amount of work to provide co-variant overrides (List returns primitive Lists, Set returns primitive Sets, etc.). The target collection variety gives the functionality at a small fraction of the cost, as the behaviors can be implemented simply as default methods in `RichIterable` and then overridden for performance as necessary.

@goldbal330 has volunteered so I assigned the issue to him. It would be great if you could review the code when he submits a PR and see that it can satisfy your requirements. 

I'd love to read your blog post when you're ready to share.  Thank you!

**Comment by goldbal330** [comment]
This issue should be probably closed since the contribution was merged.
