### ISSUE TITLE
MutableMap's functions arguments for MultiValues should extends Iterable instead of super

### ISSUE THREAD

**Issue by henohenotsuyoshi** [eclipse/eclipse-collections#803]
Hi,
Multimap's functions arguments for MultiValues, such as selectKeysMultiValues, forEachKeyMultiValues, take super class of Iterable currently. 
I think it should be subclass of Iterable.
How does anyone think ?

**Comment by nikhilnanivadekar** [comment]
This is not possible as Java generics are invariant. You can give it a try with ListMultimap and SetMultimap and see if it compiles. It’s possible that I missed something

**Comment by motlin** [comment]
Agreed, Java generics aren't strong enough to have an ideal signature here.
I'm curious if you can share an example of code that came out awkward
because of the type signature.

**Comment by henohenotsuyoshi** [comment]
Hi, agree with you two. First of all, my idea is not right as Multimap should not take subclass of Iterable as it should not know which collection class is actual implementation of multi values in subclass.(List ? Set ?)
And I confirmed that SetMultimap cannot compile with override like below.  
`
    @Override
    SetMultimap<K, V> selectKeysMultiValues(Predicate2<? super K, ? super Set<V>> predicate);
`
Thanks
