### ISSUE TITLE
Fix Javadoc warnings and build for latest JDK

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#808]

**Comment by kedar-joshi** [comment]
Hey @nikhilnanivadekar, I would like to take this up but I will need a bit of your help in understanding scope of the expected change.

Can you elaborate on the requirement ?

**Comment by nikhilnanivadekar** [comment]
Let me try to see if I can setup a Travis build so that you can see the issue. Once you see the issue it’ll be clear what is going on. I’ll keep you posted.

**Comment by nikhilnanivadekar** [comment]
hi @kedar-joshi I have setup the Javadoc build on Travis: https://travis-ci.org/eclipse/eclipse-collections
It is the 3rd build from the bottom. Currently, the build is throwing 1 error and several warnings. We would like to eliminate the error as the first step, and then eliminate the warnings as the next step. These can be different commits and different PRs. Thanks for your help and contribution!

**Comment by kedar-joshi** [comment]
@nikhilnanivadekar I have raised gh-816 for the Javadoc error. CI build also passes. 

Quick question, should I also update `Copyright (c) 2019` to `Copyright (c) 2020` in all the files that I change ?

**Comment by kedar-joshi** [comment]
.. and gh-817 should take care of the Javadoc warnings.
