### ISSUE TITLE
Migrate all Travis CI builds to GitHub Actions

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#821]
We now have an initial GitHub Actions workflow set up for Eclipse Collections, but we would like to migrate all current CI builds from Travis CI.

**Comment by nikhilnanivadekar** [comment]
That might be a bit premature. I have seen GitHub CI lock up over the past 2 days. I would suggest to keep Travis, GH actions and TeamCity as is

**Comment by donraab** [comment]
@brunoborges

**Comment by motlin** [comment]
Why migrate away from travis? Why toward GitHub Actions?

**Comment by donraab** [comment]
Better integration, and so far, better performance.  The UI is also nicer in my opinion.  My feeling is that the integration and support will only improve over time.

**Comment by sendilkumarn** [comment]
Started the work [here](https://github.com/sendilkumarn/eclipse-collections/tree/feat/enable-travis/.github/workflows). This way we can extend the `acceptance` | `findbugs` | `check style` and others to various java versions. 


P.S. This is just an initial idea. Still have to do a little bit of work on it.

**Comment by donraab** [comment]
Thanks for offering to work on this @sendilkumarn.  I assigned the issue to you.

**Comment by donraab** [comment]
@motlin I think you have successfully demonstrated one of my points on why we need to migrate to GitHub Actions (performance).  All of the PRs you submitted today are waiting for the Travis builds to complete.  All of the GitHub Actions builds for the same PRs are completed.

**Comment by motlin** [comment]
@donraab Sounds good. The travis builds do a lot so it probably makes sense to migrate one job at a time and delete each from travis after it's working well in GitHub. If we leave a few behind in travis, they'll still perform a lot better than today.

**Comment by donraab** [comment]
I'm hoping @sendilkumarn will show us a good way to organize these and a gradual migration is a great idea.  Thanks!

**Comment by sendilkumarn** [comment]
The pending stuff is migrating all `OracleJDK` builds to GitHub Actions. We don't have out of the box setup for the `OracleJDK` in GitHub Actions. We can custom build the setup for this. I will start that (but it will take sometime).

**Comment by motlin** [comment]
What's the latest here? Are we ready to delete the remaining travis build? Anything I can do to help?

@sendilkumarn @donraab @nikhilnanivadekar

**Comment by mohrezaei** [comment]
I don't think it's reasonable to keep travis because of `OracleJDK`. The oracle JDK versions they have are ancient (e.g. 1.8 is 4 years and 100 revisions old), despite the documentation claims otherwise. I believe this is what's causing the failures in the new maven upgrades (PR #844) where the ancient JDK's can't even establish a proper HTTPS connection to some eclipse servers.

Since Oracle makes it so hard to get/install/test their JDKs I'm not sure there is any other choice.

**Comment by donraab** [comment]
I'm fine to get rid of it. @nikhilnanivadekar any concerns from the QualityOutreach program perspective?

**Comment by nikhilnanivadekar** [comment]
I will need to check that

**Comment by mohrezaei** [comment]
this thing? https://wiki.openjdk.java.net/display/quality/Quality+Outreach

That looks like just OpenJDK stuff. Is there another for oracle (non-open source) stuff?

**Comment by nikhilnanivadekar** [comment]
@mohrezaei yes you are right. I got the confirmation offline via email. So, I think we are good to remove dependency on Travis.

**Comment by nikhilnanivadekar** [comment]
Closing as this is done via multiple PRs.
