### ISSUE TITLE
Pull up the implementations of with(), without(), withAll(), withoutAll() as default methods.

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#822]
These four methods on MutableCollection could be pulled up as default methods on it and its sub-interfaces.

```
    MutableCollection<T> with(T element);
    MutableCollection<T> without(T element);
    MutableCollection<T> withAll(Iterable<? extends T> elements);
    MutableCollection<T> withoutAll(Iterable<? extends T> elements);
```

**Comment by donraab** [comment]
The thing that always perplexed me about doing this is that you have to choose then how to co-variantly override. Choice one says call super and cast the return type (pro - no duplicate code). Choice two says reimplement in the sub-interface with the more specific return (pro - no casting). I wish there was a choice three. Let's at least agree before someone implements what the best default implementation option is in the sub-interfaces

**Comment by motlin** [comment]
With these you can call super and return `this`

**Comment by donraab** [comment]
Ok, perfect.  Option three: Implicit casting.
