### ISSUE TITLE
Non-intuitive behavior for MutableMap.to*Map()

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#823]
This test fails because we consider the MutableMap<K, V> to be RichIterable<V>. However, that is not intuitive as we should be able to convert an unsorted map to sorted map.:

```
   @Test
    public void toSortedMap()
    {
        MutableMap<String, String> with = Maps.mutable.with("arb1", "arb", "arb2", "arb");
        MutableSortedMap<String, String> strings = with.toSortedMap(each -> each, each -> each);
        Verify.assertSize(2, strings);
    }
```

Thoughts?

**Comment by donraab** [comment]
This ship has sailed.  `MutableMap<K, V>` is `RichIterable<V>`.  The expectation therefore is that you only iterate over values in the to methods.

I think there is or could be a `collect` that can cover transforming from an unsorted map to a sorted map.

**Comment by nikhilnanivadekar** [comment]
Currently there isn’t a collect() to transform a Map to SortedMap. We should have that

**Comment by motlin** [comment]
I've written about this idea before but I think we should have something
like asLazy() but for the key-value pairs of maps.

unsortedMap.asLazyMap().collectKeys(functionK).collectValues(functionV).toSortedMap(comparatorKK)

**Comment by donraab** [comment]
I'm going to close this issue until we come up with a proposed solution that someone could reasonably implement.
