### ISSUE TITLE
Fix symmetry issues with factory methods in Multimaps factory.

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#826]
`MutableSortedBagMultimapFactory` is missing `of` methods and methods that take `Comparator`.
`ImmutableSortedBagMultimapFactory` is missing methods that do not take `Comparator`.

**Comment by goldbal330** [comment]
I would like to contribute.

**Comment by donraab** [comment]
Thanks! Assigned the issue to you @goldbal330.
