### ISSUE TITLE
Upgrade to JUnit 4.13.

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#827]
JUnit 4.13 adds two variants of assertThrows.

```
public static <T extends Throwable> T assertThrows(Class<T> expectedThrowable, ThrowingRunnable runnable)
public static <T extends Throwable> T assertThrows(String message, Class<T> expectedThrowable, ThrowingRunnable runnable)
```

These methods clash with `Verify.assertThrows()`.
```
public static void assertThrows(Class<? extends Exception> expectedExceptionClass, Runnable code)
```

This causes some calls to `Verify.assertThrows()` to fail with `java: error: reference to assertThrows is ambiguous`

I wanted to discuss our options here.
* Delete `Verify.assertThrows(Class, Runnable)` in the next major version.
* Or change `Verify` to no longer extend `Assert` in the next major version.
* Deprecate `Verify.assertThrows(Class, Runnable)` now, although it's unclear if the deprecation is actionable.
* Replace usages of `Verify.assertThrows` with `Assert.assertThrow` though it's unclear if that can be done in a minor version.
* Upgrade to JUnit 4.13, though it's unclear if that can be done in a minor version.
* Add `Verify.assertThrows(Class, ThrowingRunnable)` using JUnit's `ThrowingRunnable` for better compatibility in a minor release.

Thoughts @donraab @nikhilnanivadekar?

**Comment by donraab** [comment]
> Or change Verify to no longer extend Assert in the next major version.

This feels like the best option to me, although it will break code that was calling methods on Verify that were actually on Assert.  I think this is the best option because it prevents more problems of clashing APIs in the future.

**Comment by nikhilnanivadekar** [comment]
We might not be able to upgrade to JUnit 4.13 in minor version. We should do it in major version and instead of removing the inheritance, we can delete the API from Verify. Due to the inheritance it should still allow Verify.assertThrows() without issues. This will be shown as a breaking change in release notes, so we should be able to notify the users of how they need to change.
Removing the inheritance might cause additional issues.

**Comment by motlin** [comment]
Sounds good to me. Any thoughts on when the next major version will be?

**Comment by sendilkumarn** [comment]
Since we are planning for 11.0. Can we add this to the release? 

> * Replace usages of `Verify.assertThrows` with `Assert.assertThrow` though it's unclear if that can be done in a minor version.

I'm in favor of this. But also would it make sense to migrate to `JUnit5` ?

**Comment by nikhilnanivadekar** [comment]
I don’t want to move to Junit5 yet

**Comment by sendilkumarn** [comment]
any specific reason?

**Comment by donraab** [comment]
We have over 150K unit tests. I might be wrong, but it could be a huge undertaking to upgrade to JUnit5, and the code reviews alone on this could take days if not weeks.

**Comment by nikhilnanivadekar** [comment]
It is more than just changing the unit tests. The packaging of JUnit 5 has changed, so it is not a drop-in replacement. Additionally, the way JUnit 5 is split up, we will go from requiring 1 dependency to multiple modular dependencies. Having used JUnit-5, I dont see so much of a value in spending cycles to do the upgrade from JUnit-4 to JUnit-5. The only time in my opinion we will move from JUnit-4 to JUnit-5 IMO is when JUnit-4 support is completely abandoned. From the looks of it it does not look like that is about to happen anytime soon.
So, from a work to returns perspective, it not worth it.

FWIW I am working on the upgrade of JUnit-4 in a separate branch, and should be able to raise a PR next week.

**Comment by sendilkumarn** [comment]
I do agree!  But nevertheless we will have to migrate in the future. For not let us focus on 4.13
