### ISSUE TITLE
To integrate Eclipse Collections with Spring Data JPA

### ISSUE THREAD

**Issue by felixgilioli** [eclipse/eclipse-collections#868]
is it possible integration eclipse collections with spring data jpa + hibernate?

for example:

```
import org.springframework.data.jpa.repository.JpaRepository;
import org.eclipse.collections.api.list.ImmutableList;

public interface UserRepository extends JpaRepository<User, Long> {

    ImmutableList<User> findByActiveTrue();

}
```

**Comment by donraab** [comment]
Hi @felixgilioli. I left a comment on StackOverflow. I will replicate here:

Anything is possible, but I'm not sure if this is easy or a lot of work. Have you tried looking to see if JPA supports extensions for custom collections? I haven't used Spring Data JPA. A long time ago I looked at the possibility of implementing custom collections for Hibernate for Eclipse Collections. It looked possible, but this would likely be a full project on its own. I never had a need to implement it myself, so I haven't spent any time trying to code it. I'd be happy if someone wanted to build out the support for it.

**Comment by neha-ranjan27** [comment]
hi @donraab 

I work as an IT professional. I am looking for open source contribution.
Can you provide more clarity on this issue. I am interested in taking it up.
I have used Spring Data JPA for connecting to sql server.

**Comment by donraab** [comment]
Hi @neha-ranjan27, this was really more of a question than an issue. Any integration between Eclipse Collections and Spring Data JPA would be done outside of Eclipse Collections. I will close this issue.
