### ISSUE TITLE
ImmutableMap newWithAll() method that takes a MapIterable

### ISSUE THREAD

**Issue by ArthurCaron** [eclipse/eclipse-collections#875]
First of all, thank you for this really cool library :D.

I need to merge `ImmutableMap`s and I couldn't find a method to do it directly. 
Currently, I use this:
`myImmutableMap.newWithAllKeyValues(myOtherImmutableMap.keyValuesView())` 
But if feels like a workaround. Is there a more direct approach?
What I was looking for is something like:
`myImmutableMap.newWithAll(myOtherImmutableMap)`. 

What do you think?

An example:
```
var myImmutableMap = Maps.immutable.of("firstKey", "firstValue");
var myOtherImmutableMap = Maps.immutable.of("secondKey", "secondValue");

var result1 = myImmutableMap.newWithAllKeyValues(myOtherImmutableMap.keyValuesView());
// Could be:
var result2 = myImmutableMap.newWithAll(myOtherImmutableMap);
// AND/OR:
var result3 = Maps.immutable.ofAll(myImmutableMap, myOtherImmutableMap);

var expectedResult = Maps.immutable.of("firstKey", "firstValue", "secondKey", "secondValue");

assertEquals(result1, expectedResult);
assertEquals(result2, expectedResult);
assertEquals(result3, expectedResult);

// Note: if two keys are identical in the two maps, I would expect the same behavior as newWithAllKeyValues
```

**Comment by prathasirisha** [comment]
Hi @ArthurCaron, 

Thank you for your question. Caught up with @donraab, we could add the method you are looking for and the method names will be : `newWithMap(Map)` ,` newWithMapInterable(MapIterbale)`. 
We would also need to add the same in MutableMap `withMapIterable` (`withMap` already exists) 

cc: @donraab @nikhilnanivadekar

**Comment by nikhilnanivadekar** [comment]
@ArthurCaron would you be interested to contribute this API? It makes sense and as @prathasirisha mentioned we will need to maintain symmetry between immutable and mutable side.

**Comment by donraab** [comment]
@ArthurCaron have you started working on this feature already? Please us know. If not, I will assign the issue to @nsardana-bny.

**Comment by nikhilnanivadekar** [comment]
Due to no response from @ArthurCaron , I am assigning it to @nsardana-bny . Neha, feel free to reach out with questions or concerns.
