### ISSUE TITLE
Implement RichIterable.getOnly().

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#88]
The implementation should be similar to `IterableIterate.getOnly()` but be available on the interface `RichIterable.` If the iterable has exactly one item, return it. Otherwise, throw `IllegalArgumentException` with a short explanation.

**Comment by itohro** [comment]
@opengl-8080 showed an interest to contribute to this issue, so I'd reserve this issue for him. 

@opengl-8080, feel free to post questions in Japanese. I can translate here.

**Comment by opengl-8080** [comment]
Thank you for providing opportunity of contribution.

I have a question about work of this issue.

My understanding is following.

- Add `getOnly()` method into `RichIterable` interface.
- Implement `getOnly()` method at some sub classes(`UnmodifiableRichIterable`, `SynchronizedRichIterable`, `AbstractRichIterable`, and more...).
    - I can't implement `getOnly()` method as default method in `RichIterable`. Because language level of `eclipse-collections` module is 1.5.
- Add test method for `getOnly()` method into `RichITerableTestCase`.

Is this understanding correct?

Thank you.

**Comment by donraab** [comment]
Yes, you are correct.  We need to upgrade the language level of all of the modules to 1.8.  I had a similar problem this evening when I tried implementing summarizingInt/Long/Float/Double on RichIterable using default methods.

**Comment by itohro** [comment]
Yes, we'll upgrade language level to 1.8 shortly.

Afterwards you could use default method in RichIterable. 

@opengl-8080, your basic understanding is correct. Along the way you'd most likely need to modify more files (e.g. stg files for primitive collections, other test files for test variants etc.), but you'll find those out while you build your project and run tests.

**Comment by opengl-8080** [comment]
@donraab, @itohro
Thank you for your reply!


@itohro
> e.g. stg files for primitive collections, other test files for test variants etc.

Does it means following?

For Example, I add `getOnly()` method into `RichIterable`. Then `ImmutableByteObjectEmptyMap` become compile error.
Therefore I need modify 2 files (`immutablePrimitiveObjectEmptyMap.stg`, `immutablePrimitiveObjectEmptyMapTest.stg`).

**Comment by itohro** [comment]
Yes, that's right.

**Comment by motlin** [comment]
@opengl-8080 I'm very much looking forward to using default methods, but it's still good to start out without using them and adding them later. That way we have compiler errors to follow. They remind me to override methods in the synchronized wrappers, for example. If I only implement a default method in RichIterable, everything compiles but the synchronized wrappers are no longer thread safe.

For this reason, when we do add default methods, I think they should be in new interfaces, or we should convert AbstractRichIterable from a class to an interface, rather than add default methods in RichIterable.

**Comment by opengl-8080** [comment]
I see.
Just yesterday, I could notice synchronized class (`AbstractSynchronizedRichIterable`) by compile error.

**Comment by opengl-8080** [comment]
When iterable doesn't have only one item. Should `getOnly()` method throw `IllegalArgumentException`?

I think it should throw `IllegalStateException`.
Because, occurring error is caused by iterable's state (it doesn't have only one item).

**Comment by itohro** [comment]
Agree, throwing `IllegalStateException` sounds to make sense here. I think you could refactor existing `IterableIterate.getOnly()` to do so, too.

@motlin what do you think?

**Comment by motlin** [comment]
In `IterableIterate`, the iterable is passed in as an argument, so `IllegalArgumentException` or `IllegalStateException` can both makes sense. I don't have a strong opinion on whether we should change the existing behavior. In `RichIterable` I agree that `IllegalStateException` makes sense.

**Comment by itohro** [comment]
Ah I see, that's true. We can keep `IterableIterate` throw `IllegalArgumentException` then. 

Let's make `RichIterable` throw `IllegalStateException`.

**Comment by opengl-8080** [comment]
`AbstractCollectionAdapter` is implemented by following.

```java
public T getFirst()
{
    return Iterate.getFirst(this.getDelegate());
}

public T getLast()
{
    return Iterate.getLast(this.getDelegate());
}
```


If to implement `getOnly()` method using `Iterate.getOnly()`, `AbstractCollectionAdapter.getOnly()` throws `IllegalArgumentException` (`Iterate.getOnly()` uses `IterableIterate.getOnly()`). 


Must I implement `getOnly()` method of `AbstractCollectionAdapter` without `Iterate.getOnly()`?

For example...

**AbstractcollectionAdapter.java**

```java
public T getOnly()
{
    Collection<T> delegate = this.getDelegate();

    if (delegate == null)
    {
        throw new NullPointerException("Cannot get item from null.");
    }

    Iterator<T> iterator = delegate.iterator();

    if (!iterator.hasNext())
    {
        throw new IllegalStateException("Iterable is empty.");
    }

    T result = iterator.next();
    if (iterator.hasNext())
    {
        throw new IllegalStateException("Iterable has multiple values");
    }

    return result;
}
```

**Comment by itohro** [comment]
Thanks @opengl-8080 , your suggestion makes sense to me.

**Comment by motlin** [comment]
I think that the delegate cannot be null and doesn't need to be checked against null. Besides that, yes, looks good.

**Comment by opengl-8080** [comment]
I see.
So I remove null check, and I get `Iterator` from delegate directly.
Thanks!
