### ISSUE TITLE
Issues while importing code in eclipse

### ISSUE THREAD

**Issue by rakotkar** [eclipse/eclipse-collections#882]
While trying to import the code that I cloned from https://github.com/eclipse/eclipse-collections    .

I got below error.

![image](https://user-images.githubusercontent.com/43616363/81698479-a9e1de00-9483-11ea-8787-3e5458fdc435.png)

I followed the instructions as mentioned  https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md
I am using java 11 on Ubuntu 20.04.

Also , Do we have some instructions for windows as while tried to build on windows, as on windows 10 , (JDK 1.8.0_241) I got checktyle errors.

**Comment by nikhilnanivadekar** [comment]
I would say don’t worry about checkstyle as we run them in GitHub actions and other builds. You can try running clean verify or clean install. These should not run checkstyle. If they still run, turn off the checkstyle profile.

**Comment by rakotkar** [comment]
Sure , I will do that. How about the compilation error (kindly see the screen shot).I can fix that but wanted to know if that's an issue .

**Comment by nikhilnanivadekar** [comment]
That seems to be an eclipse specific issue or may be a bug. Can you check if the maven build is running fine? And the project compiles via maven?

**Comment by rakotkar** [comment]
Maven build is successful , yet I see compilation issues in eclipse.

**Comment by nikhilnanivadekar** [comment]
@leomrlima can you please help?

**Comment by leomrlima** [comment]
This error seems to come from Eclipse IDE using Eclipse compiler. I don't know who is right - if Eclipse Compiler enforces something that doesn't make sense, or is the only compiler that enforces this.

I've created a fix for the generated classes, that would allow it to be built - https://github.com/eclipse/eclipse-collections/pull/903

**Comment by leomrlima** [comment]
I’m sorry I can’t. 

It’s an error with either the Eclipse Compiler or other compilers. There are multiple ways to fix the generated code if you wish to.

**Comment by kedar-joshi** [comment]
Even IntelliJ complains about the very same line. This is because the implementation is expected to return `ImmutableList<V>` but it actually returns `ImmutableList<? extends V>`. Collections are not automatically assignable this way and require explicit cast to `ImmutableList<? extends V>`.

![image](https://user-images.githubusercontent.com/13585883/87187013-1c4b2f00-c30a-11ea-8b85-777a32f01dbf.png)

For example,

```java
public class Parent { }

public class Child extends Parent { }

public static void main(final String[] args)
	public static void main(final String[] args)
{
	// This is ok
	final List<? extends Parent> children = getChildren();

	// java: incompatible types: java.util.List<Child> cannot be converted to java.util.List<Parent>
	final List<Parent> parents = getChildren();

	// This is ok
	final List<Parent> parentList = (List<Parent>) getChildren();
}

private static List<? extends Parent> getChildren()
{
	return new ArrayList<>();
}

```

**Comment by donraab** [comment]
Thanks @kedar-joshi , I think if you give the compiler a type hint it will fix this kind of issue. This happens unfortunately when a static method is followed by an instance. Javac seems to be fine with it, but IntelliJ and ECJ seem to not be.

Adding this to the line should be good enough:

`FastList.<V>newListWith(...`

This should be fixed now in the latest version of the code. I submitted a PR fixing a separate unrelated efficiency problem with this code that has the added benefit of removing the problem.

https://github.com/eclipse/eclipse-collections/pull/926

**Comment by nikhilnanivadekar** [comment]
@kedar-joshi , @rakotkar with the updated code is this still an issue?

**Comment by kedar-joshi** [comment]
> @kedar-joshi , @rakotkar with the updated code is this still an issue?

No. Current version is all green. No compiler error. 👍

**Comment by nikhilnanivadekar** [comment]
Thanks @kedar-joshi  for the confirmation. Closing this issue.
