### ISSUE TITLE
Disable maven download progress in Unit Tests GitHub Actions

### ISSUE THREAD

**Issue by prathasirisha** [eclipse/eclipse-collections#886]
Add this to `--no-transfer-progress` in [unit.yml](https://github.com/eclipse/eclipse-collections/blob/master/.github/workflows/unit.yml). Link for [Unit Test Action Log](https://github.com/eclipse/eclipse-collections/actions/runs/106990509)

Compare it to other GitHub Actions Workflows [Acceptance Tests](https://github.com/eclipse/eclipse-collections/blob/master/.github/workflows/acceptance.yml), [Performance Tests](https://github.com/eclipse/eclipse-collections/blob/master/.github/workflows/performance.yml)

Compare it to Travis Builds for Unit Tests for jdk 11, jdk 14 and openjdk-ea. [Link](https://github.com/eclipse/eclipse-collections/blob/master/.travis.yml)

**Comment by motlin** [comment]
consider moving into .mvn/maven.config

**Comment by prathasirisha** [comment]
Hi @donraab - would like to work on this. Can you please assign it to me?

**Comment by donraab** [comment]
Done. Thanks @prathasirisha !
