### ISSUE TITLE
Code generate BooleanArrayStack from the common template

### ISSUE THREAD

**Issue by vmzakharov** [eclipse/eclipse-collections#888]
Currently `BooleanArrayStack` is the only primitive stack implementation that is not generated. Generating `BooleanArrayStack` from `primitveArrayStack.stg` will reduce the amount of duplicate code needed to be maintained in the framework. 

Unlike `BooleanArrayList`, which uses an underlying implementation different from other primitive lists (`BitSet` based rather than an array based), `BooleanArrayStack` implementation appears to be consistent with other primitive stacks. The only difference, inherited from the `BooleanIterable` API, is the absence of the `toSortedList()` method, which will be easy to exclude from the primitive array stack template just for the Boolean type. This approach to include/exclude certain behaviors is already implemented in other templates.

**Comment by donraab** [comment]
I can't see any reasons not to do this. You may need to specialize the hashCode implementation.

**Comment by vmzakharov** [comment]
The only difference between the `hashCode()` implementations, as far as I can tell, is the use of a for loop in the handcoded version vs. an iterator in the code generated one to iterate over the stack elements. Any concerns around using the iterator?

**Comment by donraab** [comment]
I see. I didn't realize there was an `AbstractBooleanStack` that `BooleanArrayStack` overrides.

`BooleanArrayStack:
`
```
@Override
public int hashCode()
{
    int hashCode = 1;
    for (int i = this.size() - 1; i >= 0; i--)
    {
        boolean item = this.delegate.get(i);
        hashCode = 31 * hashCode + (item ? 1231 : 1237);
    }
    return hashCode;
}
```

`AbstractBooleanStack`:

@Override
```
public int hashCode()
{
    int hashCode = 1;
    BooleanIterable iterable = this.getDelegate().asReversed();
    BooleanIterator iterator = iterable.booleanIterator();
    while (iterator.hasNext())
    {
        boolean item = iterator.next();
        hashCode = 31 * hashCode + (item ? 1231 : 1237);
    }
    return hashCode;
}

```

**Comment by mohrezaei** [comment]
I would strongly recommend/prefer removing the iterator. `hashCode()` implementations that create garbage can lead to serious issues (e.g. terrabytes of temporary garbage on a rehash).

**Comment by vmzakharov** [comment]
So since in all cases a delegate used to iterate over is actually a primitive ArrayList it should be OK to make the common implementation iterator-less.
