### ISSUE TITLE
Implement Null Safe Comparator By Function

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#890]
Consider an object
```
public class Person
{
  private int age;
  private String firstName;
}

```
We have Comparators and Functions which are null-safe on their own, we need a comparator which brings null safety to the computed value.

Failing Test
```

MutableList<Person> people = Lists.mutable.empty();
Person p1 = new Person();
p1.setFirstName("A");
Person p2 = new Person();
p2.setFirstName("B");

people.sortThis(Comparators.byFunction(Person::getAge)); // Throws an NPE

We need something like
people.sortThis(Comparators.nullSafeValue(Person::getAge)) // the value returned after evaluating getAge() should be checked
```

**Comment by vmzakharov** [comment]
(Assuming in this example the int should be a big Integer) Then looks like something like this will do the trick:
```
    private class Person
    {
        private Integer numberOfWafflesCanEatInOneSeating;
        private String name;
        <getters, setters, etc.>
    }
```
This test passes
```
   public void sortByNullValues()
    {
        Person p1 = new Person();
        p1.setName(\"Alice\");
        Person p2 = new Person();
        p2.setName("Bob");
        p2.setNumberOfWafflesCanEatInOneSeating(2);
        Person p3 = new Person();
        p3.setName("Carol");

        MutableList<Person> people = Lists.mutable.with(p1, p2, p3);

        people.sortThis(Comparators.byFunction(
                Person::getNumberOfWafflesCanEatInOneSeating,
                Comparators.safeNullsLow(Comparators.naturalOrder())));

        Verify.assertIterablesEqual(Lists.immutable.of(p1, p3, p2), people);
    }
```
Would a method in `Comparators` that returns 
`Comparators.byFunction(<function>, Comparators.safeNullsLow(Comparators.naturalOrder()))` 
suffice then? Also do we want to support both nulls low and nulls high options? (I suspect, yes)

**Comment by nikhilnanivadekar** [comment]
We already have nulls high. So yes :)

**Comment by vmzakharov** [comment]
"Yes" to both questions? 😃

**Comment by motlin** [comment]
In addition to our methods on `Comparators`, similar methods exist on `java.util.Comparator`

**Comment by vmzakharov** [comment]
My implementation uses the ones on EC `Comparators`, is there any reason to prefer `java.util.Comparator` ones?

**Comment by motlin** [comment]
I think unless there is a material difference, we should prefer stuff that's built in. In this case something like:

```
Comparator.comparing(
                Function.identity(),
                Comparator.nullsFirst(Comparator.naturalOrder()))
```

We've replaced some of the insides of the Comparators class with delegation to Comparator. I'd like to do more of that, and possibly add some deprecation (not for removal)

**Comment by motlin** [comment]
I'm looking and it's tricky to actually replace our stuff with the built in stuff because we use the interface `SerializableComparator`. The built in Comparators are all serializable, but don't implement an interface other than `Comparator`.

So I think I'd like to add deprecation (not for removal) with pointers to the new stuff in Comparator and that's all. The only thing I see that EC has that's not built in is ascendingCollectionSizeComparator/descendingCollectionSizeComparator, but I'd still prefer `nestedCollections.sortThis(Comparator.<Collection<?>, Integer>comparing(Collection::size).reversed());` or `nestedCollections.sortThisByInt(RichIterable::size)`

**Comment by vmzakharov** [comment]
@motlin - would it be then a separate issue to mark some factory methods on EC Comparators as deprecated?
