### ISSUE TITLE
Optimize IntInterval sum(), mean() and  average() methods to use direct formulas

### ISSUE THREAD

**Issue by vmzakharov** [eclipse/eclipse-collections#892]
Currently the `sum()`, `mean()` and ` average()` methods on `IntInterval` use a brute force approach involving collection materialization and iteration based algorithms.
Using direct formulas for `mean()` and `average()`, e.g. `(first + last)/2.0`,  and  `sum()`, e.g. `size * ((first + last) / 2.0)` will eliminate unnecessary object creation (arrays and iterators)  and improve performance.

**Comment by mohrezaei** [comment]
`sum(p..q) = (q*(q+1) - p*(p+1))/2 = (q-p)*(q+p+1)/2` if `p >= 0, q >= 0`

`sum(p..q) = - sum(abs(p)..abs(q))` if `p < 0, q < 0`

`sum(p..q) = sum(0..q) - sum(0..abs(p))` if `p < 0, q > 0`

steps make this harder (need to compute actual number of steps).

Things get very hairy near `MAX` values.

**Comment by vmzakharov** [comment]
I added tests to the existing ones for these methods in `IntIntervalTest`, would you suggest any additional tests?

**Comment by mohrezaei** [comment]
I was confused by the `size` `step` thing. Sorry, the formula is good (corrected in my comment above). I would just add a test from negative to positive.

**Comment by vmzakharov** [comment]
Thank you. I have that test for `sum()` :

`        Assert.assertEquals(-7L, IntInterval.fromToBy(-10, 10, 3).sum());`

**Comment by mohrezaei** [comment]
Ugh. I was clicking on the first commit (thinking it's a PR, not a branch commit). All good. I assume you're going to make it a PR...

**Comment by vmzakharov** [comment]
https://github.com/eclipse/eclipse-collections/pull/893
