### ISSUE TITLE
Support sorting of primitive lists by indirect comparison.

### ISSUE THREAD

**Issue by vmzakharov** [eclipse/eclipse-collections#908]
The proposal is to add the following APIs on PrimitiveLists (in addition to the existing `sortThis()`):
- `PrimitiveList sortThis(PrimitiveComparator comparator)`
- `<T> PrimitiveList sortThisBy(PrimitiveFunction<T> keyExtractor) // sorts by the natural order of the keys`
- `<T> PrimitiveList sortThisBy(PrimitiveFunction<T> keyExtractor, Comparator<? super T> keyComparator)`

Where `PrimitiveComparator` is a Single Abstract Method interface that looks like
```
public interface PrimitiveComparator
{
    int compare(primitive value1, primitive value2);
}
```
To support this a new sort implementation will be required.

**Comment by nikhilnanivadekar** [comment]
This looks fine as a starting point. Please raise a PR. Thanks!
