### ISSUE TITLE
Add methods to primitive List and Set factories to create empty collections with an initial capacity.

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#920]
```
IntLists.mutable.withInitialCapacity(int)
IntSets.mutable.withInitialCapacity(int)
```

**Comment by fipro78** [comment]
I am trying to add this to the templates. Hopefully I got the right files, as everything are templates and I have no idea what an .stg file is or what is used for the code generation. Never worked in that area. Also importing, building and performing a Maven Update in the IDE does not solve all errors. Seems there are still some Scala related issues that I do not really understand. The setup description does not help.

Well I think I got the starting points working somehow. But there are issues with BooleanHashSet, which is not generated and does not have a constructor that takes an initialCapacity. And I don't know how to add that as I don't understand the internals of this class. Also the ByteHashSet has deprecated the constructor with initialCapacity constructor. Is there a reason why?

**Comment by donraab** [comment]
Hi @fipro78, I need to get the details of the following answer into docs. We use StringTemplate for code generation.

https://stackoverflow.com/questions/61386226/resources-for-understanding-fastutil-internals/61400271#61400271

I'll try and take a look at your other questions this weekend.

**Comment by donraab** [comment]
Hi @fipro78, following up on your other questions. BooleanHashSet will have at most 4 potential states. Empty, true, false, true & false so there is no need to construct with an initialCapacity. ByteHashSet is implemented via four longs, so the constructor is there and deprecated as there would no effect to the size or growth by specifying the initial capacity.

**Comment by fipro78** [comment]
Hi @donraab, thanks for the reply. Do you have an idea how to handle this in the template? For example a statement to not generate the factory method for boolean and byte?

**Comment by donraab** [comment]
Hi @fipro78, there is a way to do this. I haven't done it in quite a while so I would need to scan the other templates to see how to do this. @motlin @nikhilnanivadekar do you recall off hand an example for excluding certain sections for certain types in template files?

**Comment by nikhilnanivadekar** [comment]
Stg templates support ‘if’ statements. So you can do that. I am AFK right now but can paste the syntax later today.

**Comment by donraab** [comment]
Hi @fipro78, in `mutablePrimitiveSetFactory.stg` which you would need to add to, you can see examples of conditionally generating stream methods for int, long and double but excluding other types.

**Comment by fipro78** [comment]
Thanks, I will try to adapt this and prepare a pull request soon.

**Comment by nikhilnanivadekar** [comment]
Thanks! Would you mind telling us the troubles during your initial setup you had? It’s been ages since we setup the project from scratch. So whatever issues you had we can cover the fixes in the setup steps. Thank you!

**Comment by fipro78** [comment]
Sure. I am using a eclipse committers ide. I cloned the project via EGit and imported the projects as maven projects. This gave the first errors which I could solve by closing the ide and running the mvn clean verify command. BTW mvnw seems to be not available on my windows machine. But I did not use the Maven wrapper before, so not sure what is wrong here. Then I opened the ide again and had to update the Maven dependencies on all projects to solve the previous issues. But still I have compile errors for some classes. Maybe a Scala issue? Are there any plugins required to be installed into the ide to make all the code compile?

**Comment by donraab** [comment]
Hi @fipro78, I believe there are type inference issues in with the Eclipse Compiler in the Eclipse IDE in the following files:

immutablePrimitiveSingletonBag.stg (line 220)
immutablePrimitiveSingletonList.stg (line 179)

You should be able to fix this by changing the code in these templates to include a type inference hint as follows:

HashBag.\<V>newBagWith
FastList.\<V>newListWith

This issue was discovered by @leomrlima (Thank you Leo!) and was determined to be fixable via an explicit cast. We like to avoid explicit casts in the code base if possible, and I believe the type inference hint above should work. If you can verify this works in Eclipse IDE that would be great

**Comment by fipro78** [comment]
Hi @donraab, thanks for the pointer. That solved some of the issues. But I still get several errors in jmh-tests that several classes can not be resolved (e.g. AnagramSetScalaTest, AnySatisfyScalaTest, ...). I closed that project for now to resolve the errors in the workspace.

**Comment by nikhilnanivadekar** [comment]
@fipro78 our default profile skips JMH and Scala modules. It might be a Eclipse artifact that these modules are also getting opened.
You are the 2nd person to report that the maven wrapper is not available. @motlin can you please verify if maven wrapper is working fine, and what we are missing in the instructions. Thank you!

**Comment by nikhilnanivadekar** [comment]
Closed via https://github.com/eclipse/eclipse-collections/pull/922

**Comment by fipro78** [comment]
> @fipro78 our default profile skips JMH and Scala modules. It might be a Eclipse artifact that these modules are also getting opened.
> You are the 2nd person to report that the maven wrapper is not available. @motlin can you please verify if maven wrapper is working fine, and what we are missing in the instructions. Thank you!

Correct me if I am wrong. But shouldn't the Maven Wrapper be part of the repository. There is no mvnw script in this repository, so why should the wrapper work? Or should it be generated by the build script somehow? Because it isn't on my Windows machine.

**Comment by motlin** [comment]
> > @fipro78 our default profile skips JMH and Scala modules. It might be a Eclipse artifact that these modules are also getting opened.
> 
> > You are the 2nd person to report that the maven wrapper is not available. @motlin can you please verify if maven wrapper is working fine, and what we are missing in the instructions. Thank you!
> 
> 
> 
> Correct me if I am wrong. But shouldn't the Maven Wrapper be part of the repository. There is no mvnw script in this repository, so why should the wrapper work? Or should it be generated by the build script somehow? Because it isn't on my Windows machine.

Adding mvnw:
https://github.com/eclipse/eclipse-collections/pull/928
