### ISSUE TITLE
Incorrect feature version in p2 repository

### ISSUE THREAD

**Issue by fipro78** [eclipse/eclipse-collections#923]
When loading the p2 repository https://download.eclipse.org/collections/10.2.0/repository the feature version is shown as 10.1.0.v20200211-1558. I suppose it was missed to update the version in the p2 project pom.xml files. Is that correct or are there any additional places where the incorrect version could be?

I suppose this can't be fixed for 10.2 as it is already released. But for the next 10.3 it should be updated accordingly.

**Comment by nikhilnanivadekar** [comment]
I remember fixing this for 10.2.0 itself but might have missed something. I am going to create a 10.3.0 milestone release today, so will it be possible to test it out for 10.3.0 milestone? I’ll ping here once the release is published.

**Comment by fipro78** [comment]
Just let me know once you are ready and I will give it a try. I thought the issue might be in p2-feature pom.xml files which still show version 10.1.0.

**Comment by nikhilnanivadekar** [comment]
Would you like to raise a PR with that fix? I’ll merge it before the milestone.

**Comment by fipro78** [comment]
Raised the PR https://github.com/eclipse/eclipse-collections/pull/924

Not sure if everything is correct. The build succeeded locally, but I can't find the resulting p2 repo like it would look like on the release. But I think updating the pom.xml (maybe not necessary) and updating the feature.xml and the category.xml should be correct.

**Comment by nikhilnanivadekar** [comment]
merged. I have 1 more change before which I can start a milestone release. I should be able to get to it by late night US hours. Thanks for your help!

**Comment by nikhilnanivadekar** [comment]
I was finally able to release milestone. There were issues with Jenkins. Can you please take a look if things are fine?

**Comment by fipro78** [comment]
I added this URL to install new software:

https://download.eclipse.org/collections/10.3.0.M1/repository/

It now shows the "Uncategorized" category. And in that category there is a "Eclipse Collections Developer Resources" feature to install. But it now shows the correct version 10.3.0.v20200703-1238.

Not sure about the category and the plugin name, but the version is correct now.

BTW, you can simply test this by trying to install new software in an Eclipse IDE. :)

**Comment by nikhilnanivadekar** [comment]
@fipro78 none of us maintainers are well versed with the Eclipse ecosystem around plugins and categories. So, your direction and help will be invaluable. Thanks a lot for your help!

What do you mean by the URL to install new software? I dont even know how the url gets generated, and how it is sourced. I apologize for my lack of knowledge!

**Comment by fipro78** [comment]
I will have a look at the build for the p2 stuff the next days. Maybe I see something. But I wonder what has changed between 10.2 and the 10.3 milestone that causes this change.

If you have an Eclipse IDE installed, you can install additional plugins via Help - Install new software. There you can enter the URL I posted which points to your p2 repository. But how in detail you create and publish it I don't know yet. 

No need to apologize. We all learn something new every day. :)

**Comment by fipro78** [comment]
@nikhilnanivadekar 
When I build locally a p2 repository is generated using the ebr plugin below **p2-repository/org.eclipse.collections/target/repository**
If I am using that location as update site in my Eclipse, I see a category named "Eclipse Collections OSGi Bundle" that contains two feature entries "Eclipse Collections Main Library" and "Eclipse Collections Main Library Source". IMHO that looks correct. But it only contains the plugins, there is no feature.
So at some time someone created the p2-feature structure that consumes the p2-repository, builds a feature on top and creates a new update site based on the feature. That one only contains the "Developer Resources" feature, which is a combination of the main feature in combination with the sources. But there is no way to only consume the code feature only to avoid adding the sources to my product. And also the category link between the feature and the category definition is incorrect.

I guess that in your publishing process you are running the p2-feature build (which is not part of the default build, probably because of the signing process that is enabled always in that build). And you then publish the result in **p2-feature/org.eclipse.collections.repository/target/repository** to download.eclipse.org. But I don't know about your release process and the build servers, so it is just an assumption. Hopefully you can see that somewhere as I don't have access to your Jenkins jobs (I guess).

I also noticed that the API and IMPL jars that you publish to Maven Central do not contain OSGi metadata. So it is actually not consumeable by OSGi projects that are not based on p2.

I created PR #940 that hopefully fixes the issue with the p2 update site AND adds the OSGi metadata in advance so it is also available from Maven Central.

**Comment by nikhilnanivadekar** [comment]
@fipro78 thanks for the PR. I saw that @motlin gave a few comments on there. Can you please fix them?

**Comment by fipro78** [comment]
> @fipro78 thanks for the PR. I saw that @motlin gave a few comments on there. Can you please fix them?

I am working on it. Still trying to find out why my change causes the api bundles to be included in the collections bundle.

BTW, @nikhilnanivadekar and @motlin, are you aware that org\eclipse\collections\impl\utility\primitive\ is part of the api since 10.3.0? There was no such package in 10.2. Is it really intended to have the sort implementations as part of the API?

**Comment by fipro78** [comment]
I updated the PR. Thanks to @peterkir who helped me fixing the bnd issue

**Comment by fipro78** [comment]
Hi @nikhilnanivadekar, @motlin, @donraab,

I have a question with regards to API vs. IMPL. From a clean perspective I would assume that consumers of Eclipse Collections should only implement against the API and the IMPL should be hidden. Is that the approach that should be taken? Because actually the OSGi Manifest of the IMPL should not export any impl packages and specify them as Private-Package. Right now I have configured it to export those packages so they can be consumed from the outside. What is the preference of the project?

**Comment by motlin** [comment]
Today, impl must be public. We've gradually made the library more usable
through api only, including the dynamic loading of the impl jar at runtime
from the collection factories. Some users will be able to use api only.
However, there is still quite a bit of functionality not exposed through
the interfaces in the api package.

**Comment by nikhilnanivadekar** [comment]
This seems to be partially fixed by #940 

but the p2 build is failing: https://ci.eclipse.org/collections/job/publish-p2-repo/31/console

**Comment by fipro78** [comment]
@nikhilnanivadekar 

I am currently not at home, but it looks like the version in the pom.xml files below p2-feature need to be updated. Seems I missed those :(

**Comment by fipro78** [comment]
@nikhilnanivadekar 

I have created PR #952 which should fix the p2 build.

**Comment by nikhilnanivadekar** [comment]
@fipro78 10.3.0.M3 is pushed to p2. Can you please verify?

**Comment by fipro78** [comment]
The p2 update site now looks good to me. The category is named "Eclipse Collections", there are two features below, one for the code and one for the sources, and the version is 10.3.0.v20200715-1741

**Comment by nikhilnanivadekar** [comment]
Awesome! Thanks a ton!

**Comment by nikhilnanivadekar** [comment]
@fipro78 10.3.0.M4 is pushed to p2. Can you please check? Thanks!

**Comment by fipro78** [comment]
@nikhilnanivadekar 
I have tested to consume the M4 p2 repository in NatTable and it works as intended. Also the format of the p2 update site shown in the Install New Software dialog looks good with regards to available features, category and feature version.

I also tested consuming the M4 artefacts in a plain OSGi Maven project. And this also works as intended now.

**Comment by donraab** [comment]
Thank you for helping us fix this issue and validating things are working properly @fipro78. This is very much appreciated!

**Comment by nikhilnanivadekar** [comment]
Thanks a ton @fipro78 for your help! If I may ask, so that next release we don’t have to do this again, would you mind giving the steps which I should follow when I create a new release so that p2 remains in good shape? I will update our wiki with that so that it is followed properly. Thanks again!

**Comment by fipro78** [comment]
I can try :)

1. p2-repository is included in the default build and creates a p2 repository using the Eclipse Bundle Recipes. This repository only contains the bundle and is actually not published by you.
2. p2-feature is a separate build that consumes the p2-repository build result. It creates a feature and an update site that contains the Eclipse Collections feature.

From what I have seen, p2-repository is already updated by your default jobs. p2-feature currently not.

In p2-feature you need to:

- Update the version in the pom.xml files (not sure why I had to do this manually and it was not picked up by your jobs already, or why it was reverted somehow, as I can see in the history that I contributed that change twice)
- In p2-feature/org.eclipse.collections.feature/feature.xml update the version in the feature tag to match the release
- In p2-feature/org.eclipse.collections.repository/category.xml you need to update the version in the url and version attributes of the feature tag to match the release

With the other changes now in place, IMHO you only need to take care of the feature.xml and the category.xml file. At least if the pom.xml version updates work automatically.

Feel free to ping me on the next release when you have done the changes. I can then verify if things look like expected.

Glad I could help here! :)

**Comment by fipro78** [comment]
@nikhilnanivadekar 
Does my explanation make sense? Or do you have some questions?

**Comment by nikhilnanivadekar** [comment]
@fipro78 yes it does. For some reason, I missed your previous comment. Thanks for the reminder. 
I will be creating a final milestone for 10.3.0 this week. If that checks out fine, then will do the release for 10.3.0 next week.
Thanks for your help!

**Comment by nikhilnanivadekar** [comment]
@fipro78 I have pushed 10.3.0.M5 to p2 repo. Can you please test it and confirm?
If it looks good, will do the final release either this weekend or next week depending on available time.

**Comment by fipro78** [comment]
@nikhilnanivadekar 
10.3.0.M5 p2 repo looks good

**Comment by nikhilnanivadekar** [comment]
Awesome!

**Comment by nikhilnanivadekar** [comment]
@fipro78 I have released 10.4.0, can you please take a look if it works?
If it works I will also create a 11.0.0.M1 to confirm that p2 version issues are resolved. Then we can close this issue.

Thanks for your help!

**Comment by nikhilnanivadekar** [comment]
@fipro78 I downloaded it via Eclipse and it seemed to work fine. Please reopen or raise a new issue if you encounter the same issue.
Thanks a ton for helping to improve the quality of Eclipse Collections!
