### ISSUE TITLE
Create two part implementation jars

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#937]
A common complaint about Eclipse Collections is that it is very large (~10 MB). I think we can alleviate some of this pain by creating two additional implementation jars, in addition to the uber implementation jar we create today.

What I would propose is that the two jars contain the following:

Jar 1:

- All Object Collections, Maps, Multimaps, BiMaps
- All Primitive Lists, Sets, Bags
- Object Int Maps (needed for Object Bag implementations)
- Primitive Int Maps (needed for primitive Bag implementations)

Jar 2

- All other primitive Maps

**Comment by mohrezaei** [comment]
Doesn't this come from the Android side? Isn't the right solution to be more proguard/android build friendly?

Honestly, on the server side, 10MB is peanuts.

**Comment by donraab** [comment]
I've heard the complaint more recently in terms of Docker image sizes concerns.

**Comment by mohrezaei** [comment]
I just looked at a production fat jar and here is what I see:
Compressed size 63MB
Eclipse collection about 9 MB (so about 14%).
Application code 5 MB
Rest of the libs: 49 MB

This project would need both jars, so no help there. Even if it didn't, would it help to reduce the size by 10% or so? Very debatable.

I'm not a docker guru, but googling around returned tiny docker image sizes > 60MB (optimized hello world), and often into the hundreds of MB. Complaints seem to start with 1 GB and higher. The above production docker images are 900MB, so a 9MB reduction is peanuts.

If we're going to do this, it should be for a good reason...

**Comment by donraab** [comment]
Agreed. Wanted to float the idea regardless. 

Interested to hear thoughts from @motlin @nikhilnanivadekar and anyone else who has to build apps. Do you ever exclude Eclipse Collections because of jar size?

**Comment by motlin** [comment]
I think about the size of Eclipse Collections because it's a big library with a lot to learn, and one of the arguments I hear against EC is that it's "overkill" compared to Guava or Streams. I also think about the size because I wait for its build which has gotten longer over the years. The size in MB doesn't cause me problems.

**Comment by nikhilnanivadekar** [comment]
I think this change is very low reward for a huge amount of effort. I agree with @mohrezaei that a 9 MB * 2 (impl and api) jars are not much of a footprint. That said, it would be good to try and see if we need the API and impl as 2 separate jars. 
Breaking the impl jar in two will cause more maintenance work as well.

**Comment by donraab** [comment]
ok, I'll close the issue.
