### ISSUE TITLE
org/eclipse/collections/impl/utility/primitive package in API

### ISSUE THREAD

**Issue by fipro78** [eclipse/eclipse-collections#949]
While adding the OSGi meta-data I noticed that since 10.3.0 the package org/eclipse/collections/impl/utility/primitive is included in the API jar. It did not exist before.

This actually even creates an OSGi dependency issue because two bundles export the same package. You can see this via the bnd-maven-plugin warning:

Split package, multiple jars provide the same package:org/eclipse/collections/impl/utility/primitive

IMHO the api bundle should not contain any impl packages.

**Comment by nikhilnanivadekar** [comment]
@fipro78 you are the expert here. So we will go with your expertise, and suggestions of how to fix it.

**Comment by donraab** [comment]
I think this is probably the quick sort utility introduced by @vmzakharov.  I just looked and this is only referenced from impl classes so should be moved to impl. Not sure why it wound up in api module. It may have been due to the earlier implementation in default methods.
