### ISSUE TITLE
Implement MapIterable.getOrDefault(java.lang.Object o, V v)

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#956]
```
default V getOrDefault(Object o, V v)
{
    this.getIfAbsentValue(o, v);
}
```

**Comment by anupyadavrpvv** [comment]
I would like to help. @nikhilnanivadekar would you mind describing the issue and possible solution so that I can work on it accordingly?

**Comment by nikhilnanivadekar** [comment]
Thanks @anupyadavrpvv I have assigned this to you.
The implementation can be a default method which delegates to getIfAbsent()

**Comment by anupyadavrpvv** [comment]
Thank you @nikhilnanivadekar for assigning this task to me.
I would be glad if you help me out through the process, as this is my very first open project contribution.

**Comment by donraab** [comment]
> Thanks @anupyadavrpvv I have assigned this to you.
> The implementation can be a default method which delegates to getIfAbsent()

@nikhilnanivadekar There is a method named getIfAbsentValue on MapIterable. What is the proposed signature for getOrDefault and the result type?

**Comment by nikhilnanivadekar** [comment]
It will be the same as JDK Map API’s signature. This is to ensure we delegate the JDK Map API correctly and provide it at the highest interface

**Comment by donraab** [comment]
Ok, understood. It is already a default method on `Map`. It should be able to just delegate to `getIfAbsentValue` right?

**Comment by nikhilnanivadekar** [comment]
Yup exactly!

**Comment by nikhilnanivadekar** [comment]
@anupyadavrpvv please follow the instructions on this document to setup your environment: https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md

I have updated the PR with the correct signature.

The API will be implemented as a default method on MapIterable. MapIterable already has another API called `getIfAbsentValue()` . The implementation of `getOrDefault()` should simply delegate (call) the already existing `getIfAbsentValue()` method.

**Comment by anupyadavrpvv** [comment]
Hey @nikhilnanivadekar, I am done with the environment setup thanks to you.
Now what I have understood till now that I need to create a default method name getOrDefault() which calls the getIfAbsentValue() method like:
default V getOrDefault(arguments){
     getIfAbsentValue(pass the above arguments);
}
Is it correct?
Tell me about your suggestions which will help me.

**Comment by nikhilnanivadekar** [comment]
Yes. I have updated the PR description above with the implementation. You need to add tests as well. So refer to the tests of getIfAbsentValue() for the tests.

**Comment by anupyadavrpvv** [comment]
Hey @nikhilnanivadekar 
I didn't want to give up on this project but I am having a lot of trouble in understanding and writing test cases as I don't have any experience in writing test cases. It may be because of my lack of experience ( this is my very first attempt to solve an open-source problem as a student). I really need someone who can tell me what to do how to do it? But I know this might be difficult for you to help me at every step. I spent my whole day on it but got only warnings and errors.
So you can assign it to someone else because if I work on it I'll really need a mentor who can guide me at every step.
Sorry! I didn't stand on your expectations. I still need a lot to learn.

**Comment by nikhilnanivadekar** [comment]
@anupyadavrpvv let see if this helps, if you still have issues, dont worry, I will take it up from here.

The test is going to be exactly same as this:
https://github.com/eclipse/eclipse-collections/blob/master/unit-tests/src/test/java/org/eclipse/collections/impl/map/MapIterableTestCase.java#L194

**Comment by anupyadavrpvv** [comment]
@nikhilnanivadekar Thanks for all your help
let me show you what I am doing and how should I correct it.
I have created this method in Mapiterable interface:
default V getOrDefault(Object o, V v)
    {
        return this.getIfAbsentValue((K) o, v);
    }
then any copy-pasted the test you have mentioned 
@Test
    public void getOrDefault()
    {
        MapIterable<Integer, String> map = this.newMapWithKeysValues(1, "1", 2, "2", 3, "3");
        Assert.assertNull(map.get(4));
        Assert.assertEquals("4", map.getIfAbsentValue(4, "4"));
        Assert.assertEquals("3", map.getIfAbsentValue(3, "3"));
        Assert.assertNull(map.get(4));
    }
when I run these cases I got these errors:
Error:(40, 8) java: interface org.eclipse.collections.api.map.MutableMapIterable<K,V> inherits unrelated defaults for getOrDefault(java.lang.Object,V) from types org.eclipse.collections.api.map.MapIterable and java.util.Map

Error:(51, 8) java: interface org.eclipse.collections.api.map.MutableMap<K,V> inherits unrelated defaults for getOrDefault(java.lang.Object,V) from types java.util.Map and org.eclipse.collections.api.map.MapIterable

and 6 more of the same type please tell me what am I doing wrong.
Thanks In Advance 

Also, I wanted to know from where I need to call getOrDefault()  which always show it is never used.

**Comment by nikhilnanivadekar** [comment]
This happens because MutableMapIterable extends Map. Can you add the same default method on MutableMapIterable? I would say research a little bit of Java inheritance concepts.

**Comment by anupyadavrpvv** [comment]
@nikhilnanivadekar Please un-assign me because I am stuck with lots of errors.
 I am really looking forward to seeing the correct solution.
Sorry for all the trouble.

**Comment by nikhilnanivadekar** [comment]
@anupyadavrpvv take a look at the PR: https://github.com/eclipse/eclipse-collections/pull/958
