### ISSUE TITLE
Update README to indicate Eclipse Collections is compatible with Java 8 +

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#963]
Eclipse Collections requires Java 8 to compile and run its tests, but is compatible with Java 8+ at runtime. Eclipse Collections is part of the OpenJDK Quality Outreach program as well and qualifies that it runs ok different versions of the OpenJDK.

https://wiki.openjdk.java.net/display/quality/Quality+Outreach

**Comment by nikhilnanivadekar** [comment]
Will fix this along with Readme updates for 10.3.0.

**Comment by nikhilnanivadekar** [comment]
@donraab I will not be adding this line 

> Eclipse Collections requires Java 8 to compile and run its tests

as it is already covered in Contributing.md. The compilation language is a better fit in the Contribution guide than in Readme.
