### ISSUE TITLE
Deprecate ImmutableArrayStack

### ISSUE THREAD

**Issue by rinatigati** [eclipse/eclipse-collections#976]
Was looking around in the jacoco-report found [here](https://github.com/eclipse/eclipse-collections/actions/runs/210283622) and noticed that **ImmutableArrayStack** under *org.eclipse.collections.impl.stack.immutable* only has 3% code coverage.

This would be a great first ticket for OSS contribution in my opinion because test coverage is always welcome. 😁 

EDIT:
I don't seem to be able to add Labels to issues so if anyone can add "good first issue" and "help wanted" that would be greatly appreciated!

**Comment by jjabamani-bny** [comment]
Can I please work on this?

**Comment by donraab** [comment]
Interesting... This class should be deprecated as I believe it is no longer used. @motlin introduced a new implementation for immutable stacks which effectively replaced ImmutableArrayStack. There is no way to create this class outside of its package. If we deprecate it in the the 11.0 release, we can then remove it in 12.0.

**Comment by nikhilnanivadekar** [comment]
We cannot mark  anything for removal as that annotation was introduced in Java 9

**Comment by rinatigati** [comment]
According to this, https://docs.oracle.com/javase/7/docs/api/java/lang/Deprecated.html, @Deprecated has been around since Java 5.
We can't use the forRemoval optional attribute since it was added in Java 9, but we can still use the annotation right?

Maybe I'm missing something.

**Comment by donraab** [comment]
I would just putting the removal comment in a todo so we have a reminder. We could also just deprecate and never remove. This would guarantee we never break serialization/deserialization of the class, but then this would suggest we should test it.

**Comment by nikhilnanivadekar** [comment]
We should test it and keep it.

**Comment by donraab** [comment]
Sounds like we have consensus on keeping it and testing it. Two things to do. This issue will cover item 1.

1. Deprecate the class and comment on the new replacement and include a comment to ensure we will keep the class for serialization
2. Write dedicated tests for the existing class

**Comment by jjabamani-bny** [comment]
> Sounds like we have consensus on keeping it and testing it. Two things to do. This issue will cover item 1.
> 
>     1. Deprecate the class and comment on the new replacement and include a comment to ensure we will keep the class for serialization
> 
>     2. Write dedicated tests for the existing class

Don, Can you help me and @rinatigati understand the need for serialization/deserialization of a deprecated class?

**Comment by donraab** [comment]
@jjabamani-bny @rinatigati The problem is this. If someone serializes an ImmutableArrayStack to some persistent store (disk) in a version of Eclipse Collections before 10.3 and attempts to later deserialize the class instances from that persistent store with a version of Eclipse Collections without the class available, they will have an unsolvable issue.
