### ISSUE TITLE
Create Eclipse Collections and JDK compatibility table in Readme and website.

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#985]
Different versions of Eclipse Collections are compatible with different versions of Java. We should have an easy reference table to denote the compatibility.

**Comment by MantriAditi** [comment]
hi @donraab , I want to work on this issue, can u please assign this to me.

**Comment by donraab** [comment]
Thanks for volunteering @MantriAditi. I've assigned the issue to you.
