### ISSUE TITLE
Test Coverage: BagAddOccurrencesProcedure

### ISSUE THREAD

**Issue by johnjstuart** [eclipse/eclipse-collections#989]
`BagAddOccurrencesProcedure` currently has 0% test coverage. Add unit tests for this class.

**Comment by jonathansamuel-bnym** [comment]
@donraab Please assign this issue to me.

**Comment by donraab** [comment]
Hi @jonathansamuel-bnym, I've assigned the ticket to you. Thank you for volunteering!

**Comment by jonathansamuel-bnym** [comment]
I have completed the test cases for BagAddOccurrencesProcedure. Will be submitting a pull request shortly.
