### ISSUE TITLE
Test Coverage: SumOf(PrimitiveType)Procedure

### ISSUE THREAD

**Issue by johnjstuart** [eclipse/eclipse-collections#991]
All of the `SumOf<PrimitiveType>Procedure` classes currently have 0% test coverage. Create a template with unit tests for these classes.

**Comment by donraab** [comment]
Hi @johnjstuart, `SumOfShortProcedure` is a generated class. We would want tests for all of the primitive types (`SumOfLongProcedure`, `SumOfDoubleProcedure`, etc.). We should collapse all of the SumOfTypeProcedure issues into a single issue. 

I explain a little bit about how the code generation for primitive types works in Eclipse Collections here for folks looking into this issue:

https://stackoverflow.com/questions/61386226/resources-for-understanding-fastutil-internals/61400271#61400271

**Comment by donraab** [comment]
@johnjstuart I'm changing this issue to reflect that this needs to have a generated test class for all primitive types.
